### ISSUE TITLE
[Accepted] SDL 0032 - Delegate Support for all onHMIStatus State Changes

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_evolution#101]
Hello SDL community,

The review of "Delegate Support for all onHMIStatus State Changes" begins now and runs through March 7, 2017. The proposal is available here:

https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0032-on-hmi-status-state-changes.md

Reviews are an important part of the SDL evolution process. All reviews should be sent to the associated Github issue at:

https://github.com/smartdevicelink/sdl_evolution/issues/101

What goes into a review?

The goal of the review process is to improve the proposal under review through constructive criticism and, eventually, determine the direction of SDL. When writing your review, here are some questions you might want to answer in your review:

* Is the problem being addressed significant enough to warrant a change to SDL?
* Does this proposal fit well with the feel and direction of SDL?
* If you have used competitors with a similar feature, how do you feel that this proposal compares to those?
* How much effort did you put into your review? A glance, a quick reading, or an in-depth study?
Please state explicitly whether you believe that the proposal should be accepted into SDL.

More information about the SDL evolution process is available at

https://github.com/smartdevicelink/sdl_evolution/blob/master/process.md

Thank you,
Theresa Lech

Program Manager - Livio
theresa@livio.io

**Comment by ssolovey** [comment]
It will most probably will require some changes in API on core side.
Otherwise, it is fine with Luxoft team and we vote "Yay" for this.

**Comment by joeljfischer** [comment]
@ssolovey this is purely an iOS library change. There are no rpcs or anything else affected.

**Comment by theresalech** [comment]
The Steering Committee fully agreed to accept this proposal.

**Comment by theresalech** [comment]
Issue entered: [[SDL 0032] Delegate Support for all onHMIStatus State Changes](https://github.com/smartdevicelink/sdl_ios/issues/569)
