### ISSUE TITLE
[Accepted with Revisions] SDL 0305 - Homogenize TextFieldName

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_evolution#1020]
Hello SDL community,

The review of "SDL 0305 - Homogenize TextFieldName"  begins now and runs through June 2, 2020.  The proposal is available here:

https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0305-homogenize-textfieldname.md

Reviews are an important part of the SDL evolution process. All reviews should be sent to the associated Github issue at:

https://github.com/smartdevicelink/sdl_evolution/issues/1020

What goes into a review?

The goal of the review process is to improve the proposal under review through constructive criticism and, eventually, determine the direction of SDL. When writing your review, here are some questions you might want to answer in your review:

* Is the problem being addressed significant enough to warrant a change to SDL?
* Does this proposal fit well with the feel and direction of SDL?
* If you have used competitors with a similar feature, how do you feel that this proposal compares to those?
* How much effort did you put into your review? A glance, a quick reading, or an in-depth study?
Please state explicitly whether you believe that the proposal should be accepted into SDL.

More information about the SDL evolution process is available at

https://github.com/smartdevicelink/sdl_evolution/blob/master/process.md

Thank you,
Theresa Lech

Program Manager - Livio
theresa@livio.io

**Comment by joeljfischer** [comment]
1\. I would request that there be documentation for all of the enum values to contain information like the RPC and param name.

**Comment by Sohei-Suzuki-Nexty** [comment]
2.
>notificationText is removed because it does not exist in the MOBILE_API.xml and is not used currently.

How did you decide that it is not currently used?
Did you decided based on whether it is used by RPC or not, as well as the elements added to MOBILE_API?

**Comment by iCollin** [comment]
1. 
> I would request that there be documentation for all of the enum values to contain information like the RPC and param name.

This could be helpful but also might be difficult to maintain. I think this type of documentation would be easier to maintain near the RPC parameter that uses text fields. for example, here is `UI.Show.showStrings` in `HMI_API.xml`:

```
    <param name="showStrings" type="Common.TextFieldStruct" mandatory="true" array="true" minsize="0" maxsize="8">
      <description>Array of lines of show text fields. See TextFieldStruct. If some field is not set, the corresponding text should stay unchanged. If field's text is empty "", the field must be cleared.
          mainField1: The text that should be displayed in a single or upper display line.
          mainField2: The text that should be displayed on the second display line.
          mainField3: The text that should be displayed on the second "page" first display line.
          mainField4: The text that should be displayed on the second "page" second display line.
          templateTitle: The title of the new template that will be displayed.
          statusBar: statusBar.
          mediaClock: Text value for MediaClock field.
          mediaTrack: The text that should be displayed in the track field. This field is only valid for media applications on NGN type ACMs.
      </description>
    </param>
```

What do you think of documenting this info at each `TextField` parameter (only some have this now)? Otherwise, did you have a format in mind to document this info within the `TextFieldName` enum?

2.

> How did you decide that notificationText is not currently used?

I determined this by searching through SDL Core and SDL HMI code. `notificationText` does not appear at all in the SDL HMI and in SDL Core only appears in code to add a mapping from the string `notificationText` to the enum value.

**Comment by joeljfischer** [comment]
1. My comment was based on the documentation in this proposal:

```xml
<description>Navigation text for UpdateTurnList.</description>
```

You can see that this kind of documentation exists elsewhere in `TextFieldName` (https://github.com/smartdevicelink/rpc_spec/blob/master/MOBILE_API.xml#L753).

**Comment by iCollin** [comment]
> 1. My comment was based on the documentation in this proposal:
> 
> You can see that this kind of documentation exists elsewhere in `TextFieldName`.

Gotcha. I think that is a good idea.

**Comment by theresalech** [comment]
The Steering Committee voted to accept this proposal with the following revision: add requirement for documentation of enum values, as described in [this comment](https://github.com/smartdevicelink/sdl_evolution/issues/1020#issuecomment-637740732).

**Comment by theresalech** [comment]
@iCollin please advise when a new PR has been entered to update the proposal to reflect the agreed upon revisions. I'll then merge the PR so the proposal is up to date, and enter issues in impacted repositories for implementation. Thanks!

**Comment by iCollin** [comment]
@theresalech Hello, I have created a PR with the requested revisions: https://github.com/smartdevicelink/sdl_evolution/pull/1029

Thank you!

**Comment by theresalech** [comment]
The author has updated the proposal to include the requested revisions, and implementation issues have been entered:
- [RPC](https://github.com/smartdevicelink/rpc_spec/issues/253)
- [Core](https://github.com/smartdevicelink/sdl_core/issues/3419)
- [Generic HMI](https://github.com/smartdevicelink/generic_hmi/issues/274)
- [SDL HMI](https://github.com/smartdevicelink/sdl_hmi/issues/371)
- [iOS](https://github.com/smartdevicelink/sdl_ios/issues/1676)
- [Java Suite](https://github.com/smartdevicelink/sdl_java_suite/issues/1367)
- [JavaScript Suite](https://github.com/smartdevicelink/sdl_javascript_suite/issues/229)
