### ISSUE TITLE
[Accepted] SDL 0279 Revisions - Screen Manager Subscribe Buttons

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_evolution#1035]
Hello SDL community,

The review of "Revise SDL-0279 - Screen Manager Subscribe Buttons" begins now and runs through June 16, 2020.

This will be a review of proposed revisions to a previously accepted but not yet implemented proposal, [SDL 0279](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0279-screen-manager-subscribe-buttons.md).  

The pull request outlining the revisions under review is available here:

https://github.com/smartdevicelink/sdl_evolution/pull/1025

Reviews are an important part of the SDL evolution process. All reviews should be sent to the associated Github issue at:

https://github.com/smartdevicelink/sdl_evolution/issues/1035

What goes into a review?

The goal of the review process is to improve the proposal under review through constructive criticism and, eventually, determine the direction of SDL. When writing your review, here are some questions you might want to answer in your review:

* Is the problem being addressed significant enough to warrant a change to SDL?
* Does this proposal fit well with the feel and direction of SDL?
* If you have used competitors with a similar feature, how do you feel that this proposal compares to those?
* How much effort did you put into your review? A glance, a quick reading, or an in-depth study?
Please state explicitly whether you believe that the proposal should be accepted into SDL.

More information about the SDL evolution process is available at

https://github.com/smartdevicelink/sdl_evolution/blob/master/process.md

Thank you,
Theresa Lech

Program Manager - Livio
theresa@livio.io

**Comment by kshala-ford** [comment]
The revision makes sense to me. I don't have any strong opinion to the following question (just for my understanding):

```objc
- (void)unsubscribeButton:(SDLButtonName)buttonName withObserver:(id<NSObject>)observer withCompletionHandler:(SDLScreenManagerUpdateCompletionHandler)completionHandler;
```

So on iOS when you add a listener for a button name you'll receive an observer object. Now when you unsubscribe I'm wondering if the observer object isn't enough to identify the button name it was subscribed/added to. Are you planning to return the same observer object multiple times? What if `buttonName` *and* `observer` don't make a subscription?

**Comment by joeljfischer** [comment]
@kshala-ford That changed `unsubscribe` method is due to a method that did not change in this revision:

```
- (void)subscribeButton:(SDLButtonName)buttonName withObserver:(id<NSObject>)observer selector:(SEL)selector;
```

Because in this method the observer is passed to the manager, the observer could watch multiple button name callbacks, potentially with multiple selectors. Because of this you need a way to match the button name and observer to only unsubscribe that particular button name for the observer object.

**Comment by theresalech** [comment]
The Steering Committee fully agreed to accept these changes.

**Comment by theresalech** [comment]
Comments have been left on implementation issues to describe accepted changes:
- [Java Suite](https://github.com/smartdevicelink/sdl_java_suite/issues/1280)
- [iOS](https://github.com/smartdevicelink/sdl_ios/issues/1563)
- [JavaScript Suite](https://github.com/smartdevicelink/sdl_javascript_suite/issues/118)
