### ISSUE TITLE
[Accepted] SDL 0278 Revisions - Screen Manager Template Management

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_evolution#1038]
Hello SDL community,

The review of "Revise SDL-0278 - Screen Manager Template Management" begins now and runs through June 30, 2020.

This will be a review of proposed revisions to a previously accepted but not yet implemented proposal, [SDL 0278](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0278-screenmanager-layout-management.md).  

The pull request outlining the revisions under review is available here:

https://github.com/smartdevicelink/sdl_evolution/pull/1015

Reviews are an important part of the SDL evolution process. All reviews should be sent to the associated Github issue at:

https://github.com/smartdevicelink/sdl_evolution/issues/1038

What goes into a review?

The goal of the review process is to improve the proposal under review through constructive criticism and, eventually, determine the direction of SDL. When writing your review, here are some questions you might want to answer in your review:

* Is the problem being addressed significant enough to warrant a change to SDL?
* Does this proposal fit well with the feel and direction of SDL?
* If you have used competitors with a similar feature, how do you feel that this proposal compares to those?
* How much effort did you put into your review? A glance, a quick reading, or an in-depth study?
Please state explicitly whether you believe that the proposal should be accepted into SDL.

More information about the SDL evolution process is available at

https://github.com/smartdevicelink/sdl_evolution/blob/master/process.md

Thank you,
Theresa Lech

Program Manager - Livio
theresa@livio.io

**Comment by kshala-ford** [comment]
Just to confirm. This proposal is not implemented yet in a release? This revision would therefore not cause a breaking change?

**Comment by joeljfischer** [comment]
@kshala-ford That's correct. We were hoping to have it in this release, but the changes in this revision mean that it has to wait for the Taskmaster changes in Java Suite 4.12, so it has to wait.

**Comment by theresalech** [comment]
We did not have a quorum present during the 2020-07-07 Steering Committee meeting, so voting on this proposal could not take place.  This proposal will remain in review until 2020-07-14.

**Comment by theresalech** [comment]
The Steering Committee fully agreed to accept these revisions.

**Comment by theresalech** [comment]
Comments left on implementation issues:
- [iOS](https://github.com/smartdevicelink/sdl_ios/issues/1612)
- [Java Suite](https://github.com/smartdevicelink/sdl_java_suite/issues/1327)
- [JavaScript Suite](https://github.com/smartdevicelink/sdl_javascript_suite/issues/175)
