### ISSUE TITLE
[Accepted with Revisions] SDL 0296 Revisions - Possibility to update video streaming capabilities during ignition cycle

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_evolution#1059]
Hello SDL community,

The review of "Revise SDL-0296 - Possibility to update video streaming capabilities during ignition cycle" begins now and runs through August 4, 2020.

This will be a review of proposed revisions to a previously accepted but not yet implemented proposal, [SDL 0296](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0296-Update-video-streaming-capabilities-during-ignition-cycle.md).  

The pull request outlining the revisions under review is available here:

https://github.com/smartdevicelink/sdl_evolution/pull/1055

Reviews are an important part of the SDL evolution process. All reviews should be sent to the associated Github issue at:

https://github.com/smartdevicelink/sdl_evolution/issues/1059

What goes into a review?

The goal of the review process is to improve the proposal under review through constructive criticism and, eventually, determine the direction of SDL. When writing your review, here are some questions you might want to answer in your review:

* Is the problem being addressed significant enough to warrant a change to SDL?
* Does this proposal fit well with the feel and direction of SDL?
* If you have used competitors with a similar feature, how do you feel that this proposal compares to those?
* How much effort did you put into your review? A glance, a quick reading, or an in-depth study?
Please state explicitly whether you believe that the proposal should be accepted into SDL.

More information about the SDL evolution process is available at

https://github.com/smartdevicelink/sdl_evolution/blob/master/process.md

Thank you,
Theresa Lech

Program Manager - Livio
theresa@livio.io

**Comment by joeljfischer** [comment]
1\. The Java versions appears to be missing some methods that are available on iOS:

```objc
// Check if the argument is within the [.minimumResolution, .maximumResolution] range
- (BOOL)isImageResolutionInRange:(SDLImageResolution*)imageResolution;
// Check if the argument is within the [.minimumAspectRatio, .maximumAspectRatio] range
- (BOOL)isAspectRatioInRange:(float)aspectRatio;
```

2\. The `Resolution Switching` section has become a sub-section of `JavaScript APIs`, was that intentional?

**Comment by dboltovskyi** [comment]
2. 
That's a mistake that needs to be corrected: `JavaScript APIs` section has to be after `Resolution Switching`

**Comment by dboltovskyi** [comment]
1.
It was not planned initially to have these methods. But in order to have better alignment with iOS changes we would propose to add the similar methods for Android:
```
public Boolean isImageResolutionInRange(VideoStreamingRange range, ImageResolution currentResolution)
public Boolean isAspectRatioInRange(VideoStreamingRange range, ImageResolution currentResolution)
```

**Comment by joeljfischer** [comment]
👍

**Comment by theresalech** [comment]
The Steering Committee voted to accept this proposal with revisions.  The author will move the `JavaScript API` section after `Resolution Switching` and also add the following methods to Android:

```
public Boolean isImageResolutionInRange(VideoStreamingRange range, ImageResolution currentResolution)
public Boolean isAspectRatioInRange(VideoStreamingRange range, ImageResolution currentResolution)
```

**Comment by theresalech** [comment]
@dboltovskyi please advise when your PR has been updated to reflect the agreed upon revisions. I'll then merge the PR so the proposal is up to date, and leave comments on the implementation issues to reference these updates. Thanks!

**Comment by theresalech** [comment]
Author has updated proposal to reflect agreed upon revisions, and comments have been left on implementation issues:
- [Core](https://github.com/smartdevicelink/sdl_core/issues/3465)
- [Generic HMI](https://github.com/smartdevicelink/generic_hmi/issues/290)
- [SDL HMI](https://github.com/smartdevicelink/sdl_hmi/issues/390)
- [iOS](https://github.com/smartdevicelink/sdl_ios/issues/1730)
- [Java Suite](https://github.com/smartdevicelink/sdl_java_suite/issues/1120)

Issues were projects now impacted by this feature:
- [RPC](https://github.com/smartdevicelink/rpc_spec/issues/273)
- [JavaScript Suite](https://github.com/smartdevicelink/sdl_javascript_suite/issues/290)
