### ISSUE TITLE
[Accepted with Revisions] SDL 0242 Revisions - Subtle Alert Style

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_evolution#1060]
Hello SDL community,

The review of "Revise SDL-0242 Subtle Alert Style - Add SubtleAlert Response" begins now and runs through August 4, 2020.

This will be a review of proposed revisions to a previously accepted but not yet implemented proposal, [SDL 0242](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0242-alert-style-subtle.md).  

The pull request outlining the revisions under review is available here:

https://github.com/smartdevicelink/sdl_evolution/pull/1056

Reviews are an important part of the SDL evolution process. All reviews should be sent to the associated Github issue at:

https://github.com/smartdevicelink/sdl_evolution/issues/1060

What goes into a review?

The goal of the review process is to improve the proposal under review through constructive criticism and, eventually, determine the direction of SDL. When writing your review, here are some questions you might want to answer in your review:

* Is the problem being addressed significant enough to warrant a change to SDL?
* Does this proposal fit well with the feel and direction of SDL?
* If you have used competitors with a similar feature, how do you feel that this proposal compares to those?
* How much effort did you put into your review? A glance, a quick reading, or an in-depth study?
Please state explicitly whether you believe that the proposal should be accepted into SDL.

More information about the SDL evolution process is available at

https://github.com/smartdevicelink/sdl_evolution/blob/master/process.md

Thank you,
Theresa Lech

Program Manager - Livio
theresa@livio.io

**Comment by ShobhitAd** [comment]
I think the `tryAgainTime` parameter in the `SubtleAlert` response should be in **milliseconds** to match to match the SubtleAlert response in the HMI_API https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0242-alert-style-subtle.md#hmi_api-changes. I've requested changes in the revision PR

**Comment by theresalech** [comment]
The Steering Committee voted to accept this proposal with the following revision: change the `tryAgainTime` parameter in the `SubtleAlert` response to be in milliseconds instead of seconds.

**Comment by theresalech** [comment]
@joeljfischer please advise when your PR has been updated to reflect the agreed upon revisions. I'll then merge the PR so the proposal is up to date, and leave comments on the implementation issues to reference these updates. Thanks!

**Comment by theresalech** [comment]
Author has updated proposal to reflect agreed upon revisions, and comments have been left on implementation issues:
- [Core](https://github.com/smartdevicelink/sdl_core/issues/2969)
- [RPC](https://github.com/smartdevicelink/rpc_spec/issues/182)
- [Generic HMI](https://github.com/smartdevicelink/generic_hmi/issues/180)
- [SDL HMI](https://github.com/smartdevicelink/sdl_hmi/issues/207)
- [iOS](https://github.com/smartdevicelink/sdl_ios/issues/1355)
- [Java Suite](https://github.com/smartdevicelink/sdl_java_suite/issues/1120)
- [JavaScript Suite](https://github.com/smartdevicelink/sdl_javascript_suite/issues/256)
- [SDL Server](https://github.com/smartdevicelink/sdl_server/issues/152)
- [Manticore](https://github.com/smartdevicelink/manticore/issues/86)
