### ISSUE TITLE
[Accepted with Revisions] SDL 0318 - App Library: Vehicle Data Manager

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_evolution#1071]
Hello SDL community,

The review of "SDL 0318 - App Library: Vehicle Data Manager"  begins now and runs through August 25, 2020.  The proposal is available here:

https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0318-app-lib-vehicle-data-manager.md

Reviews are an important part of the SDL evolution process. All reviews should be sent to the associated Github issue at:

https://github.com/smartdevicelink/sdl_evolution/issues/1071

What goes into a review?

The goal of the review process is to improve the proposal under review through constructive criticism and, eventually, determine the direction of SDL. When writing your review, here are some questions you might want to answer in your review:

* Is the problem being addressed significant enough to warrant a change to SDL?
* Does this proposal fit well with the feel and direction of SDL?
* If you have used competitors with a similar feature, how do you feel that this proposal compares to those?
* How much effort did you put into your review? A glance, a quick reading, or an in-depth study?
Please state explicitly whether you believe that the proposal should be accepted into SDL.

More information about the SDL evolution process is available at

https://github.com/smartdevicelink/sdl_evolution/blob/master/process.md

Thank you,
Theresa Lech

Program Manager - Livio
theresa@livio.io

**Comment by joeljfischer** [comment]
As I re-read this, I've noticed a few things:

1\. In [this section](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0318-app-lib-vehicle-data-manager.md#cached-data-1), the method name should be `getVehicleData`. In [this section](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0318-app-lib-vehicle-data-manager.md#retrieving-updated-data-1), `updateCapabilities` should be named `updateVehicleData`. In [this section](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0318-app-lib-vehicle-data-manager.md#retrieving-updated-data-2) the method should be named `updateVehicleData`.

**Comment by joeljfischer** [comment]
2\. Additionally, in [this section](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0318-app-lib-vehicle-data-manager.md#java-suite), the method names should be `addPermissionListener` and `removePermissionListener`. In [this section](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0318-app-lib-vehicle-data-manager.md#javascript-suite), the method names should be `addPermissionListener` and `removePermissionListener`.

**Comment by theresalech** [comment]
The Steering Committee voted to accept this proposal with revisions. In [this section](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0318-app-lib-vehicle-data-manager.md#cached-data-1), the method name should be `getVehicleData`. In [this section](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0318-app-lib-vehicle-data-manager.md#retrieving-updated-data-1), `updateCapabilities` should be named `updateVehicleData`. In [this section](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0318-app-lib-vehicle-data-manager.md#retrieving-updated-data-2) the method should be named `updateVehicleData`. Additionally, in [this section](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0318-app-lib-vehicle-data-manager.md#java-suite), the method names should be `addPermissionListener` and `removePermissionListener`. In [this section](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0318-app-lib-vehicle-data-manager.md#javascript-suite), the method names should be `addPermissionListener` and `removePermissionListener`.

**Comment by theresalech** [comment]
@joeljfischer please advise when a new PR has been entered to update the proposal to reflect the agreed upon revisions. I'll then merge the PR so the proposal is up to date, and enter issues in impacted repositories for implementation. Thanks!

**Comment by theresalech** [comment]
Proposal has been updated and implementation issues have been entered:
- [iOS](https://github.com/smartdevicelink/sdl_ios/issues/1769)
- [Java Suite](https://github.com/smartdevicelink/sdl_java_suite/issues/1484)
- [JavaScript Suite](https://github.com/smartdevicelink/sdl_javascript_suite/issues/308)
