### ISSUE TITLE
[In Review] SDL 0323 - Align video streaming parameters with VideoStreamingCapability

### ISSUE THREAD

**Issue by jordynmackool** [smartdevicelink/sdl_evolution#1094]
Hello SDL community,

The review of "SDL 0323 - Align video streaming parameters with VideoStreamingCapability" begins now and runs through November 24, 2020.  The proposal is available here:

https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0323-align-VideoStreamingParameter-with-capability.md

Reviews are an important part of the SDL evolution process. All reviews should be sent to the associated Github issue at:

https://github.com/smartdevicelink/sdl_evolution/issues/1094

What goes into a review?

The goal of the review process is to improve the proposal under review through constructive criticism and, eventually, determine the direction of SDL. When writing your review, here are some questions you might want to answer in your review:

* Is the problem being addressed significant enough to warrant a change to SDL?
* Does this proposal fit well with the feel and direction of SDL?
* If you have used competitors with a similar feature, how do you feel that this proposal compares to those?
* How much effort did you put into your review? A glance, a quick reading, or an in-depth study?
Please state explicitly whether you believe that the proposal should be accepted into SDL.

More information about the SDL evolution process is available at

https://github.com/smartdevicelink/sdl_evolution/blob/master/process.md

Thank you,
Jordyn Mackool 

Program Manager - Livio
Jordyn@livio.io

**Comment by joeljfischer** [comment]
LGTM from an iOS side

**Comment by jordynmackool** [comment]
The Steering Committee voted to accept the proposal. Xevo, the authoring company of the proposal shared that this proposal's [motivation](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0323-align-VideoStreamingParameter-with-capability.md#motivation) was found while working on the implementation for [SDL 0274](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0274-add-preferred-FPS.md) (an already accepted proposal).

**Comment by jordynmackool** [comment]
Issues have been entered:
- [iOS](https://github.com/smartdevicelink/sdl_ios/issues/1860)
- [Java Suite](https://github.com/smartdevicelink/sdl_java_suite/issues/1569)
