### ISSUE TITLE
[In Review] SDL 0034 - Rename Cocoapods Project to "SmartDeviceLink"

### ISSUE THREAD

**Issue by pelsila** [smartdevicelink/sdl_evolution#111]
Hello SDL community,

The review of "Rename Cocoapods Project to "SmartDeviceLink"

" begins now and runs through 3/21/2017. The proposal is available here:

https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0034-ios-cocoapods-rename.md

Reviews are an important part of the SDL evolution process. All reviews should be sent to the associated Github issue at:

https://github.com/smartdevicelink/sdl_evolution/issues/111

What goes into a review?

The goal of the review process is to improve the proposal under review through constructive criticism and, eventually, determine the direction of SDL. When writing your review, here are some questions you might want to answer in your review:

* Is the problem being addressed significant enough to warrant a change to SDL?
* Does this proposal fit well with the feel and direction of SDL?
* If you have used competitors with a similar feature, how do you feel that this proposal compares to those?
* How much effort did you put into your review? A glance, a quick reading, or an in-depth study?
Please state explicitly whether you believe that the proposal should be accepted into SDL.

More information about the SDL evolution process is available at

https://github.com/smartdevicelink/sdl_evolution/blob/master/process.md

Thank you,
Paul Elsila
Livio
paul@livio.io

**Comment by theresalech** [comment]
The Steering Committee has accepted this proposal as we will need to rename Cocoapods as a result of the accepted [Redesign iOS Logging proposal](https://github.com/smartdevicelink/sdl_evolution/issues/93).  The Redesign iOS Logging proposal contains a separate swift library to make logging easier, but will not work if using Cocoapods.

**Comment by theresalech** [comment]
Issue entered: [[SDL 0034] Rename Cocoapods Project to "SmartDeviceLink"](https://github.com/smartdevicelink/sdl_ios/issues/584)
