### ISSUE TITLE
[In Review] Revise SDL 0267 Main Menu UI Updates

### ISSUE THREAD

**Issue by jordynmackool** [smartdevicelink/sdl_evolution#1114]
Hello SDL community,

The review of "Revise SDL 0267 Main Menu UI Updates" begins now and continues through January 19, 2021.

This will be a review of proposed revisions to a previously accepted but not yet implemented proposal, [SDL 0267](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0267-addcommand-ui-updates.md).  

The pull request outlining the revisions under review is available here:

https://github.com/smartdevicelink/sdl_evolution/pull/1111

Reviews are an important part of the SDL evolution process. All reviews should be sent to the associated Github issue at:

https://github.com/smartdevicelink/sdl_evolution/issues/1114

What goes into a review?

The goal of the review process is to improve the proposal under review through constructive criticism and, eventually, determine the direction of SDL. When writing your review, here are some questions you might want to answer in your review:

* Is the problem being addressed significant enough to warrant a change to SDL?
* Does this proposal fit well with the feel and direction of SDL?
* If you have used competitors with a similar feature, how do you feel that this proposal compares to those?
* How much effort did you put into your review? A glance, a quick reading, or an in-depth study?
Please state explicitly whether you believe that the proposal should be accepted into SDL.

More information about the SDL evolution process is available at

https://github.com/smartdevicelink/sdl_evolution/blob/master/process.md

Thank you,
Jordyn Mackool

Program Manager - Livio
jordyn@livio.io

**Comment by Sohei-Suzuki-Nexty** [comment]
1.In the original proposal, the RPC spec has similar parameter additions, 
but in this revision, since it is only for HMI_API, we think that the parameter implementation will be different between MOBILE and HMI.
Isn't this a problem?

**Comment by kshala-ford** [comment]
1\\. In the HMI API both, `AddSubMenu` and `AddCommand` rely on `MenuParams` for text fields. However, in the Mobile API, `AddSubMenu` doesn't. This is the current situation since long time, before this proposal existed. This revision aligns better with the current situation of the APIs.

**Comment by Sohei-Suzuki-Nexty** [comment]
@kshala-ford -san 
Thank you for your reply.
1.I understand that this proposal matches the current implementation.
I think there is no problem.

**Comment by jordynmackool** [comment]
The Steering Committee voted on 2021-01-19 to accept the revisions to this proposal.

**Comment by jordynmackool** [comment]
Comments have been left on implementation issues to reference revisions:

**Comment by jordynmackool** [comment]
Comments have been left on implementation issues to reference revisions:

- [Core](https://github.com/smartdevicelink/sdl_core/issues/3195)
- [rpc spec](https://github.com/smartdevicelink/rpc_spec/issues/213)
- [sdl hmi](https://github.com/smartdevicelink/sdl_hmi/issues/268)
- [generic hmi](https://github.com/smartdevicelink/generic_hmi/issues/230)
- [ios](https://github.com/smartdevicelink/sdl_ios/issues/1510)
- [java suite](https://github.com/smartdevicelink/sdl_java_suite/issues/1246)
- [javascript suite](https://github.com/smartdevicelink/sdl_javascript_suite/issues/348)
