### ISSUE TITLE
[In Review] Revise SDL-0180 - Broaden Choice Uniqueness

### ISSUE THREAD

**Issue by jordynmackool** [smartdevicelink/sdl_evolution#1116]
Hello SDL community,

The review of "Revise SDL-0180 - Broaden Choice Uniqueness" begins now and continues through January 26, 2021.

This will be a review of proposed revisions to a previously accepted but not yet implemented proposal, [SDL 0180](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0180-broaden-choice-uniqueness.md).  

The pull request outlining the revisions under review is available here:

https://github.com/smartdevicelink/sdl_evolution/pull/1115

Reviews are an important part of the SDL evolution process. All reviews should be sent to the associated Github issue at:

https://github.com/smartdevicelink/sdl_evolution/issues/1116

What goes into a review?

The goal of the review process is to improve the proposal under review through constructive criticism and, eventually, determine the direction of SDL. When writing your review, here are some questions you might want to answer in your review:

* Is the problem being addressed significant enough to warrant a change to SDL?
* Does this proposal fit well with the feel and direction of SDL?
* If you have used competitors with a similar feature, how do you feel that this proposal compares to those?
* How much effort did you put into your review? A glance, a quick reading, or an in-depth study?
Please state explicitly whether you believe that the proposal should be accepted into SDL.

More information about the SDL evolution process is available at

https://github.com/smartdevicelink/sdl_evolution/blob/master/process.md

Thank you,
Jordyn Mackool

Program Manager - Livio
jordyn@livio.io

**Comment by kshala-ford** [comment]
The additional documentation looks good to me. It's not part of the revision update but how are you planning to detect a system not supporting duplicate primary text? I assume by RPC spec version?

> In the mobile libraries, if it is detected that we are working with an SDL system that does not support duplicate primary text (based on the RPC version), we should append "(1)", "(2)", etc. after duplicate primary texts in the following way:

**Comment by joeljfischer** [comment]
Thanks for taking a look. I'll number that as (1) for future reference if there are additional points to be made:

1\. Yes, I'm sorry that it wasn't explicitly stated, but yes, using the RPC spec version.

**Comment by jordynmackool** [comment]
The Steering Committee voted on 2021-01-26 to accept these proposed revisions.

**Comment by jordynmackool** [comment]
Comments have been left on implementation issues to reference revisions:

- [Core](https://github.com/smartdevicelink/sdl_core/issues/2346)
- [ios](https://github.com/smartdevicelink/sdl_ios/issues/1024)
- [java suite](https://github.com/smartdevicelink/sdl_java_suite/issues/811)
- [javascript suite](https://github.com/smartdevicelink/sdl_javascript_suite/issues/345)
