### ISSUE TITLE
[Accepted with Revisions] SDL 0334 - Transform SetDisplayLayout requests into UI.Show for HMIs

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_evolution#1141]
Hello SDL community,

The review of "SDL 0334 - Transform SetDisplayLayout requests into UI.Show for HMIs"  begins now and runs through May 18, 2021.  The proposal is available here:

https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0334-transform-setdisplaylayout-requests-to-ui-show.md

Reviews are an important part of the SDL evolution process. All reviews should be sent to the associated Github issue at:

https://github.com/smartdevicelink/sdl_evolution/issues/1141

What goes into a review?

The goal of the review process is to improve the proposal under review through constructive criticism and, eventually, determine the direction of SDL. When writing your review, here are some questions you might want to answer in your review:

* Is the problem being addressed significant enough to warrant a change to SDL?
* Does this proposal fit well with the feel and direction of SDL?
* If you have used competitors with a similar feature, how do you feel that this proposal compares to those?
* How much effort did you put into your review? A glance, a quick reading, or an in-depth study?
Please state explicitly whether you believe that the proposal should be accepted into SDL.

More information about the SDL evolution process is available at

https://github.com/smartdevicelink/sdl_evolution/blob/master/process.md

Thank you,
Theresa Lech

Program Manager - Livio
theresa@livio.io

**Comment by joeljfischer** [comment]
1\. Should this entirely remove `SetDisplayLayout` from the HMI_API? We don't consider breaking HMI changes to be breaking for Core releases.

**Comment by JackLivio** [comment]
1. I agree that we can remove SetDisplayLayout from the HMI_API entirely with this change.

**Comment by theresalech** [comment]
The Steering Committee agreed to accept this proposal with the revision of removing `SetDisplayLayout` from HMI_API.

**Comment by theresalech** [comment]
@ShobhitAd please advise when a new PR has been entered to update the proposal to reflect the agreed upon revisions. I'll then merge the PR so the proposal is up to date, and the Core issue for implementation. Thanks!

**Comment by theresalech** [comment]
Proposal has been updated to reflect revisions, and implementation issue has been entered: https://github.com/smartdevicelink/sdl_core/issues/3706
