### ISSUE TITLE
[Accepted with Revision] SDL 0003 - Last Mile Navigation

### ISSUE THREAD

**Issue by joeljfischer** [smartdevicelink/sdl_evolution#12]
Hello SDL community,

The review of "Last Mile Navigation" begins now and runs through August 23, 2016. The proposal is available here:

https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0003-last-mile-navigation.md

Reviews are an important part of the SDL evolution process. All reviews should be sent to the associated Github issue at:

https://github.com/smartdevicelink/sdl_evolution/issues/12

What goes into a review?

The goal of the review process is to improve the proposal under review through constructive criticism and, eventually, determine the direction of SDL. When writing your review, here are some questions you might want to answer in your review:

* Is the problem being addressed significant enough to warrant a change to SDL?
* Does this proposal fit well with the feel and direction of SDL?
* If you have used competitors with a similar feature, how do you feel that this proposal compares to those?
* How much effort did you put into your review? A glance, a quick reading, or an in-depth study?
Please state explicitly whether you believe that the proposal should be accepted into SDL.

More information about the SDL evolution process is available at

https://github.com/smartdevicelink/sdl_evolution/blob/master/process.md

Thank you,
Joel Fischer

SDL iOS Maintainer - Livio
joel@livio.io

**Comment by joeljfischer** [comment]
### Review
> Is the problem being addressed significant enough to warrant a change to SDL?

No, I don't believe this problem is significant enough to warrant a change. The usefulness of this feature to end users is quite small. Second, this feature requires a good number of changes to Core, Mobile, and the RPC spec. This feature essentially allows a user who navigated to a location on the head unit to have a nav app that's running to be able to continue navigation after you exit the vehicle. This is not especially useful for two reasons. For one, I believe the number of users who would use it is rather small. First, not many people are going to navigate using their car and then need to navigate via walking with any regularity. Second, the amount of time the feature saves a user doesn't seem especially significant. It would take a user 10-20 seconds to re-navigate on their phone if they do need to walk to a location. Since this feature would only save people a small amount of time, and that rarely, this feature does not seem to warrant inclusion and future upkeep.

> Does this proposal fit well with the feel and direction of SDL?

No, this proposal does not fit well with the feel and direction of SDL. We already have a mechanism for subscribing to data via VehicleData, and this proposal's implementation would probably fit better using that mechanism.

> If you have used competitors with a similar feature, how do you feel that this proposal compares to those?

No competitors have a similar feature, I believe it's because this proposal attempts to solve a non-existant problem.

> How much effort did you put into your review? A glance, a quick reading, or an in-depth study? Please state explicitly whether you believe that the proposal should be accepted into SDL.

I did somewhere between a quick reading and an in-depth study. I do not believe this proposal should be accepted into SDL.

**Comment by asm09fsu** [comment]
I'm really not sure what the usefulness of this in it's own as opposed to having it within SubscribeVehicleData and GetVehicleData. @robinmk can you please list the benefits of having Waypoints outside of the already existing object?

**Comment by joeljfischer** [comment]
This proposal is accepted contingent on changes being made in an additional pull request:
* The RPC ids must be changed as follows:

```xml
<element name="GetWayPointsID" value="45" hexvalue="2D" />
<element name="SubscribeWayPointsID" value="46" hexvalue="2E" />
<element name="UnsubscribeWayPointsID" value="47" hexvalue="2F" />
<element name="OnWayPointChangeID" value="32784" hexvalue="8010" />
```

**Comment by theresalech** [comment]
Issues entered:
[Android](https://github.com/smartdevicelink/sdl_android/issues/344)
[Core](https://github.com/smartdevicelink/sdl_core/issues/1275)
[iOS](https://github.com/smartdevicelink/sdl_ios/issues/457)
