### ISSUE TITLE
[Accepted] SDL 0040 - DTLS encryption

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_evolution#126]
Hello SDL community,

The review of the revised proposal "DTLS encryption" begins now and runs through April 11, 2017.  The original review of "DTLS encryption" occurred March 21, 2017 through March 28, 2017. The proposal is available here:

https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0040-DTLS-encryption.md

Reviews are an important part of the SDL evolution process. All reviews should be sent to the associated Github issue at:

https://github.com/smartdevicelink/sdl_evolution/issues/126

What goes into a review?

The goal of the review process is to improve the proposal under review through constructive criticism and, eventually, determine the direction of SDL. When writing your review, here are some questions you might want to answer in your review:

* Is the problem being addressed significant enough to warrant a change to SDL?
* Does this proposal fit well with the feel and direction of SDL?
* If you have used competitors with a similar feature, how do you feel that this proposal compares to those?
* How much effort did you put into your review? A glance, a quick reading, or an in-depth study?
Please state explicitly whether you believe that the proposal should be accepted into SDL.

More information about the SDL evolution process is available at

https://github.com/smartdevicelink/sdl_evolution/blob/master/process.md

Thank you,
Theresa Lech

Program Manager - Livio
theresa@livio.io

**Comment by stefanek22** [comment]
Agree with the proposal and definitely advocate support of DTLS for video encryption.  Through integration of SDL with TLS support, we found an absolute need to recover from malformed/missing packets, which is something DTLS offers over TLS.

**Comment by theresalech** [comment]
The author has asked that this proposal be deferred, as revisions are required before it's ready for review. The proposal will be unlocked and marked as "in review" when ready.

**Comment by joeljfischer** [comment]
Hi @mrapitis, correct me if I'm wrong, but this is not merely a Core change. The iOS open source security library (there does not appear to be an Android version) would need to support this as well, correct?

Additionally, how do we negotiate between iOS and Core whether we're using DTLS or TLS?

**Comment by mrapitis** [comment]
@joeljfischer we could create a branch of the sample security library that leverages DTLS for testing purposes.  We would need to update the line below to use DTLSv1_server_method as opposed to TLSv1_2_server_method.  
https://github.com/smartdevicelink/sdl_security_ios/blob/3c1908bd3555b5073c704df8d5ec03984dc2257d/SDLSecurity/_SDLTLSEngine.m#L130

SDL core will however still support TLS v1.2 via the existing ini file setting; it may be helpful to make this option configurable in the sample security library as well.

**Comment by joeljfischer** [comment]
@mrapitis I understand, but I believe it is (or should be) a requirement to have a sample security library for OEMs to know how to build their own. I believe it should be added to this proposal that sample mobile security library updates will be made to support this new protocol, if it is accepted.

But I'm not convinced on the premise of this proposal. Is it really desirable for DTLS to re-transmit packets? Wouldn't that involve so much latency that it's not worth it? Wouldn't it be better for the video frame (for example) to simply be dropped? I can perhaps see the usefulness on the RPC service.

**Comment by mrapitis** [comment]
@joeljfischer TLS v1.2 does not allow for dropped packets, in the case that packets are dropped the protocol becomes unusable.  I understand the need for sample security libraries; we could bundle the tasks into the current proposal, however it may be better to target the tasks separately -- especially since their is a larger scope of work around the samples security libraries.  For example, as was previously mentioned we need to add an Android sample security library repository and its associated code.  We also need to add other security communication protocols to the sample security libraries that core currently supports -- this seems to be outside of the scope of this proposal.

**Comment by joeljfischer** [comment]
@mrapitis Understood. I think we need to discuss the task of updating the security libraries (and creating one for Android) as part of the review of this proposal. It will be hard for OEMs to implement without example mobile code.

I believe this proposal should be accepted.

**Comment by theresalech** [comment]
The Steering Committee has agreed to accept this proposal.  They've also agreed that we should target Android and iOS library changes as an additional proposal, as this cannot be tested without the library portion.

**Comment by theresalech** [comment]
Issue entered: [[SDL 0040 DTLS encryption](https://github.com/smartdevicelink/sdl_core/issues/1479)
