### ISSUE TITLE
[In Review] SDL 0042 - SDL must transfer RPC’s with invalid image reference parameters to the HMI

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_evolution#128]
Hello SDL community,

The review of "SDL must transfer RPC’s with invalid image reference parameters to the HMI" begins now and runs through March 28, 2017. The proposal is available here:

https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0042-transfer-invalid-image-rpc.md

Reviews are an important part of the SDL evolution process. All reviews should be sent to the associated Github issue at:

https://github.com/smartdevicelink/sdl_evolution/issues/128

What goes into a review?

The goal of the review process is to improve the proposal under review through constructive criticism and, eventually, determine the direction of SDL. When writing your review, here are some questions you might want to answer in your review:

* Is the problem being addressed significant enough to warrant a change to SDL?
* Does this proposal fit well with the feel and direction of SDL?
* If you have used competitors with a similar feature, how do you feel that this proposal compares to those?
* How much effort did you put into your review? A glance, a quick reading, or an in-depth study?
Please state explicitly whether you believe that the proposal should be accepted into SDL.

More information about the SDL evolution process is available at

https://github.com/smartdevicelink/sdl_evolution/blob/master/process.md

Thank you,
Theresa Lech

Program Manager - Livio
theresa@livio.io

**Comment by ISHIZAKI-MASASHI** [comment]
@mrapitis 
How're you?
I'm MASASHI and an engineer from SUZUKI.

There are some questions as below. 
Could you explain that, if you don't mind?

1. What is the difference between "image" and "Image" in this proposal?
2. Not easy to imagine that "RPCs include an invalid Image reference"
    Could you give me examples or explain more in detail?

**Comment by mrapitis** [comment]
Hi @ISHIZAKI-MASASHI,

Thanks for your feedback.  Please find my response below.  Thanks!

* The references to image and Image actually have the same meaning.  The parameter of type 'Image' is the specific type in our mobile api specification (linked below).  Informally the parameter is referenced as an image type.

https://github.com/smartdevicelink/sdl_core/blob/master/src/components/interfaces/MOBILE_API.xml#L808-L815

* Currently if an RPC such as a show command makes a reference to an image that does not exist on the system for any reason, the image reference is considered invalid and the RPC will receive and invalid data response.  This proposal adds the capability for sdl to continue processing the RPC and warn the HMI that the image being referenced by the RPC does not exist on the system.  The HMI can then gracefully handle the request.

**Comment by joeljfischer** [comment]
> Is the problem being addressed significant enough to warrant a change to SDL?

This doesn't seem like a huge problem, but worth solving.

> Does this proposal fit well with the feel and direction of SDL?

I think both this solution and the alternative are plausible solutions.

> If you have used competitors with a similar feature, how do you feel that this proposal compares to those?

N/A

> How much effort did you put into your review? A glance, a quick reading, or an in-depth study?

A quick reading

> Please state explicitly whether you believe that the proposal should be accepted into SDL.

I believe this proposal should be accepted.

**Comment by mfoedisch** [comment]
Here are my concerns with this proposal:

- the definition of proposal makes sense; although the benefit of a somewhat different behavior doesn't seem to be clear. Aren't we just changing the system's response to a bug in a mobile application?

- I fully agree with the potential downsides:

> Since RPC's with invalid image references are processed successfully, the mobile app may be less likely to resolve logical errors in image processing.

- I could go almost either way with this proposal. Both the current definition of behavior and the proposed one make sense. Considering the somewhat limited benefit, however, I'd prefer not to change existing behavior.

**Comment by mrapitis** [comment]
@mfoedisch thanks again for your feedback.
One additional benefit not explicitly stated in the proposal is that an app could actually post load images.  An RPC request like a show command could be sent with a reference to an image that would be loaded onto the file system later.  After the image is successfully pushed to the file system, the HMI could be notified of the putfiles existence and update the display as needed.

**Comment by ISHIZAKI-MASASHI** [comment]
@mrapitis
Thank you for reply.

Could you tell me if my understandig is wrong?
■my understanding
Mobile app sends an RPC with an invalid image to SDL Core (which is in Head Unit?)
SDL Core validates the image parameter whether or not in the "AppStorageFolder".
The HMI judges how to respond to an RPC throgh SDL Core. 

Here are questions as below again.
Please answer these questions.
1. Who has the "AppStorageFolder"?   SDL Core? HMI? or other?
2. If you want the HMI to judge to respond to an RPC with the invalid image, should the HMI have the "AppStorageFolder" or not? Access limitation is necessary or not?

**Comment by mrapitis** [comment]
@ISHIZAKI-MASASHI Please find response below.  Thanks!

Who has the "AppStorageFolder"? SDL Core? HMI? or other?
*The AppStorageFolder should be available to both SDL Core and the HMI.  SDL Core will typically put a file in the AppStorageFolder at the request of the mobile application.  The HMI can then be notified that a file is available for its usage in the filesystem.

If you want the HMI to judge to respond to an RPC with the invalid image, should the HMI have the "AppStorageFolder" or not? Access limitation is necessary or not?
*The HMI shouldn't be limited as far as accessing the AppStorageFolder.  This proposal allows for the rpc to still be processed successfully (with warnings) even if the file is not (yet) available.

**Comment by Toyota-Sbetts** [comment]
This is a proposal we had also been considering raising and we support it.  While if the app is using Putfile, ListFiles and Show correctly they may not have an issue, it can be difficult for an app developer to figure out why an RPC is failing or handle all edge cases in the app logic.  As developers start using their apps on more HMIs that will have different policies, this change will allow HMI's to at least handle the valid data passed in the RPC instead of nothing at all.

**Comment by joeljfischer** [comment]
> One additional benefit not explicitly stated in the proposal is that an app could actually post load images. An RPC request like a show command could be sent with a reference to an image that would be loaded onto the file system later. After the image is successfully pushed to the file system, the HMI could be notified of the putfiles existence and update the display as needed.

If possible, I think this would be a very worthwhile addition to this proposal.

**Comment by mrapitis** [comment]
> One additional benefit not explicitly stated in the proposal is that an app could actually post load images. An RPC request like a show command could be sent with a reference to an image that would be loaded onto the file system later. After the image is successfully pushed to the file system, the HMI could be notified of the putfiles existence and update the display as needed.
If possible, I think this would be a very worthwhile addition to this proposal.
>

We will need to append one addition to this proposal to allow the putfile to notify the HMI as currently it is only notified for a 'systemFile'

https://github.com/smartdevicelink/sdl_core/blob/master/src/components/interfaces/HMI_API.xml#L2398-#L2401

**Comment by kshala-ford** [comment]
I fully support this proposal. Image post loading would be an excellent addition. It would be extremely helpful for choices and manual interactions.

**Comment by theresalech** [comment]
The Steering Committee has decided to extend this review, as they were not able to accept this proposal as written.  The Ford team will re-write this proposal to add clarity and address the concerns expressed in the issue comments and during the Steering Committee meeting.  The Steering Committee will vote on the revised proposal during the next meeting on April 4, 2017.

**Comment by theresalech** [comment]
The Steering Committee has agreed to accept this proposal.  They also recommended that an additional proposal be submitted for the additional post loading of content.

**Comment by theresalech** [comment]
Issue entered: [[SDL 0042] SDL must transfer RPC’s with invalid image reference parameters to the HMI](https://github.com/smartdevicelink/sdl_core/issues/1428)
