### ISSUE TITLE
[Accepted] SDL 0045 - External Policy Manager

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_evolution#134]
Hello SDL community,

The review of "External Policy Manager" begins now and runs through April 4, 2017. The proposal is available here:

https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0045-external-policy-manager.md

Reviews are an important part of the SDL evolution process. All reviews should be sent to the associated Github issue at:

https://github.com/smartdevicelink/sdl_evolution/issues/134

What goes into a review?

The goal of the review process is to improve the proposal under review through constructive criticism and, eventually, determine the direction of SDL. When writing your review, here are some questions you might want to answer in your review:

* Is the problem being addressed significant enough to warrant a change to SDL?
* Does this proposal fit well with the feel and direction of SDL?
* If you have used competitors with a similar feature, how do you feel that this proposal compares to those?
* How much effort did you put into your review? A glance, a quick reading, or an in-depth study?
Please state explicitly whether you believe that the proposal should be accepted into SDL.

More information about the SDL evolution process is available at

https://github.com/smartdevicelink/sdl_evolution/blob/master/process.md

Thank you,
Theresa Lech

Program Manager - Livio
theresa@livio.io

**Comment by joeljfischer** [comment]
* Is the problem being addressed significant enough to warrant a change to SDL?

Yes, although I'd like to see it expanded a little bit. It would be nice if this were paired with an example SDL Server implementation using an AES library to provide an example of encrypting / decrypting policy tables.

* Does this proposal fit well with the feel and direction of SDL?

Yes

* If you have used competitors with a similar feature, how do you feel that this proposal compares to those?

n/a

* How much effort did you put into your review? A glance, a quick reading, or an in-depth study?

A quick reading

* Please state explicitly whether you believe that the proposal should be accepted into SDL.

I believe this proposal should be accepted.

**Comment by theresalech** [comment]
This proposal has been accepted by the Steering Committee.  When this is implemented, it should include a clear description and background, and call out that it shouldn't be used in an embedded environment, but instead serve as a good reference for encrypting and decrypting a policy table when a policy update takes place.  The Steering Committee also supported submitting a separate proposal for a production-ready policy manager, which can be used by OEMs if they so choose.

**Comment by theresalech** [comment]
Issue Entered: [[SDL 0045] External Policy Manager](https://github.com/smartdevicelink/sdl_core/issues/1455)
