### ISSUE TITLE
[Accepted] SDL 0046 - Implement logger abstraction

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_evolution#141]
Hello SDL community,

The review of "Implement logger abstraction" begins now and runs through April 11, 2017. The proposal is available here:

https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0046-implement-logger-abstraction.md

Reviews are an important part of the SDL evolution process. All reviews should be sent to the associated Github issue at:

https://github.com/smartdevicelink/sdl_evolution/issues/141

What goes into a review?

The goal of the review process is to improve the proposal under review through constructive criticism and, eventually, determine the direction of SDL. When writing your review, here are some questions you might want to answer in your review:

* Is the problem being addressed significant enough to warrant a change to SDL?
* Does this proposal fit well with the feel and direction of SDL?
* If you have used competitors with a similar feature, how do you feel that this proposal compares to those?
* How much effort did you put into your review? A glance, a quick reading, or an in-depth study?
Please state explicitly whether you believe that the proposal should be accepted into SDL.

More information about the SDL evolution process is available at

https://github.com/smartdevicelink/sdl_evolution/blob/master/process.md

Thank you,
Theresa Lech

Program Manager - Livio
theresa@livio.io

**Comment by joeljfischer** [comment]
@AGaliuzov I assume that despite the abstraction, by default SDL will still log using Log4cxx unless whoever's using it writes an output class to use something else and compiles it that way?

**Comment by AGaliuzov** [comment]
@joeljfischer that is right. the main idea is to get rid of `4CXX` suffix from SDL logger. and provide the handy interface to the integrators. 
Regarding the default logger, we have couple ideas about another default logger for an SDL. But before creating proposal we have to measure their performance especially during active audio/video streaming

**Comment by joeljfischer** [comment]
> Is the problem being addressed significant enough to warrant a change to SDL?

Yes

> Does this proposal fit well with the feel and direction of SDL?

Yes

> If you have used competitors with a similar feature, how do you feel that this proposal compares to those?

n/a

> How much effort did you put into your review? A glance, a quick reading, or an in-depth study?
Please state explicitly whether you believe that the proposal should be accepted into SDL.

A moderate reading. I believe this proposal should be accepted.

**Comment by JackLivio** [comment]
I agree with Joel's review

**Comment by theresalech** [comment]
The Steering Committee fully agreed to accept this proposal.

**Comment by theresalech** [comment]
Issue entered: [[SDL 0046] Implement logger abstraction](https://github.com/smartdevicelink/sdl_core/issues/1480)
