### ISSUE TITLE
[Accepted] SDL 0049 - Gesture cancellation on video streaming

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_evolution#144]
Hello SDL community,

The review of "Gesture cancellation on video streaming" begins now and runs through April 11, 2017. The proposal is available here:

https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0049-touch-cancellation.md

Reviews are an important part of the SDL evolution process. All reviews should be sent to the associated Github issue at:

https://github.com/smartdevicelink/sdl_evolution/issues/144

What goes into a review?

The goal of the review process is to improve the proposal under review through constructive criticism and, eventually, determine the direction of SDL. When writing your review, here are some questions you might want to answer in your review:

* Is the problem being addressed significant enough to warrant a change to SDL?
* Does this proposal fit well with the feel and direction of SDL?
* If you have used competitors with a similar feature, how do you feel that this proposal compares to those?
* How much effort did you put into your review? A glance, a quick reading, or an in-depth study?
Please state explicitly whether you believe that the proposal should be accepted into SDL.

More information about the SDL evolution process is available at

https://github.com/smartdevicelink/sdl_evolution/blob/master/process.md

Thank you,
Theresa Lech

Program Manager - Livio
theresa@livio.io

**Comment by tpulatha** [comment]
What is the difference between `END` and the new proposed `CANCEL` touchevent type?
Wouldn't the HMI just send `END` if a current gesture gets interrupted?

**Comment by masatoogawa** [comment]
@tpulatha Thank you for your prompt review. `END` is the end of input by a user. `CANCEL` is an interruption of the input by system.

>  if the user is dragging..

For example, in the case of tap gestures, `END` may be a decision behavior.

1. A user taps on the screen. `BEGIN` is sent to an application.
2. A user keeps on tapping. A native dialog interrupts.
3. A user keeps on tapping. `END` is sent to an application.

An application may decide `END` which system send is a decision action even a user does not release his finger.

> "cancel" the drag (which would mean to move back to the start of the drag)

`CANCEL` expects not to rewind screenplay but to cancel gesture recognition.

**Comment by joeljfischer** [comment]
@tpulatha I think what they're trying to say, for example: the user is in the middle of a pinch gesture, a popup appears. If `END` is sent, the pinch will register, which is not intended. If `CANCEL` is sent, the pinch should be discarded.

The problem I see with this is that I'm not sure it's necessary. A pinch or drag generally occurs in real time, and simply using `END` seems appropriate. I'm not sure of what touch event use case would occur where a popup appearing would require a `CANCEL` and not simply an `END`. A long-press is the only one I can think of that might be relevant? It may be possible to get a short-press when a long was intended?

**Comment by masatoogawa** [comment]
For example, we have drag and drop in the user case.

Although they are edge cases, there are possibilities where `END` causes a decision action. We believe that introducing `CANCEL` is reasonable.

**Comment by theresalech** [comment]
The Steering Committee has agreed to accept this proposal, citing the drag and drop example as a valid use case.

**Comment by theresalech** [comment]
Issue entered: [[SDL 0049] Gesture cancellation on video streaming](https://github.com/smartdevicelink/sdl_core/issues/1481)
