### ISSUE TITLE
[Accepted] SDL 0051 - Enhance Video Streaming API's for Android

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_evolution#152]
Hello SDL community,

The review of "Enhance Video Streaming API's for Android" begins now and runs through April 18, 2017. The proposal is available here:

https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0051-enhance_video_streaming_apis_for_android.md

Reviews are an important part of the SDL evolution process. All reviews should be sent to the associated Github issue at:

https://github.com/smartdevicelink/sdl_evolution/issues/152

What goes into a review?

The goal of the review process is to improve the proposal under review through constructive criticism and, eventually, determine the direction of SDL. When writing your review, here are some questions you might want to answer in your review:

* Is the problem being addressed significant enough to warrant a change to SDL?
* Does this proposal fit well with the feel and direction of SDL?
* If you have used competitors with a similar feature, how do you feel that this proposal compares to those?
* How much effort did you put into your review? A glance, a quick reading, or an in-depth study?
Please state explicitly whether you believe that the proposal should be accepted into SDL.

More information about the SDL evolution process is available at

https://github.com/smartdevicelink/sdl_evolution/blob/master/process.md

Thank you,
Theresa Lech

Program Manager - Livio
theresa@livio.io

**Comment by mrapitis** [comment]
Providing this functionality will greatly enhance our current Android projected video streaming efforts from both usability and ease of use standpoints.  I can vouch for the technical feasibility of this PR as I have utilized the referenced presentation and virtual display encoder classes from an app perspective to create an h264 video stream.  

I believe this proposal should be accepted.

**Comment by theresalech** [comment]
The Steering Committee voted to accept this proposal, after discussing that a note clarifying API level should be included when this feature is released.  As the previous method for video streaming will still exist (not deprecated), it will be up to the developer if they want to support older versions of Android or use the enhanced API.  The Steering Committee will also need to clarify which version will be used for certification, or if all versions will need to be tested for certification purposes.

**Comment by theresalech** [comment]
Issue entered: [[SDL 0051] Enhance Video Streaming API's for Android](https://github.com/smartdevicelink/sdl_android/issues/469)
