### ISSUE TITLE
[Accepted] SDL 0055 - System Capabilities Query

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_evolution#166]
Hello SDL community,

The review of "System Capabilities Query" begins now and runs through May 2, 2017. The proposal is available here:

https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0055-system_capabilities_query.md

Reviews are an important part of the SDL evolution process. All reviews should be sent to the associated Github issue at:

https://github.com/smartdevicelink/sdl_evolution/issues/166

What goes into a review?

The goal of the review process is to improve the proposal under review through constructive criticism and, eventually, determine the direction of SDL. When writing your review, here are some questions you might want to answer in your review:

* Is the problem being addressed significant enough to warrant a change to SDL?
* Does this proposal fit well with the feel and direction of SDL?
* If you have used competitors with a similar feature, how do you feel that this proposal compares to those?
* How much effort did you put into your review? A glance, a quick reading, or an in-depth study?
Please state explicitly whether you believe that the proposal should be accepted into SDL.

More information about the SDL evolution process is available at

https://github.com/smartdevicelink/sdl_evolution/blob/master/process.md

Thank you,
Theresa Lech

Program Manager - Livio
theresa@livio.io

**Comment by joeljfischer** [comment]
> There are currently a lot of capabilities already implemented in the RAI response as params. We would have to either deprecate those, or duplicate functionality.

To be clear, is this what is proposed, or are we only adding new things to be handled by this flow. Also, are we considering adding parameters to binary service types?

**Comment by joeygrover** [comment]
Adding new capabilities this way. We will have to make a choice on the next Major version if we want to deprecate, but that would be a separate proposal. 

If you mean control packets, that is separate from this proposal. Adding params to the control packet will be for specific tasks like negotiating service details (eg MTU). This system is for providing developers with details on what the system supports purely for information. How that information is used is determined by that specific system capability. ie DialNumber information provided through this method will be used through the RPC service, but video streaming information can be used through the video streaming service.

**Comment by shoamano83** [comment]
Hi @joeygrover,

I guess we also need to update HMI_API (for example by adding `GetSystemCapability` RPC or extending `UI.GetCapabilities` response), is my understanding correct?

And by the way, in `GetSystemCapability` response,
```
<param name="info" type="String" maxlength="1000" mandatory="false">
```
Do we need `platform="documentation"` here? I don't know what it actually does but other "info" params have it.
Thanks.

**Comment by mfoedisch** [comment]
Would displayCapabilities and buttonCapabilities still be communicated the old way? They seem to be the ones of a larger size compared with the proposed ones.

**Comment by joeygrover** [comment]
@shoamano83 
I believe the HMI API would likely have to be updated as well. 
As far as the `platform="documentation"` I'm actually not sure. This is a good question. Looking at other entries, I'd guess it is also needed. 

@mfoedisch 
This proposal is simply to add new functionality to this RPC. Another proposal can be submitted with the idea of deprecating old params in the RAI and use the new system. There are no actual proposed new capabilities (beyond the existing entries in HMICapabilities), they were only used as  examples.

**Comment by tpulatha** [comment]
If we want to keep the `HMICapabilities` Struct then why don't we use it in the `SystemCapability` Struct? This seems to duplicate information?

**Comment by joeygrover** [comment]
It doesn't fit. 'HMICapabilities' only contains boolean of supported features. The 'SystemCapability'  is the actual details of a single capability

**Comment by theresalech** [comment]
There was much discussion over this proposal, and the Steering Committee ultimately agreed to accept.  They've also agreed that any desired changes to the implementation of this proposal can be addressed by members during the implementation.

**Comment by theresalech** [comment]
Issues Entered:
[Core](https://github.com/smartdevicelink/sdl_core/issues/1524)
[iOS](https://github.com/smartdevicelink/sdl_ios/issues/611)
[Android](https://github.com/smartdevicelink/sdl_android/issues/486)
