### ISSUE TITLE
[Accepted] SDL 0056 - Hardware Validator App (Android)

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_evolution#167]
Hello SDL community,

The review of "Hardware Validator App (Android)" begins now and runs through May 2, 2017. The proposal is available here:

https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0056-hardware-validator-app-android.md

Reviews are an important part of the SDL evolution process. All reviews should be sent to the associated Github issue at:

https://github.com/smartdevicelink/sdl_evolution/issues/167

What goes into a review?

The goal of the review process is to improve the proposal under review through constructive criticism and, eventually, determine the direction of SDL. When writing your review, here are some questions you might want to answer in your review:

* Is the problem being addressed significant enough to warrant a change to SDL?
* Does this proposal fit well with the feel and direction of SDL?
* If you have used competitors with a similar feature, how do you feel that this proposal compares to those?
* How much effort did you put into your review? A glance, a quick reading, or an in-depth study?
Please state explicitly whether you believe that the proposal should be accepted into SDL.

More information about the SDL evolution process is available at

https://github.com/smartdevicelink/sdl_evolution/blob/master/process.md

Thank you,
Theresa Lech

Program Manager - Livio
theresa@livio.io

**Comment by joeljfischer** [comment]
I'm always leery of taking on additional projects into the committee maintenance, as it increases the amount of work that must be done on any given release to ensure compatibility and updates. This does seem like a necessary step toward OEM validation however, so I reluctantly support this proposal.

**Comment by theresalech** [comment]
The Steering Committee feels that this app will serve as a good tool when working towards SDL certification for head units and therefore have accepted this proposal.  They stressed that the app will need to be released with details that differentiate it from other test tools (RPCBuilder, Relay app, etc.).  They also agreed that if we find testing tools are becoming too similar, a proposal can be submitted to consolidate applicable tools.  Lastly, there was discussion regarding an additional tool for iOS - perhaps a baseline iOS test app - and agreed that a separate proposal can be submitted for such if desired.

**Comment by theresalech** [comment]
Issue entered: [[SDL 0056] Hardware Validator App (Android)](https://github.com/smartdevicelink/hardwarevalidator_android/issues/1)
