### ISSUE TITLE
[Accepted with Revisions] SDL 0058 - Add video streaming capabilities

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_evolution#176]
Hello SDL community,

The review of the revised proposal "SDL 0058 - Add video streaming capabilities" begins now and runs through May 30, 2017. The original review of "Add video streaming capabilities" occurred May 9 through May 16, 2017. The proposal is available here:

https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0058-video-streaming-capabilities.md

Reviews are an important part of the SDL evolution process. All reviews should be sent to the associated Github issue at:

https://github.com/smartdevicelink/sdl_evolution/issues/176

What goes into a review?

The goal of the review process is to improve the proposal under review through constructive criticism and, eventually, determine the direction of SDL. When writing your review, here are some questions you might want to answer in your review:

* Is the problem being addressed significant enough to warrant a change to SDL?
* Does this proposal fit well with the feel and direction of SDL?
* If you have used competitors with a similar feature, how do you feel that this proposal compares to those?
* How much effort did you put into your review? A glance, a quick reading, or an in-depth study?
Please state explicitly whether you believe that the proposal should be accepted into SDL.

More information about the SDL evolution process is available at

https://github.com/smartdevicelink/sdl_evolution/blob/master/process.md

Thank you,
Theresa Lech

Program Manager - Livio
theresa@livio.io

**Comment by joeygrover** [comment]
As it stands, I believe this proposal is a little incomplete. It is better to encompass every change needed to contain this feature, than to leave anything under assumption. I have included changes to functionality and structure of the proposed solution as well as the necessary changes for completeness. There still needs to be additions to this proposal to describe different encoding settings possible with the different formats (See `VideoStreamingContainer`) as I am not an expert in this area.

## Modified existing RPCS 
Based on #166 

```xml
<struct name="HMICapabilities">
    <param name="navigation" type="Boolean" mandatory="false">
        <description>Availability of build in Nav. True: Available, False: Not Available</description>
    </param>
    <param name="phoneCall" type="Boolean" mandatory="false">
        <description>Availability of build in phone. True: Available, False: Not Available </description>
    </param>
    <param name="videoStreaming" type="Boolean" mandatory="false">
        <description>Availability of video streaming. </description>
    </param>
</struct>

<struct name="SystemCapability">
    <description>The systemCapabilityType indicates which type of data should be changed and identifies which data object exists in this struct. For example, if the SystemCapability Type is NAVIGATION then a "navigationCapability" should exist</description>
    <param name="systemCapabilityType" type="SystemCapabilityType" mandatory="true">
    </param>
    <param name="videoStreamingCapability" type="VideoStreamingCapability" mandatory="false">
    </param>

</struct>

<enum name="SystemCapabilityType">
    <element name="VIDEO_STREAMING"/>
</enum>

```

## New additions and better scope

```xml
<struct name="VideoStreamingCapability">
    <description>Contains information about this system's' video streaming capabilities.</description>
    <param name="preferredResolution" type="ImageResolution" mandatory="false">
        <description>The preferred resolution of a video stream for decoding and rendering on HMI.</description>
    </param>
    <param name="maxBitrate" type="Integer" minvalue="0" maxvalue="2147483647" mandatory="false">
        <description>The maximum bitrate of video stream that is supported, in kbps.</description>
    </param>
    <param name="supportedContainers" type="VideoStreamingContainer"  array="true" mandatory = "false">
        <description>Detailed information on each container supported by this system. Each object will contain a VideoStreamingContainerType that describes what can be expected. </description>
    </param>
</struct>

<struct name="VideoStreamingContainer">
    <description>Video streaming containers and their specifications. The containerType will define what other parameters are available. For example, if containerType was H264_RAW, H264_RTP, VP8_WEBM, VP9_WEBM, then the param maxProfile would be available. However, if the containerType was OGG_THEORA it would not. </description>
    <param name="containerType" type="VideoStreamingContainerType" mandatory="true">
        <description>Container type</description>
    </param>
    <param name="maxProfile" type="String" minlength="1" maxlength="250" mandatory="false">
        <description>Used with: H264_RAW, H264_RTP, VP8_WEBM, VP9_WEBM. If container is for H.264 (H264_RAW, H264_RTP), the highest H.264 profile that is supported. Examples: "1b", "3", "4.2". If used with VP8/9 (VP8_WEBM, VP9_WEBM), the highest of the corresponding format. Examples: "1", "3.1", "6.2"</description>
    </param>
</struct>


<enum name="VideoStreamingContainerType">
    <description>Enum  for each type of video streaming container</description>
    <element name="H264_RAW">
        <description>Raw h.264 stream that contains no timestamp data and is the lowest supported video streaming</description>
    </element>
    <element name="H264_RTP">
        <description>Container for H264, follows RFC 6184. RTP facilitates the transfer of real-time data. Information provided by this protocol include timestamps (for synchronization), sequence numbers (for packet loss and reordering detection) and the payload format which indicates the encoded format of the data.</description>
    </element>
    <element name="OGG_THEORA">
        <description>Container for OGG</description>
    </element>
    <element name="VP8_WEBM">
        <description>Container for VP8</description>
    </element>
    <element name="VP9_WEBM">
        <description>Container for VP9</description>
    </element>
</enum>
```

**Comment by shoamano83** [comment]
Hi @joeygrover, thank you very much for your comment.
OK, I agree that the proposal should include definitions of HMICapabilities, SystemCapability and SystemCapabilityType for completeness. I will update it.

Regarding your "New additions and better scope" I have a few comments and concerns.
(1) The New formats. Right now I don't have a plan to implement additional Theora, VP8 and VP9 formats. Will the proposal still be accepted without implementation plan?
I personally prefer to concentrate on adding RTP format in this proposal, i.e. if somebody wants to add Theora/VP8/VP9 then s/he can create another proposal for them. Of course, if everyone agrees then I can leave these new formats in the definition.

(2) Regarding maxProfile. It looks a bit complicated that the param means different thing for different formats, and is not used for particular format (Theora). Although I can live with your approach, I still prefer adding separate params like "maxH264Profile", "maxVP8Profile", "maxVP9Profile" into VideoStreamingCapability struct. They will increase the struct's size but should look cleaner.

(3) Definitions of the format. Actually I prefer using a string value rather than enum to define the formats. The downside of defining as enum is that when we add a new format, we need to update RPC, thus we need to create SDL core release for it. So it will take some time. If we define the format as a string, we are free from SDL core updates and releases.
In #143 I proposed "video/x-h264,stream-format=byte-stream" for ordinal H.264 stream and "application/x-rtp-stream,media=video,encoding-name=h264" for RTP format. If we are to add theora, VP8 and VP9, I can add "video/ogg,encoding-name=theora", "video/webm,encoding-name=vp8" and "video/webm,encoding-name=vp9".

Thanks.

**Comment by joeljfischer** [comment]
> (3) Definitions of the format. Actually I prefer using a string value rather than enum to define the formats. The downside of defining as enum is that when we add a new format, we need to update RPC, thus we need to create SDL core release for it. So it will take some time. If we define the format as a string, we are free from SDL core updates and releases.
In #143 I proposed "video/x-h264,stream-format=byte-stream" for ordinal H.264 stream and "application/x-rtp-stream,media=video,encoding-name=h264" for RTP format. If we are to add theora, VP8 and VP9, I can add "video/ogg,encoding-name=theora", "video/webm,encoding-name=vp8" and "video/webm,encoding-name=vp9"

I don't see how we are free from SDL releases. We have to have an SDL release (on both mobile and Core) to support a new language, why would we not simply add the enum at that time? I think an enum is the right way to go here.

**Comment by joeygrover** [comment]
1. I needed the formats to explain the entire flow. I am not saying we need/should implement each one of those. They were simply open-source formats that could theoretically be implemented. If we go the enum route, however, I think it's best to add as many as possible now so we can correctly scope the `VideoStreamingContainer` struct.
2. Yes I agree. I was torn here. I like reusing params when possible and the maxLevel (you're right it should be level) seems to be a common param with different video formats. See [h264](https://en.wikipedia.org/wiki/H.264/MPEG-4_AVC#Levels) and [VP9](https://en.wikipedia.org/wiki/VP9#Levels). It comes down to if we would rather have a little confusion on params with a need for clear documentation or let the struct grow in size. My vote is the former. We can always write code APIs around this knowledge so that developers use methods like `getMaxH264Level` that actually just gets the param maxLevel.
3. As @joeljfischer stated just making it a string does not prevent a need for a release. It might circumvent it on Core, however, each of the proxies would need a release to know what this new string was and how to use it. Thus, we would have to standardized and agree to each new format being accepted. So if we already have to agree on new formats and know how to handle them, and enum makes more sense. This also increases our ability to test code. Any parameter that is a free form string is difficult to test thoroughly, but testing a param that is expecting an enum is simply.

**Comment by shoamano83** [comment]
Thanks @joeljfischer, @joeygrover,

1. I understand and agree.
2. I understand, and both looks fine to me.
3. I meant SDL core release. If we define as enum, we need to update xml files when we add a new format in future. This requires update of Proxy, Core and HMI and particularly we need to wait for a new release of SDL core to enable the new format. This is my concern.
I understand that we need to standardize the new format. My idea is to put the explanation of each format in <description> field (just as I did in my proposal). So when we add a new format, eventually we need to create a new proposal and everybody will be notified.

**Comment by joeljfischer** [comment]
Regarding (3), I can't imagine a situation in which someone wishes to release a head unit with a new video format that can't notify the steering committee at most 6 months ahead of time to get that into an SDL Core release. Proxy releases are every 3 months, so at most you're gaining 3 months (and remember that mobile devs need time to update too).

**Comment by theresalech** [comment]
After much discussion about this proposal, it was decided that a workshop will be hosted for Steering Committee members to allow for more time to discuss and collaborate.  This proposal will be deferred until the workshop has taken place and the Steering Committee has come to an agreement on proposal revisions.

**Comment by joeygrover** [comment]
Based on comments during  the 5/18/2017 workshop here is an updated xml sheet for new RPCs.

## Modified existing RPCS

```xml
<struct name="HMICapabilities">
    <param name="navigation" type="Boolean" mandatory="false">
        <description>Availability of build in Nav. True: Available, False: Not Available</description>
    </param>
    <param name="phoneCall" type="Boolean" mandatory="false">
        <description>Availability of build in phone. True: Available, False: Not Available </description>
    </param>
    <param name="videoStreaming" type="Boolean" mandatory="false">
        <description>Availability of video streaming. </description>
    </param>
</struct>

<struct name="SystemCapability">
    <description>The systemCapabilityType indicates which type of data should be changed and identifies which data object exists in this struct. For example, if the SystemCapability Type is NAVIGATION then a "navigationCapability" should exist</description>
    <param name="systemCapabilityType" type="SystemCapabilityType" mandatory="true">
    </param>
    <param name="videoStreamingCapability" type="VideoStreamingCapability" mandatory="false">
    </param>

</struct>

<enum name="SystemCapabilityType">
    <element name="VIDEO_STREAMING"/>
</enum>
```

## New additions and better scope

```xml
<struct name="VideoStreamingCapability">
    <description>Contains information about this system's' video streaming capabilities.</description>
    <param name="preferredResolution" type="ImageResolution" mandatory="false">
        <description>The preferred resolution of a video stream for decoding and rendering on HMI.</description>
    </param>
    <param name="maxBitrate" type="Integer" minvalue="0" maxvalue="2147483647" mandatory="false">
        <description>The maximum bitrate of video stream that is supported, in kbps.</description>
    </param>
    <param name="supportedFormats" type="VideoStreamingFormat"  array="true" mandatory = "false">
        <description>Detailed information on each container supported by this system. Each object will contain a VideoStreamingContainerType that describes what can be expected. </description>
    </param>
</struct>

<struct name="VideoStreamingFormat">
    <description>Video streaming formats and their specifications. </description>
    <param name="protocol" type="VideoStreamingProtocol" mandatory="true">
        <description>Protocol type, see VideoStreamingProtocol</description>
    </param>
    <param name="codec" type="VideoStreamingCodec" mandatory="true">
        <description>Codec type, see VideoStreamingCodec</description>
    </param>
</struct>

<enum name="VideoStreamingProtocol">
    <description>Enum  for each type of video streaming protocol type.</description>
    <element name="RAW">
        <description>Raw stream bytes that contains no timestamp data and is the lowest supported video streaming</description>
    </element>
    <element name="RTP">
         <description>RTP facilitates the transfer of real-time data. Information provided by this protocol include timestamps (for synchronization), sequence numbers (for packet loss and reordering detection) and the payload format which indicates the encoded format of the data.</description>
    </element>
    <element name="RTSP">
        <description>The transmission of streaming data itself is not a task of RTSP. Most RTSP servers use the Real-time Transport Protocol (RTP) in conjunction with Real-time Control Protocol (RTCP) for media stream delivery. However, some vendors implement proprietary transport protocols. </description>
    </element>
    <element name="RTMP">
        <description> Real-Time Messaging Protocol (RTMP) was initially a proprietary protocol developed by Macromedia for streaming audio, video and data over the Internet, between a Flash player and a server. Macromedia is now owned by Adobe, which has released an incomplete version of the specification of the protocol for public use.</description>
    </element>
    <element name="WEBM">
        <description>The WebM container is based on a profile of Matroska.[2][4][5] WebM initially supported VP8 video and Vorbis audio streams. In 2013 it was updated to accommodate VP9 video and Opus audio.</description>
    </element>
</enum>

<enum name="VideoStreamingCodec">
    <description>Enum  for each type of video streaming codec.</description>
    <element name="H264">
        <description>A block-oriented motion-compensation-based video compression standard. As of 2014 it is one of the most commonly used formats for the recording, compression, and distribution of video content </description>
     </element>
    <element name="H265">
        <description>High Efficiency Video Coding (HEVC), also known as H.265 and MPEG-H Part 2, is a video compression standard, one of several potential successors to the widely used AVC (H.264 or MPEG-4 Part 10). In comparison to AVC, HEVC offers about double the data compression ratio at the same level of video quality, or substantially improved video quality at the same bit rate. It supports resolutions up to 8192×4320, including 8K UHD.</description>
     </element>
    <element name="Theora">
        <description>Theora is derived from the formerly proprietary VP3 codec, released into the public domain by On2 Technologies. It is broadly comparable in design and bitrate efficiency to MPEG-4 Part 2, early versions of Windows Media Video, and RealVideo while lacking some of the features present in some of these other codecs. It is comparable in open standards philosophy to the BBC's Dirac codec.</description>
    </element>
    <element name="VP8">
        <description>VP8 can be multiplexed into the Matroska-based container format WebM along with Vorbis and Opus audio. The image format WebP is based on VP8's intra-frame coding. VP8's direct successor, VP9, and the emerging royalty-free internet video format AV1 from the Alliance for Open Media (AOMedia) are based on VP8.</description>
    </element>
    <element name="VP9">
        <description>Similar to VP8, but VP9 is customized for video resolutions beyond high-definition video (UHD) and also enables lossless compression.</description>
    </element>
</enum>
```

**Comment by theresalech** [comment]
This proposal has been revised to include parameters that come from the head unit to inform the mobile library, and also an updated XML.  The Steering Committee will vote on this revised proposal during the May 30, 2017 meeting.

**Comment by joeljfischer** [comment]
Should this proposal mark which video containers and codecs are currently supported?

**Comment by theresalech** [comment]
The Steering Committee has decided to accept this proposal with revisions.  The Xevo team (@shoamano83 @jhludwig) will revise, based on the discussion in the Steering Committee meeting:
1) Codecs and streaming transports need information in their descriptions to let develops know which ones are currently supported and which ones aren’t. 2) Xevo will create first draft of the fallback streaming combination order.

**Comment by theresalech** [comment]
Proposal has been revised to incorporate the agreed upon changes:

Added a note that not all video formats are supported yet.
Added a suggested mechanism to pick a video format during video negotiation, including a fall back flow.

**Comment by theresalech** [comment]
Issues Entered:
[Android](https://github.com/smartdevicelink/sdl_android/issues/535)
[iOS](https://github.com/smartdevicelink/sdl_ios/issues/628)
[Core](https://github.com/smartdevicelink/sdl_core/issues/1591)
[RPC](https://github.com/smartdevicelink/rpc_spec/issues/22)

**Comment by theresalech** [comment]
Revisions from Xevo team have been merged.  Details of revisions from @shoamano83:

>>>I've revised the proposal to align with SDL-0058. It is ready for merge.  
The change is to remove duplicate sections (video capabilities and format negotiation) from this proposal since they are now covered by SDL-0058. As a result, this proposal has impacts on iOS and Android proxies only. Please check the "Impacted Platforms" field.
