### ISSUE TITLE
[Accepted] SDL 0059 - Android RPC Refactor

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_evolution#177]
Hello SDL community,

The review of "Android RPC Refactor" begins now and runs through May 16, 2017. The proposal is available here:

https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0059-android_rpc_refactor.md

Reviews are an important part of the SDL evolution process. All reviews should be sent to the associated Github issue at:

https://github.com/smartdevicelink/sdl_evolution/issues/177

What goes into a review?

The goal of the review process is to improve the proposal under review through constructive criticism and, eventually, determine the direction of SDL. When writing your review, here are some questions you might want to answer in your review:

* Is the problem being addressed significant enough to warrant a change to SDL?
* Does this proposal fit well with the feel and direction of SDL?
* If you have used competitors with a similar feature, how do you feel that this proposal compares to those?
* How much effort did you put into your review? A glance, a quick reading, or an in-depth study?
Please state explicitly whether you believe that the proposal should be accepted into SDL.

More information about the SDL evolution process is available at

https://github.com/smartdevicelink/sdl_evolution/blob/master/process.md

Thank you,
Theresa Lech

Program Manager - Livio
theresa@livio.io

**Comment by joeljfischer** [comment]
I have a few questions/comments about this proposal:

1. Just to clarify, this is just to clean up the implementation of getter methods, and makes no public API changes, or is RPCMessage public and therefore these are minor level API changes?

2. We did something similar in the iOS library in [this pull request](https://github.com/smartdevicelink/sdl_ios/pull/494), and the [current version of this file](https://github.com/smartdevicelink/sdl_ios/blob/develop/SmartDeviceLink/NSMutableDictionary+Store.m). The main differences are that (1) we did it in a private file so no API changes were made, (2) everything is an object in obj-c dictionaries. Not sure if there's anything for you to draw upon from it.

**Comment by joeygrover** [comment]
This is to just move the base calls into the parent class. The public API would remain the same, however, the internals of those API methods would call the parent class's methods. It is just a minor API change.

**Comment by ISHIZAKI-MASASHI** [comment]
Hello,
Could you give me descriptions of _a certain class_, _Hashtable_, _List_ which are referred in **Generic Getter Methods** ?

**Comment by joeljfischer** [comment]
@ISHIZAKI-MASASHI 
https://developer.android.com/reference/java/util/List.html
https://developer.android.com/reference/java/util/Hashtable.html

**Comment by theresalech** [comment]
The Steering Committee has fully agreed to accept this proposal.

**Comment by theresalech** [comment]
Issue entered: [[SDL 0059] Android RPC Refactor](https://github.com/smartdevicelink/sdl_android/issues/513)
