### ISSUE TITLE
[Accepted] SDL 0062 - Template images

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_evolution#183]
Hello SDL community,

The review of "Template images" begins now and runs through May 23, 2017. The proposal is available here:

https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0062-template-images.md

Reviews are an important part of the SDL evolution process. All reviews should be sent to the associated Github issue at:

https://github.com/smartdevicelink/sdl_evolution/issues/183

What goes into a review?

The goal of the review process is to improve the proposal under review through constructive criticism and, eventually, determine the direction of SDL. When writing your review, here are some questions you might want to answer in your review:

* Is the problem being addressed significant enough to warrant a change to SDL?
* Does this proposal fit well with the feel and direction of SDL?
* If you have used competitors with a similar feature, how do you feel that this proposal compares to those?
* How much effort did you put into your review? A glance, a quick reading, or an in-depth study?
Please state explicitly whether you believe that the proposal should be accepted into SDL.

More information about the SDL evolution process is available at

https://github.com/smartdevicelink/sdl_evolution/blob/master/process.md

Thank you,
Theresa Lech

Program Manager - Livio
theresa@livio.io

**Comment by joeljfischer** [comment]
I assume that if the `isTemplate` parameter is not set, the default is `false`?

I support this proposal.

**Comment by brettywhite** [comment]
This sounds like a good idea. However a small formatting change I'd request. Instead of N/A in Downsides then later showing: "The big downside is that apps won't know when to use template rather than dynamic when it comes to backwards compatibility (e.g. SDL Core 4.1)." Put that in the downsides section so that it is highlighted.

**Comment by joeljfischer** [comment]
@brettywhite That's a downside to the alternative, not the main proposal.

**Comment by brettywhite** [comment]
Ahh, I've got a case of the Mondays. Thanks @joeljfischer

**Comment by joeljfischer** [comment]
Regarding this proposal, I also believe we may need to specify good error messages for when an image is marked as `TEMPLATE` but does not fit the requirements for a template image.

**Comment by theresalech** [comment]
The Steering Committee has agreed to accept this proposal, and also agreed that specific error messages should be defined in the implementation of template images.

**Comment by theresalech** [comment]
Issues Entered:
[Core](https://github.com/smartdevicelink/sdl_core/issues/1588)
[iOS](https://github.com/smartdevicelink/sdl_ios/issues/626)
[Android](https://github.com/smartdevicelink/sdl_android/issues/533)
