### ISSUE TITLE
[Accepted] SDL 0067 - Optimize Connection Wait Range

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_evolution#196]
Hello SDL community,

The review of "Optimize Connection Wait Range" begins now and runs through June 20, 2017. The proposal is available here:

https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0067-optimize-connection-wait-range.md

Reviews are an important part of the SDL evolution process. All reviews should be sent to the associated Github issue at:

https://github.com/smartdevicelink/sdl_evolution/issues/196

What goes into a review?

The goal of the review process is to improve the proposal under review through constructive criticism and, eventually, determine the direction of SDL. When writing your review, here are some questions you might want to answer in your review:

* Is the problem being addressed significant enough to warrant a change to SDL?
* Does this proposal fit well with the feel and direction of SDL?
* If you have used competitors with a similar feature, how do you feel that this proposal compares to those?
* How much effort did you put into your review? A glance, a quick reading, or an in-depth study?
Please state explicitly whether you believe that the proposal should be accepted into SDL.

More information about the SDL evolution process is available at

https://github.com/smartdevicelink/sdl_evolution/blob/master/process.md

Thank you,
Theresa Lech

Program Manager - Livio
theresa@livio.io

**Comment by Toyota-BSalahat** [comment]
Hi @tpulatha. I was curious if it would help the connection strategy to use beginBackgroundTask to ask iOS for more time before suspending the app during connection if we need it. This might further help premature suspension of the app when numbers on the higher end of the range are randomly selected. I found it suggested in the Apple documentation for the external accessory background mode.

https://developer.apple.com/library/content/documentation/iPhone/Conceptual/iPhoneOSProgrammingGuide/BackgroundExecution/BackgroundExecution.html

https://developer.apple.com/documentation/uikit/uiapplication/1623031-beginbackgroundtask

**Comment by tpulatha** [comment]
Hi @Toyota-BSalahat thanks for your comment. 
I agree there are things we can do to improve the retry strategy. 
We have a different long term strategy, tough. With iOS 10 we seem to have stable multisession capabilities in iOS. This means all Apps can use the same protocol string. In older versions, one App would close an already existing connection if it used the same string (As explained in the proposal). This is not the case anymore, so the long term strategy will be to move to multisession (proposal is upcoming).

This proposal is a Interim Containment Action. Intentionally not changing any logic to enable us to go fast and bring this into the 4.3.0 release (which is currently in Pre-Release).

**Comment by Toyota-BSalahat** [comment]
@tpulatha Thanks for the clarification. I believe you are correct about the multisession changes going forward.

However, I think that investigating use of the function I posted above could also be considered as part of a fast fix. It should simply allow us to ask for more execution time from the OS if the app hits the 10 second mark, and is still in the process of connection for some reason.

**Comment by tpulatha** [comment]
@Toyota-BSalahat To get the change into 4.3.0 we basically have to confirm on Tuesday and then execute the change right away. I feel any logic change would need too much testing.

**Comment by Toyota-BSalahat** [comment]
@tpulatha the changes I am proposing would roughly amount to this

```

@property (assign) UIBackgroundTaskIdentifier backgroundTaskId;

- (void)connect {
	self.backgroundTaskId = [[UIApplication sharedApplication] beginBackgroundTask(expirationHandler: ^{
		[[UIApplication sharedApplication] endBackgroundTask: self.backgroundTaskId];
	})]
    [self sdl_connect:nil];
}

- (void)sdl_connect:(EAAccessory *)accessory {
    if (!self.session && !self.sessionSetupInProgress) {
        self.sessionSetupInProgress = YES;
        [self sdl_establishSessionWithAccessory:accessory];
    } else if (self.session) {
        [SDLDebugTool logInfo:@"Session already established."];
    } else {
        [SDLDebugTool logInfo:@"Session setup already in progress."];
    }
	
	[[UIApplication sharedApplication] endBackgroundTask: self.backgroundTaskId];
}
```

However I am uncertain what risk this would introduce, or if the benefit would be worth it. It could potentially give us a buffer on the connection timeout though.

**Comment by Harshacharan** [comment]
@tpulatha Hello, we have the following queries with this proposal:
1. Could you explain the background on why sdl_core responds with a number only between 0..29?
_4.sdl_core responds with a number between **0..29**._

2. Could you explain why apps get disconnected when the random wait time is close to 0?
_This happens for some Apps more often than others. We were able to root cause this to Apps, which have a random wait time that is close to the edges. (**Close to 0** or close to 10)._

**Comment by theresalech** [comment]
The Steering Committee voted to accept this proposal, and also noted the code provided in Toyota-BSalahat's comment could be helpful to improve this functionality in the future.  The Ford team will be submitting a PR for this change, and the Steering Committee voted to include the change in the iOS 4.6.0 release (scheduled for June 30, 2017).  The Project Maintainer noted that it's best practice to perform a full test suite in this situation, but given the need for this proposal, its scope (changing two variables), and current timing, the Steering Committee voted to make an exception and forgo additional testing after including this PR.  They've agreed this should not become common practice for future releases.

**Comment by theresalech** [comment]
Issue Entered: [[SDL 0067] Optimize Connection Wait Range](https://github.com/smartdevicelink/sdl_ios/issues/632)
