### ISSUE TITLE
[In Review] SDL 0076 - Support for Additional Languages

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_evolution#220]
Hello SDL community,

The review of "Support for Additional Languages" begins now and runs through July 18, 2017. The proposal is available here:

https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0076-Support-For-Additional-Languages.md

Reviews are an important part of the SDL evolution process. All reviews should be sent to the associated Github issue at:

https://github.com/smartdevicelink/sdl_evolution/issues/220

What goes into a review?

The goal of the review process is to improve the proposal under review through constructive criticism and, eventually, determine the direction of SDL. When writing your review, here are some questions you might want to answer in your review:

* Is the problem being addressed significant enough to warrant a change to SDL?
* Does this proposal fit well with the feel and direction of SDL?
* If you have used competitors with a similar feature, how do you feel that this proposal compares to those?
* How much effort did you put into your review? A glance, a quick reading, or an in-depth study?
Please state explicitly whether you believe that the proposal should be accepted into SDL.

More information about the SDL evolution process is available at

https://github.com/smartdevicelink/sdl_evolution/blob/master/process.md

Thank you,
Theresa Lech

Program Manager - Livio
theresa@livio.io

**Comment by joeljfischer** [comment]
I don't think that this proposal should be accepted, but it's frankly ridiculous that @kshala-ford's SDL-0061 (issue #179) which was close to being accepted and needed a few revisions, has not been done in nearly 2 months. That proposal should be accepted in place of this one, once those revisions are made.

**Comment by Toyota-Sbetts** [comment]
@joeljfischer If #179 can be accepted in time for 4.4, I agree.  If this not possible, we should continue with this proposal.

**Comment by theresalech** [comment]
As #179 has not yet been revised, the Steering Committee has accepted this proposal so that these languages can be supported in the SDL Core 4.4.0 Release.

**Comment by theresalech** [comment]
Issues Entered:
[iOS](https://github.com/smartdevicelink/sdl_ios/issues/652)
[Core](https://github.com/smartdevicelink/sdl_core/issues/1672)
[Android](https://github.com/smartdevicelink/sdl_android/issues/561)
