### ISSUE TITLE
[Accepted] SDL 0079 - System Capability Manager

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_evolution#226]
Hello SDL community,

The review of "System Capability Manager" begins now and runs through July 25, 2017. The proposal is available here:

https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0079-system_capability_manager.md
Reviews are an important part of the SDL evolution process. All reviews should be sent to the associated Github issue at:

https://github.com/smartdevicelink/sdl_evolution/issues/226

What goes into a review?

The goal of the review process is to improve the proposal under review through constructive criticism and, eventually, determine the direction of SDL. When writing your review, here are some questions you might want to answer in your review:

* Is the problem being addressed significant enough to warrant a change to SDL?
* Does this proposal fit well with the feel and direction of SDL?
* If you have used competitors with a similar feature, how do you feel that this proposal compares to those?
* How much effort did you put into your review? A glance, a quick reading, or an in-depth study?
Please state explicitly whether you believe that the proposal should be accepted into SDL.

More information about the SDL evolution process is available at

https://github.com/smartdevicelink/sdl_evolution/blob/master/process.md

Thank you,
Theresa Lech

Program Manager - Livio
theresa@livio.io

**Comment by mrapitis** [comment]
If the head unit does not support the GetSystemCapability RPC, a generic error response will be triggered from sdl core.  Will this response also be propagated through the public void onError(String info) callback?  Will the string type provide sufficient info for each of the different types of errors that can occur?

**Comment by askirk** [comment]
Yes, that response could be propogated through the `onError()` callback. I think a string is sufficient , it could return messages like: "GENERIC_ERROR Response from Core", "Video Streaming Unsupported on Head Unit", "Invalid Capability Type Requested".

**Comment by theresalech** [comment]
The Steering Committee fully agreed to accept this proposal.

**Comment by theresalech** [comment]
Issue Entered: [[SDL 0079] System Capability Manager](https://github.com/smartdevicelink/sdl_android/issues/566)
