### ISSUE TITLE
[Accepted] SDL 0080 - Support for MultiSession protocol string

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_evolution#228]
Hello SDL community,

The review of "Support for MultiSession protocol string" begins now and runs through July 25, 2017. The proposal is available here:

https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0080-Support-for-MultiSession-protocol-string.md

Reviews are an important part of the SDL evolution process. All reviews should be sent to the associated Github issue at:

https://github.com/smartdevicelink/sdl_evolution/issues/228

What goes into a review?

The goal of the review process is to improve the proposal under review through constructive criticism and, eventually, determine the direction of SDL. When writing your review, here are some questions you might want to answer in your review:

* Is the problem being addressed significant enough to warrant a change to SDL?
* Does this proposal fit well with the feel and direction of SDL?
* If you have used competitors with a similar feature, how do you feel that this proposal compares to those?
* How much effort did you put into your review? A glance, a quick reading, or an in-depth study?
Please state explicitly whether you believe that the proposal should be accepted into SDL.

More information about the SDL evolution process is available at

https://github.com/smartdevicelink/sdl_evolution/blob/master/process.md

Thank you,
Theresa Lech

Program Manager - Livio
theresa@livio.io

**Comment by joeljfischer** [comment]
It's not made clear in this proposal, but this appears to only affect devices running iOS 9 and up based on the code provided?

I strongly support this proposal, as it is quite easy to support on the iOS proxy side and provides a manifestly more simple connection strategy than we currently have in place.

**Comment by robinmk** [comment]
@joeljfischer , Yes it will be for iOS 9 and up.

**Comment by theresalech** [comment]
The Steering Committee fully agreed to accept this proposal.

**Comment by theresalech** [comment]
Issues Entered:
[Core](https://github.com/smartdevicelink/sdl_core/issues/1683)
[iOS](https://github.com/smartdevicelink/sdl_ios/issues/662)

**Comment by theresalech** [comment]
Per discussion on https://github.com/smartdevicelink/sdl_core/issues/1683, Core should not be considered an impacted platform for this proposal.
