### ISSUE TITLE
[In Review] SDL 0075 Revisions - Add `hapticSpatialDataSupported` to `VideoStreamingCapability`

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_evolution#237]
Hello SDL community,

The review of "Add `hapticSpatialDataSupported` to `VideoStreamingCapability`" begins now and runs through August 8, 2017. This will be a review of proposed revisions to a previously accepted but not yet implemented proposal, [SDL 0075](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0075-HID-Support-Plug-in.md).  

The pull request outlining the revisions under review is available here:

https://github.com/smartdevicelink/sdl_evolution/pull/234

Reviews are an important part of the SDL evolution process. All reviews should be sent to the associated Github issue at:

https://github.com/smartdevicelink/sdl_evolution/issues/237

What goes into a review?

The goal of the review process is to improve the proposal under review through constructive criticism and, eventually, determine the direction of SDL. When writing your review, here are some questions you might want to answer in your review:

* Is the problem being addressed significant enough to warrant a change to SDL?
* Does this proposal fit well with the feel and direction of SDL?
* If you have used competitors with a similar feature, how do you feel that this proposal compares to those?
* How much effort did you put into your review? A glance, a quick reading, or an in-depth study?
Please state explicitly whether you believe that the proposal should be accepted into SDL.

More information about the SDL evolution process is available at

https://github.com/smartdevicelink/sdl_evolution/blob/master/process.md

Thank you,
Theresa Lech

Program Manager - Livio
theresa@livio.io

**Comment by joeljfischer** [comment]
I would suggest a default value given if the parameter is not provided, with the default being `false`.

**Comment by joeygrover** [comment]
The Steering Committee fully agreed to accept this proposal.

**Comment by joeygrover** [comment]
PR with revisions has been merged into proposal .md file.

Issues have been updated:
[Core](https://github.com/smartdevicelink/sdl_core/issues/1685)
[iOS](https://github.com/smartdevicelink/sdl_ios/issues/664)
[Android](https://github.com/smartdevicelink/sdl_android/issues/568)
[RPC](https://github.com/smartdevicelink/rpc_spec/issues/36)
