### ISSUE TITLE
[In Review] SDL 0073 Revisions - Change Struct and Enum names to Adding Metadata Types

### ISSUE THREAD

**Issue by joeygrover** [smartdevicelink/sdl_evolution#240]
Hello SDL community,

The review of "Change Struct and Enum names to Adding Metadata Types" begins now and runs through August 15, 2017. This will be a review of proposed revisions to a previously accepted but not yet implemented proposal, [SDL 0073](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0073-Adding-Metadata-Types.md).  

The pull request outlining the revisions under review is available here:

https://github.com/smartdevicelink/sdl_evolution/pull/239

Reviews are an important part of the SDL evolution process. All reviews should be sent to the associated Github issue at:

https://github.com/smartdevicelink/sdl_evolution/issues/240

What goes into a review?

The goal of the review process is to improve the proposal under review through constructive criticism and, eventually, determine the direction of SDL. When writing your review, here are some questions you might want to answer in your review:

* Is the problem being addressed significant enough to warrant a change to SDL?
* Does this proposal fit well with the feel and direction of SDL?
* If you have used competitors with a similar feature, how do you feel that this proposal compares to those?
* How much effort did you put into your review? A glance, a quick reading, or an in-depth study?
Please state explicitly whether you believe that the proposal should be accepted into SDL.

More information about the SDL evolution process is available at

https://github.com/smartdevicelink/sdl_evolution/blob/master/process.md

Thank you,
Theresa Lech

Program Manager - Livio
theresa@livio.io

**Comment by theresalech** [comment]
The Steering Committee voted to accept this proposal.  The reason a proposal was entered to make this change was because the feature being changed was worked on by multiple SDLC Members, and the author requesting the change wanted to make sure all members were aligned in the implementation.
