### ISSUE TITLE
[Rejected] SDL 0075 Revisions - Change Parameter Types in 0075 HID Support Plug in

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_evolution#246]
Hello SDL community,

The review of "Change Parameter Types in 0075 HID Support Plug in" begins now and runs through August 22, 2017. This will be a review of proposed revisions to a previously accepted but not yet implemented proposal, [SDL 0075](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0075-HID-Support-Plug-in.md).  

The pull request outlining the revisions under review is available here:

https://github.com/smartdevicelink/sdl_evolution/pull/241

Reviews are an important part of the SDL evolution process. All reviews should be sent to the associated Github issue at:

https://github.com/smartdevicelink/sdl_evolution/issues/246

What goes into a review?

The goal of the review process is to improve the proposal under review through constructive criticism and, eventually, determine the direction of SDL. When writing your review, here are some questions you might want to answer in your review:

* Is the problem being addressed significant enough to warrant a change to SDL?
* Does this proposal fit well with the feel and direction of SDL?
* If you have used competitors with a similar feature, how do you feel that this proposal compares to those?
* How much effort did you put into your review? A glance, a quick reading, or an in-depth study?
Please state explicitly whether you believe that the proposal should be accepted into SDL.

More information about the SDL evolution process is available at

https://github.com/smartdevicelink/sdl_evolution/blob/master/process.md

Thank you,
Theresa Lech

Program Manager - Livio
theresa@livio.io

**Comment by joeljfischer** [comment]
This is a difficult change to decide, here are a few pieces of background information:

1. The current SDL APIs related to the device coordinate system are integers. For example, [the `TouchCoord` struct](https://github.com/smartdevicelink/rpc_spec/blob/18966d58c725efab59978ce4d5199b820f2d275f/README.md#touchcoord).
2. iOS and Android view APIs use floating-point values.

The question is whether we want to stick with integers as we have in other places, or if we want to stick with the native APIs. I do not know if head unit view APIs tend toward integers or floats.

**Comment by joeygrover** [comment]
There are no other instances of floats in the RPC spec currently. I'm not sure if this was an initial design choice, but it's something we should take into account. Maybe Ford can weigh in here if they have any knowledge on the choice.

I do think floats would give better accuracy for drawing the selection rects on the head unit. That will be an important piece to ensuring the quality of the feature.

I would lean towards accepting this change for the sake of continuity with the rest of the RPC spec, but this is not a strong position. If we did agree on floats then I think the `TouchCoord` struct should be revised, possibly including a new param for the fraction part that the proxy could put together as a float, something like:

```xml
    <struct name="TouchCoord">
        <param name="x" type="Integer" mandatory="true" minvalue="0" maxvalue="10000">
            <description>The x coordinate of the touch.</description>
        </param>
        <param name="xFraction" type="Integer" mandatory="false" minvalue="0" maxvalue="10000">
            <description>The fraction of the x coordinate of the touch.</description>
        </param>
        <param name="y" type="Integer" mandatory="true" minvalue="0" maxvalue="10000">
            <description>The y coordinate of the touch.</description>
        </param>
        <param name="yFraction" type="Integer" mandatory="false" minvalue="0" maxvalue="10000">
            <description>The fraction of the y coordinate of the touch.</description>
        </param>
    </struct>
```

**Comment by tsuzuki-uie** [comment]
I apologize confused proposal.
Actually, our proposal was "Float" for supporting sub-pixel in layout information.
However, certainly, parameter of OnTouchEvent which includes pixel information as Integer.
So, I propose to change Float to Integer of spatial layout parameter.

Because of 
 - modify OnTouchEvent may be impact to core/proxy schedule.
 - almost (or all) HU will not apply sub-pixel, so Integer is enough for spatial layout.

**Comment by Toyota-BSalahat** [comment]
As Joel and Joey pointed out, the native system tracks things in floats, and provides more precision than an integer value would.

I think there is something to be said for continuity with the other RPCs, but generally speaking with this kind of information I think it is better to have the precision, and choose not to use it on the HMI, than not have the precision at all. I think it would be reasonable to update the existing coordinate RPCs to reflect this as well, just for future proofing.

**Comment by theresalech** [comment]
The Steering Committee decided to reject this proposal, as they did not see a need to move from floats to integers in `SpacialStruct`.  When considering why floats hadn't been used in the past, the Ford team confirmed that there's no technical limitation in the spec as to why floats haven't been used in the past.  There was concern over how Core interprets floats, but it was determined there's nothing in Core that prevents the use in floats, although Core might drop precision.  For these reasons, it was determined that floats could be used in `SpatialStruct` and therefore this proposal should be rejected.
