### ISSUE TITLE
[Accepted] SDL 0082 - New vehicle data - EngineOilLife

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_evolution#247]
Hello SDL community,

The review of "New vehicle data - EngineOilLife" begins now and runs through August 22, 2017. The proposal is available here:

https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0082-New-vehicle-data-EngineOilLife.md

Reviews are an important part of the SDL evolution process. All reviews should be sent to the associated Github issue at:

https://github.com/smartdevicelink/sdl_evolution/issues/247

What goes into a review?

The goal of the review process is to improve the proposal under review through constructive criticism and, eventually, determine the direction of SDL. When writing your review, here are some questions you might want to answer in your review:

* Is the problem being addressed significant enough to warrant a change to SDL?
* Does this proposal fit well with the feel and direction of SDL?
* If you have used competitors with a similar feature, how do you feel that this proposal compares to those?
* How much effort did you put into your review? A glance, a quick reading, or an in-depth study?
Please state explicitly whether you believe that the proposal should be accepted into SDL.

More information about the SDL evolution process is available at

https://github.com/smartdevicelink/sdl_evolution/blob/master/process.md

Thank you,
Theresa Lech

Program Manager - Livio
theresa@livio.io

**Comment by stefanek22** [comment]
:+1:

**Comment by joeljfischer** [comment]
This appears to be an easy and quick change.

**Comment by theresalech** [comment]
When discussing this proposal, it was noted that members should ensure new parameters being added fit their design.  The Steering Committee then agreed to accept this proposal.

**Comment by theresalech** [comment]
Issues entered:
[Core](https://github.com/smartdevicelink/sdl_core/issues/1733)
[iOS](https://github.com/smartdevicelink/sdl_ios/issues/706)
[Android](https://github.com/smartdevicelink/sdl_android/issues/593)
[RPC](https://github.com/smartdevicelink/rpc_spec/issues/42)
