### ISSUE TITLE
[In Review] SDL 0083 - Expandable Design for Proprietary Data Exchange

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_evolution#249]
Hello SDL community,

The review of "Expandable Design for Proprietary Data Exchange" begins now and runs through August 22, 2017. The proposal is available here:

https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0083-Expandable-design-for-proprietary-data-exchange.md

Reviews are an important part of the SDL evolution process. All reviews should be sent to the associated Github issue at:

https://github.com/smartdevicelink/sdl_evolution/issues/249

What goes into a review?

The goal of the review process is to improve the proposal under review through constructive criticism and, eventually, determine the direction of SDL. When writing your review, here are some questions you might want to answer in your review:

* Is the problem being addressed significant enough to warrant a change to SDL?
* Does this proposal fit well with the feel and direction of SDL?
* If you have used competitors with a similar feature, how do you feel that this proposal compares to those?
* How much effort did you put into your review? A glance, a quick reading, or an in-depth study?
Please state explicitly whether you believe that the proposal should be accepted into SDL.

More information about the SDL evolution process is available at

https://github.com/smartdevicelink/sdl_evolution/blob/master/process.md

Thank you,
Theresa Lech

Program Manager - Livio
theresa@livio.io

**Comment by stefanek22** [comment]
:+1: This allows a proprietary data exchange for OEMs and their owners apps without triggering Policy Table updates.

**Comment by joeljfischer** [comment]
This seems to be a reasonable addition for OEM specific data exchange, and it is understood that something like this is needed. I believe this should be accepted.

**Comment by joeygrover** [comment]
I believe this to be a necessary feature moving forward. However, I'd like a little more detail if possible about what kind of data is assumed to be sent. Is this strictly for module data that owner apps will process? Or is there a possibility of sending over a json file that represents a custom, proprietary RPC message? If so, I think we should discuss the expected limitations of such an addition.

**Comment by robinmk** [comment]
The intention is purely for data exchanges between the owner app and the system and not for sending RPCs. The design does not propose a design for enforcement of the above.

**Comment by joeljfischer** [comment]
So, for clarity, although the proposal does say this, this is purely facilitating communication for: 
```
OEM head unit <- proprietary data -> OEM app 
```
Something else would have to be in place for OEM head unit to app proprietary RPC extensions. Assuming that's the case, having a way for OEM owned apps to communicate raw data seems reasonable. Extensions meant for wide-app use seem out of the question here.

**Comment by theresalech** [comment]
When discussing this proposal, there was an ask for an example of the data that would be exchanged.  Ford provided the example of an embedded navigation getting traffic information from a companion app.  The Steering Committee then voted to accept this proposal.

**Comment by theresalech** [comment]
Issues entered:
[Core](https://github.com/smartdevicelink/sdl_core/issues/1734)
[iOS](https://github.com/smartdevicelink/sdl_ios/issues/707)
[Android](https://github.com/smartdevicelink/sdl_android/issues/594)
[RPC](https://github.com/smartdevicelink/rpc_spec/issues/43)
