### ISSUE TITLE
[In Review] SDL 0010 - ButtonName Additions for Navigation Applications

### ISSUE THREAD

**Issue by joeljfischer** [smartdevicelink/sdl_evolution#27]
Hello SDL community,

The review of "ButtonName Additions for Navigation Applications" begins now and runs through September 6, 2016. The proposal is available here:

https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0010-spec-buttonname-additions-for-navigation-applications.md

Reviews are an important part of the SDL evolution process. All reviews should be sent to the associated Github issue at:

https://github.com/smartdevicelink/sdl_evolution/issues/27

What goes into a review?

The goal of the review process is to improve the proposal under review through constructive criticism and, eventually, determine the direction of SDL. When writing your review, here are some questions you might want to answer in your review:

* Is the problem being addressed significant enough to warrant a change to SDL?
* Does this proposal fit well with the feel and direction of SDL?
* If you have used competitors with a similar feature, how do you feel that this proposal compares to those?
* How much effort did you put into your review? A glance, a quick reading, or an in-depth study?
Please state explicitly whether you believe that the proposal should be accepted into SDL.

More information about the SDL evolution process is available at

https://github.com/smartdevicelink/sdl_evolution/blob/master/process.md

Thank you,
Joel Fischer

SDL iOS Maintainer - Livio
joel@livio.io

**Comment by joeljfischer** [comment]
> Is the problem being addressed significant enough to warrant a change to SDL?

* Yes, this problem seems to be a significant enough problem to warrant a change. Since we are now allowing navigation apps, we want to keep their capabilities with regard to buttons as generic as possible for OEMs to implement UIs that make sense for them.

> Does this proposal fit well with the feel and direction of SDL?

* Yes, this proposal fits well. However, my primary criticism is actually that I feel we may need a change in how "ButtonName" enums work. Since we have many enums, it may be difficult for a developer to know which one to use in which situations. I think it may be better if we were to clarify and separate these buttons into separate enums, such as MediaButtonName, NavigationButtonName, etc. This proposal could be shifted to add a new enum such as "NavigationButtonName"

* With how SDL currently works, this is a good fit, but I worry that we may be getting to large for one enum to handle it well.

* I think this largely covers navigation buttons that would be wise to have available for use on the navigation screen, and other features make more sense to be under the menu. The only other button I could think of was a button to view route steps.

> If you have used competitors with a similar feature, how do you feel that this proposal compares to those?

* It makes sense to give nav apps the same capabilities afforded to the built-in nav.

> How much effort did you put into your review? A glance, a quick reading, or an in-depth study? 
Please state explicitly whether you believe that the proposal should be accepted into SDL.

* I did a quick reading of this proposal, and I'm interested to hear whether or not others have additional button names or agree that this should be a new enum instead of adding to the existing one.

* If no additions or changes are desired, then this proposal should be accepted.

**Comment by asm09fsu** [comment]
@joeljfischer if we create a new enum, how would that impact the Subscribe Button RPC? That RPC is requiring a ButtonName enum value.

**Comment by joeljfischer** [comment]
This proposal has been rejected. The team does not see a strong need and this proposal is not quite sophisticated enough to handle problems such as location of the buttons overlaying over the video stream when developers do not know where the buttons will be.
