### ISSUE TITLE
[Accepted with Revisions] SDL 0090 - SDLHapticHitTester Protocol

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_evolution#270]
Hello SDL community,

The review of "SDLHapticHitTester Protocol" begins now and runs through September 5, 2017.  The proposal is available here:

https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0090-SDLHapticHitTesterProtocol.md

Reviews are an important part of the SDL evolution process. All reviews should be sent to the associated Github issue at:

https://github.com/smartdevicelink/sdl_evolution/issues/270

What goes into a review?

The goal of the review process is to improve the proposal under review through constructive criticism and, eventually, determine the direction of SDL. When writing your review, here are some questions you might want to answer in your review:

* Is the problem being addressed significant enough to warrant a change to SDL?
* Does this proposal fit well with the feel and direction of SDL?
* If you have used competitors with a similar feature, how do you feel that this proposal compares to those?
* How much effort did you put into your review? A glance, a quick reading, or an in-depth study?
Please state explicitly whether you believe that the proposal should be accepted into SDL.

More information about the SDL evolution process is available at

https://github.com/smartdevicelink/sdl_evolution/blob/master/process.md

Thank you,
Theresa Lech

Program Manager - Livio
theresa@livio.io

**Comment by joeljfischer** [comment]
I'm largely in agreement with this proposal. A minor tweak:

```objc
- (nullable UIView *)viewForSDLTouch:(SDLTouch *_Nonnull)touch;
```

I would propose removing the `SDL` part of the method name:

```objc
- (nullable UIView *)viewForTouch:(SDLTouch *_Nonnull)touch;
```

In your section "Out of Scope", you note that this doesn't change anything user facing, but I think we should make those determinations here, as they have to be made. I would also propose changes to the developer facing `SDLTouchManagerDelegate`:

```objc
NS_ASSUME_NONNULL_BEGIN

@protocol SDLTouchManagerDelegate <NSObject>

@optional
- (void)touchManager:(SDLTouchManager *)manager didReceiveSingleTapAtPoint:(CGPoint)point;
- (void)touchManager:(SDLTouchManager *)manager didReceiveDoubleTapAtPoint:(CGPoint)point;
- (void)touchManager:(SDLTouchManager *)manager panningDidStartAtPoint:(CGPoint)point;
- (void)touchManager:(SDLTouchManager *)manager didReceivePanningFromPoint:(CGPoint)fromPoint toPoint:(CGPoint)toPoint;
- (void)touchManager:(SDLTouchManager *)manager panningDidEndAtPoint:(CGPoint)point;
- (void)touchManager:(SDLTouchManager *)manager pinchDidStartAtCenterPoint:(CGPoint)point;
- (void)touchManager:(SDLTouchManager *)manager didReceivePinchAtCenterPoint:(CGPoint)point withScale:(CGFloat)scale;
- (void)touchManager:(SDLTouchManager *)manager pinchDidEndAtCenterPoint:(CGPoint)point;

@end

NS_ASSUME_NONNULL_END
```

and I would propose adding a `nullable` view to each of these methods.

**Comment by theresalech** [comment]
The Steering Committee has voted to accept this proposal with the revisions included in Joel Fischer’s comment.  It was noted that the functions included in the changes to the `SDLTouchManagerDelegate` already exist, so only the new parameter would need to be added.  Since this feature is planned to be included in the iOS 5.0 release, breaking changes could be included.

**Comment by theresalech** [comment]
@Toyota-BSalahat please advise when a new PR has been entered to update the proposal to reflect the agreed upon revisions. I'll then merge the PR so the proposal is up to date, and enter an issue in the iOS repository for implementation. Thanks!

**Comment by theresalech** [comment]
Proposal has been revised to include agreed upon changes and issue has been entered: [[SDL 0090] SDLHapticHitTester Protocol](https://github.com/smartdevicelink/sdl_ios/issues/728)
