### ISSUE TITLE
[Accepted] SDL 0094 - SDL Policy Server Enhancements - UI Framework

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_evolution#280]
Hello SDL community,

The review of "SDL Policy Server Enhancements - UI Framework" begins now and runs through September 12, 2017.  The proposal is available here:

https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0094-sdl-policy-server-ui.md

Reviews are an important part of the SDL evolution process. All reviews should be sent to the associated Github issue at:

https://github.com/smartdevicelink/sdl_evolution/issues/280

What goes into a review?

The goal of the review process is to improve the proposal under review through constructive criticism and, eventually, determine the direction of SDL. When writing your review, here are some questions you might want to answer in your review:

* Is the problem being addressed significant enough to warrant a change to SDL?
* Does this proposal fit well with the feel and direction of SDL?
* If you have used competitors with a similar feature, how do you feel that this proposal compares to those?
* How much effort did you put into your review? A glance, a quick reading, or an in-depth study?
Please state explicitly whether you believe that the proposal should be accepted into SDL.

More information about the SDL evolution process is available at

https://github.com/smartdevicelink/sdl_evolution/blob/master/process.md

Thank you,
Theresa Lech

Program Manager - Livio
theresa@livio.io

**Comment by Toyota-BSalahat** [comment]
@joeygrover 

> The main issue with Angular is the push to use TypeScript. While a developer can get around using TypeScript, all of the documentation uses TypeScript code. The options there are sticking with JavaScript and facing the consequences of translating TypeScript example code into JavaScript, or learning TypeScript on top of Angular for the policy server. For the sake of maintaining a small learning curve, these frameworks are not as recommended.

I just wanted to point out that generally type-safety does have the pro of making long term maintenance easier, and does reduce bug counts of a certain nature. I am not sure if that is worth the learning curve trade-off or not in this case, but I thought it is something that should be considered when evaluating Angular as an alternative.

**Comment by theresalech** [comment]
The Steering Committee voted to accept using Vue.JS, but still needs to decide on using JavaScript or TypeScript.  A few items to consider when making this decision should be how TypeScript works with JavaScript (JavaScript is used in the back end component of the Policy Server), and the scope/complexity of the Policy Server UI (whether the higher barrier to entry of TypeScript is worth the payoff of maintainability).  The Steering Committee will vote on JavaScript versus TypeScript during the 2017-09-19 meeting.

**Comment by joeljfischer** [comment]
I believe that JavaScript should be used over TypeScript. The team that is building this is more familiar with raw JavaScript than with TypeScript, and I think there is a strong benefit of having a unified codebase in both the backend and frontend of the policy server using the same language.

**Comment by Toyota-BSalahat** [comment]
@joeljfischer raises a valid point, however it is worth noting that Typescript has pretty solid interopability with Javascript. That is to say that any valid Javascript code is also valid Typescript code. This should make it pretty painless to start developing new code using Typescript, and update the existing codebase to utilize Typescript's type safety and other useful features as time moves forward.

As discussed during the previous SDLC meeting, Typescript does introduce several features that are useful if we are going to maintain this code base long term, with the intention that OEMs can use it out of the box. The most useful feature Typescript allows is "type safety". Having "type safety" in this code base will allow the codebase to be maintained and updated more easily/quicker, with much less risk of introducing regressions or other bugs.

The advantages of type safety can be seen in the fact that Apple moved to a type safe language with Swift, and Google is moving to support Kotlin. Generally speaking, I think it is in the project's advantage to utilize these advantages. 

I am also attaching some great articles that really go over the pros and cons of using Typescript.

https://vsavkin.com/writing-angular-2-in-typescript-1fa77c78d8e8

https://basarat.gitbooks.io/typescript/docs/types/migrating.html

https://scotch.io/tutorials/why-you-shouldnt-be-scared-of-typescript

https://medium.com/@auxx/typescript-pros-and-cons-873529634099

**Comment by joeygrover** [comment]
> That is to say that any valid Javascript code is also valid Typescript code.

It should be noted not all JavaScript libraries will automatically work with TypeScript projects. There might need to be a definition file added that provides the compiler with information on methods contained in the JavaScript library. However, in terms of our own code we can pretty much just rename the files from .js to .ts and it should be work which is great. This [SO post ](https://stackoverflow.com/questions/12694530/what-is-typescript-and-why-would-i-use-it-in-place-of-javascript/35048303#35048303)has a couple really great answers, mostly Lodewijk Bogaards's comment.

And because of the recommendation made during last week's call, and so we can properly assess all options ;). 
http://coffeescript.org/announcing-coffeescript-2/

**Comment by theresalech** [comment]
After further discussion about TypeScript and JavaScript, the Steering Committee voted to move forward with JavaScript, as outlined in the proposal.  It was determined that TypeScript will make the front end much more complex than it needs to be, given its current scope.  It was noted that TypeScript may be better suited for the Policy Server back end because of the larger amount of logic required, and if the SDLC would like to consider making this change, a separate proposal can be entered.

**Comment by theresalech** [comment]
Issue Entered: [[SDL 0094] SDL Policy Server Enhancements - UI Framework](https://github.com/smartdevicelink/sdl_server/issues/37)
