### ISSUE TITLE
[In Review] SDL 0097 - Tire pressure additions

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_evolution#288]
Hello SDL community,

The review of "Tire pressure additions" begins now and runs through September 19, 2017.  The proposal is available here:

https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0097-tire-pressure-additions.md

Reviews are an important part of the SDL evolution process. All reviews should be sent to the associated Github issue at:

https://github.com/smartdevicelink/sdl_evolution/issues/288

What goes into a review?

The goal of the review process is to improve the proposal under review through constructive criticism and, eventually, determine the direction of SDL. When writing your review, here are some questions you might want to answer in your review:

* Is the problem being addressed significant enough to warrant a change to SDL?
* Does this proposal fit well with the feel and direction of SDL?
* If you have used competitors with a similar feature, how do you feel that this proposal compares to those?
* How much effort did you put into your review? A glance, a quick reading, or an in-depth study?
Please state explicitly whether you believe that the proposal should be accepted into SDL.

More information about the SDL evolution process is available at

https://github.com/smartdevicelink/sdl_evolution/blob/master/process.md

Thank you,
Theresa Lech

Program Manager - Livio
theresa@livio.io

**Comment by JackLivio** [comment]
@kshala-ford You have tire pressure assumed to only be returned in kilo pascals. I am not sure if all OEM's use that unit of measurement, or if some might prefer to have the option to use PSI instead. 

Returning the associated unit of measurement with the measurement value might also be helpful for developers depending on the country they are from, especially if they are more familiar with standard units over the metric system.

**Comment by joeljfischer** [comment]
@JackLivio I think it's better for us to leave this complexity out of the spec and allow devs to do the conversions themselves. It's so easy for them to do that I don't think we need to handle that complexity.

**Comment by Toyota-Sbetts** [comment]
@joeljfischer This assumes all OEM systems return kilopascal, otherwise the HU will be converting the value so the app can convert it back.  While not necessarily difficult, it does seem redundant.

**Comment by joeljfischer** [comment]
@Toyota-Sbetts That kind of expansion is what I'm trying to avoid. I'd rather provide a single data point in a constant unit and allow developers to do those conversions as necessary, even if it means the HU needs to convert on its end. This may lead to a slight loss of precision, but I don't think that should be a large issue.

**Comment by JackLivio** [comment]
@joeljfischer @Toyota-Sbetts After looking at other vehicle data types in the mobile api, they all use the SI measurement system (odometer - km, externalTemperature - celsius, speed - km/h). Also Pascals is the SI unit of pressure.

I take back my original suggestion and agree with the original proposal. 

If we wanted to talk about converting between different units of pressure, then we  probably need to do the same for the other vehicle data units.

**Comment by theresalech** [comment]
After the discussion that took place on this issue, the Steering Committee voted to accept this proposal as is.

**Comment by theresalech** [comment]
Issues Entered:
[Core](https://github.com/smartdevicelink/sdl_core/issues/1766)
[iOS](https://github.com/smartdevicelink/sdl_ios/issues/748)
[Android](https://github.com/smartdevicelink/sdl_android/issues/613)
[RPC](https://github.com/smartdevicelink/rpc_spec/issues/48)
