### ISSUE TITLE
[Rejected] SDL 0001 - Secured Preferences

### ISSUE THREAD

**Issue by joeljfischer** [smartdevicelink/sdl_evolution#3]
Hello SDL community,

The review of "Secured Preferences" begins now and runs through August 10, 2016 (EDT). The proposal is available here:

> <https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0001-SecuredPreferences.md>

Reviews are an important part of the SDL evolution process. All reviews
should be sent to the associated Github issue at:

> <https://github.com/smartdevicelink/sdl_evolution/issues/3/>

##### What goes into a review?

The goal of the review process is to improve the proposal under review through constructive criticism and, eventually, determine the direction of SDL. When writing your review, here are some questions you might want to answer in your review:

* Is the problem being addressed significant enough to warrant a change to SDL?
* Does this proposal fit well with the feel and direction of SDL?
* If you have used competitors with a similar feature, how do you feel that this proposal compares to those?
* How much effort did you put into your review? A glance, a quick reading, or an in-depth study?

Please state explicitly whether you believe that the proposal should be accepted into SDL.

More information about the SDL evolution process is available at

> <https://github.com/smartdevicelink/sdl_evolution/blob/master/process.md>

Thank you,
Joel Fischer

SDL iOS Maintainer - Livio
joel@livio.io

**Comment by joeljfischer** [comment]
> Is the problem being addressed significant enough to warrant a change in SDL?

* The problem seems legitimate. If any random app can tamper with the routing services, they could tamper with data being passed by other apps. This effectively is SDL malware on Android devices, correct me if I'm wrong.

> Does the proposal fit well with the feel and direction of SDL?

* Here I must disagree. I don't believe that having an open source project be dependent on closed source projects, even freeware ones, is the right way to go. The point of open-source is that anyone can see and modify the code that we provide. Anyone could fork it and attempt to create a "better SDL", and if the project were ever abandoned, anyone could pick up where we left off. Restricting a part of SDL to only "maintainers" is inherently more nebulous than "open to all, free to all". I do not believe that requiring a dependency of this sort is in keeping with the open-source nature of SDL.

> If you have used competitors with a similar feature, how do you feel that this proposal compares to those?

* I am not aware of other libraries who do similar things

> How much effort did you put into your review? A glance, a quick reading, or an in-depth study?

* I did somewhere between a quick reading and an in-depth study. I asked questions to understand the reason behind the proposal, but I am not intimately familiar with Android development to know if there are secure alternatives that can leverage native libraries or open-source libraries.

I do not believe the proposal should be accepted into SDL.

**Comment by joeygrover** [comment]
Official resolution. We don't want to have a closed source library in the open source project to close one link in a chain that is inherently not secure at the moment. This proposal is not accepted into SDL.
