### ISSUE TITLE
[Accepted] SDL 0102 - New vehicle data - ElectronicParkBrakeStatus

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_evolution#303]
Hello SDL community,

The review of "New vehicle data - ElectronicParkBrakeStatus" begins now and runs through October 3, 2017.  The proposal is available here:

https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0102-New-vehicle-data-ElectronicParkBrakeStatus.md

Reviews are an important part of the SDL evolution process. All reviews should be sent to the associated Github issue at:

https://github.com/smartdevicelink/sdl_evolution/issues/303

What goes into a review?

The goal of the review process is to improve the proposal under review through constructive criticism and, eventually, determine the direction of SDL. When writing your review, here are some questions you might want to answer in your review:

* Is the problem being addressed significant enough to warrant a change to SDL?
* Does this proposal fit well with the feel and direction of SDL?
* If you have used competitors with a similar feature, how do you feel that this proposal compares to those?
* How much effort did you put into your review? A glance, a quick reading, or an in-depth study?
Please state explicitly whether you believe that the proposal should be accepted into SDL.

More information about the SDL evolution process is available at

https://github.com/smartdevicelink/sdl_evolution/blob/master/process.md

Thank you,
Theresa Lech

Program Manager - Livio
theresa@livio.io

**Comment by JackLivio** [comment]
Looks good to me. Only question I have for other OEM's is if they are ok with the following defined enums
```
<enum name="EletronicParkBrakeStatus">
  <element name="CLOSED" />
    <description>
      Park brake actuators have been fully applied.
    </description>		
    </element>
  <element name="TRANSITION">
    <description>
      Park brake actuators are transitioning to either Apply/Closed or Release/Open state.
    </description>
  </element>
  <element name="OPEN">
    <description>
      Park brake actuators are released.
    </description>		
  </element>
  <element name="DRIVE_ACTIVE">
    <description>
      When driver pulls the Electronic Park Brake switch while driving "at speed".
    </description>
  </element>
 <element name="FAULT">
    <description>
      When system has a fault or is under maintenance.
    </description>
 </element>
</enum>
```

**Comment by theresalech** [comment]
During the Steering Committee meeting on October 3 (2017-10-03), the Steering Committee voted to defer this proposal, keeping it in review until our next meeting on October 10, 2017. This will allow members additional time to confirm the enum definitions with their appropriate departments, as it will be important to ensure definitions work for all members and avoid changing them in the future.

**Comment by theresalech** [comment]
The Steering Committee fully agreed to accept this proposal and the enums defined in the [comment](https://github.com/smartdevicelink/sdl_evolution/issues/303#issuecomment-333927396) left by JackLivio on this review issue.

**Comment by theresalech** [comment]
Issues Entered:
[Core](https://github.com/smartdevicelink/sdl_core/issues/1815)
[iOS](https://github.com/smartdevicelink/sdl_ios/issues/761)
[Android](https://github.com/smartdevicelink/sdl_android/issues/632)
[RPC](https://github.com/smartdevicelink/rpc_spec/issues/51)
