### ISSUE TITLE
[In Review] SDL 0105 - Remote Control - Seat

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_evolution#314]
Hello SDL community,

The review of "Remote Control - Seat" begins now and runs through November 7, 2017.  The proposal is available here:

https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0105-remote-control-seat.md

Reviews are an important part of the SDL evolution process. All reviews should be sent to the associated Github issue at:

https://github.com/smartdevicelink/sdl_evolution/issues/314

What goes into a review?

The goal of the review process is to improve the proposal under review through constructive criticism and, eventually, determine the direction of SDL. When writing your review, here are some questions you might want to answer in your review:

* Is the problem being addressed significant enough to warrant a change to SDL?
* Does this proposal fit well with the feel and direction of SDL?
* If you have used competitors with a similar feature, how do you feel that this proposal compares to those?
* How much effort did you put into your review? A glance, a quick reading, or an in-depth study?
Please state explicitly whether you believe that the proposal should be accepted into SDL.

More information about the SDL evolution process is available at

https://github.com/smartdevicelink/sdl_evolution/blob/master/process.md

Thank you,
Theresa Lech

Program Manager - Livio
theresa@livio.io

**Comment by joeygrover** [comment]
What is the purpose of `heatingEnabled` and `coolingEnabled`? Would this not be implied by their respective level's being at either 0% or >0%?

I'm a little worried that the massage options are very OEM specific and I believe other SDLC members should really make sure those values work for them as well.

**Comment by theresalech** [comment]
The Steering Committee agreed to defer this proposal, keeping it in review until our next meeting on 2017-11-14, to allow members time to confirm values internally and ensure they'll work within their own implementations.

**Comment by theresalech** [comment]
The Steering Committee has agreed to accept this proposal.

**Comment by theresalech** [comment]
Issues Entered:
[Android](https://github.com/smartdevicelink/sdl_android/issues/651)
[Core](https://github.com/smartdevicelink/sdl_core/issues/1860)
[iOS](https://github.com/smartdevicelink/sdl_ios/issues/792)
[RPC](https://github.com/smartdevicelink/rpc_spec/issues/55)
