### ISSUE TITLE
[Accepted] SDL 0106 - Remote Control - OnRCStatus notification

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_evolution#315]
Hello SDL community,

The review of the revised proposal "SDL 0106 - Remote Control - OnRCStatus notification" begins now and runs through November 28, 2017.  The original review of "Remote Control - OnRCStatus notification" occurred October 31 through November 21, 2017.  The proposal is available here:

https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0106-remote-control-onRcStatus-notification.md

Reviews are an important part of the SDL evolution process. All reviews should be sent to the associated Github issue at:

https://github.com/smartdevicelink/sdl_evolution/issues/315

What goes into a review?

The goal of the review process is to improve the proposal under review through constructive criticism and, eventually, determine the direction of SDL. When writing your review, here are some questions you might want to answer in your review:

* Is the problem being addressed significant enough to warrant a change to SDL?
* Does this proposal fit well with the feel and direction of SDL?
* If you have used competitors with a similar feature, how do you feel that this proposal compares to those?
* How much effort did you put into your review? A glance, a quick reading, or an in-depth study?
Please state explicitly whether you believe that the proposal should be accepted into SDL.

More information about the SDL evolution process is available at

https://github.com/smartdevicelink/sdl_evolution/blob/master/process.md

Thank you,
Theresa Lech

Program Manager - Livio
theresa@livio.io

**Comment by JackLivio** [comment]
@yang1070 I think that the alternate approach proposed in the solution should also be considered for this proposal. 

If an app has a list of free modules via onRCStatus to reference, then it knows when a a resource is available. Then the app won't have to spam remote control requests until it receives a notification that it has been given access to a remote control module.

**Comment by joeygrover** [comment]
@yang1070 I see the notification returns a `moduleType` but this does not protect for the future when we hope to have more addressable modules. Unless we are saying that only one app can have access to a module type for all modules at a time, but I don't believe that is either correct or a necessary restrictions.  I would assume we could return a `module` instead.

**Comment by theresalech** [comment]
The Steering Committee voted to defer this proposal, keeping it in review until our next meeting on 2017-11-14, to allow the author time to respond to the questions included in the comments, and give members additional time to review.

**Comment by theresalech** [comment]
The Steering Committee voted to defer this proposal, keeping it in review until our next meeting on 2017-11-21, to allow the author time to respond to the questions in the comments.

**Comment by yang1070** [comment]
@joeygrover As I have pointed out in the proposal
```Since there is not currently agreement on the ID/ZONE scheme of the resources, we use ModuleType here. We shall use the id of a resource if we want to support multiple resources of the same type in the future. ```
Ideally, the notification shall return a list of allocated ```module```. However, in the remote control baseline, the assumption is one module per module type, there is no ```module``` defined. We can change it once we have an addressable ```module``` defined in the future.

**Comment by joeygrover** [comment]
Right but that makes a breaking change and that's what I would like to avoid. There is still a concept of module through `ModuleData` so that is what should be returned to protect for the future.

**Comment by yang1070** [comment]
@JackLivio That's a good question we have discussed inside Ford. The alternative approach adds a list of free modules in the same notification. Here are some reasons that we choose the current version. (1) adding free module list will change the notification from just sending to affected applications to sending all applications. That's more message traffic. (2) the remote control capabilities provides a list of module for control that app an query, so that the app knows the full list (3) even a module is not free, an application in foreground can still 'steal' the the module if the ```rcAccessMode``` configured as ```autoAllow``` or ```askDriver``` and driver allows it, which breaks the need for free module list.

But we are open to change. If most the committee members think adding the free module list is better, we will change the proposal to use the alternative version.

**Comment by yang1070** [comment]
@joeygrover Yes, change from ```ModuleType``` to some kind of ```ModuleId``` will be a breaking change. Unfortunately, untill we define the module id, module type is the best replacement for now. ```ModuleData``` itself cannot be used as module.
```xml
    <struct name="ModuleData">
        <description>The moduleType indicates which type of data should be changed and identifies which data object exists in this struct. For example, if the moduleType is CLIMATE then a "climateControlData" should exist</description>
        <param name="moduleType" type="ModuleType" mandatory="true">
        </param>
        <param name="radioControlData" type="RadioControlData" mandatory="false">
        </param>
        <param name="climateControlData" type="ClimateControlData" mandatory="false">
        </param>
    </struct>
```

**Comment by joeygrover** [comment]
It can be used. All the control data is optional so it doesn't have to be included, it contains the module type as needed in the original proposal, and it originally contained the zone of the module. It gives us what we need now and what we will need in the future without introducing a breaking change.

**Comment by yang1070** [comment]
@joeygrover  I get your point. It's a good suggestion. Will create a PR update the proposal.

**Comment by theresalech** [comment]
The Steering Committee voted to return this proposal for revisions.  The author of this proposal has already written a PR to incorporate the requested revisions left in the comments on this review issue: https://github.com/smartdevicelink/sdl_evolution/pull/349.

**Comment by theresalech** [comment]
The proposal has been revised to include requested changes, and the revised proposal has now moved into review. The Steering Committee will vote on this proposal during the November 28, 2017 (2017-11-28) meeting.

**Comment by JackLivio** [comment]
👍

**Comment by theresalech** [comment]
The Steering Committee fully agreed to accept this proposal.

**Comment by theresalech** [comment]
Issues Entered:
[Android](https://github.com/smartdevicelink/sdl_android/issues/657)
[Core](https://github.com/smartdevicelink/sdl_core/issues/1930)
[iOS](https://github.com/smartdevicelink/sdl_ios/issues/800)
[RPC](https://github.com/smartdevicelink/rpc_spec/issues/56)
