### ISSUE TITLE
[Accepted] SDL 0107 - New vehicle data - TurnSignal

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_evolution#328]
Hello SDL community,

The review of "New vehicle data - TurnSignal" begins now and runs through November 14, 2017.  The proposal is available here:

https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0107-New-vehicle-data-turnSignal.md

Reviews are an important part of the SDL evolution process. All reviews should be sent to the associated Github issue at:

https://github.com/smartdevicelink/sdl_evolution/issues/328

What goes into a review?

The goal of the review process is to improve the proposal under review through constructive criticism and, eventually, determine the direction of SDL. When writing your review, here are some questions you might want to answer in your review:

* Is the problem being addressed significant enough to warrant a change to SDL?
* Does this proposal fit well with the feel and direction of SDL?
* If you have used competitors with a similar feature, how do you feel that this proposal compares to those?
* How much effort did you put into your review? A glance, a quick reading, or an in-depth study?
Please state explicitly whether you believe that the proposal should be accepted into SDL.

More information about the SDL evolution process is available at

https://github.com/smartdevicelink/sdl_evolution/blob/master/process.md

Thank you,
Theresa Lech

Program Manager - Livio
theresa@livio.io

**Comment by JackLivio** [comment]
Instead of using the enum "BOTH", wouldn't naming it something like "HAZARDS" be more descriptive?

**Comment by joeljfischer** [comment]
@JackLivio It might be more semantic to what's happening, but I think it's less descriptive to name it hazards. I can't think of another case where both signals might be enabled, but I think most developers should be able to figure out that if both are on, it's likely a hazard situation. I'm fine with either option, but would lean toward the proposal's.

**Comment by theresalech** [comment]
The Steering Committee fully agreed to accept this proposal.

**Comment by theresalech** [comment]
Issues Entered:
[iOS](https://github.com/smartdevicelink/sdl_ios/issues/791)
[Android](https://github.com/smartdevicelink/sdl_android/issues/650)
[Core](https://github.com/smartdevicelink/sdl_core/issues/1859)
[RPC](https://github.com/smartdevicelink/rpc_spec/issues/54)
