### ISSUE TITLE
[Accepted] SDL 0108 - AutoCompleteList

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_evolution#331]
Hello SDL community,

The review of "AutoCompleteList" begins now and runs through November 14, 2017.  The proposal is available here:

https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0108-AutoCompleteList.md

Reviews are an important part of the SDL evolution process. All reviews should be sent to the associated Github issue at:

https://github.com/smartdevicelink/sdl_evolution/issues/331

What goes into a review?

The goal of the review process is to improve the proposal under review through constructive criticism and, eventually, determine the direction of SDL. When writing your review, here are some questions you might want to answer in your review:

* Is the problem being addressed significant enough to warrant a change to SDL?
* Does this proposal fit well with the feel and direction of SDL?
* If you have used competitors with a similar feature, how do you feel that this proposal compares to those?
* How much effort did you put into your review? A glance, a quick reading, or an in-depth study?
Please state explicitly whether you believe that the proposal should be accepted into SDL.

More information about the SDL evolution process is available at

https://github.com/smartdevicelink/sdl_evolution/blob/master/process.md

Thank you,
Theresa Lech

Program Manager - Livio
theresa@livio.io

**Comment by JackLivio** [comment]
How often would "SetGlobalProperties" be sent from the phone? Does core notify the phone after every keyboard press so the phone knows the context of how to generate the autoCompleteList sent in setGlobalProperties?

If that is not the case, then is size 100 of the array enough possible words to be useful?

**Comment by joeljfischer** [comment]
@JackLivio It would be sent after every keypress, and yes, Core notifies the phone with `OnKeyboardInput` after each keypress.

**Comment by theresalech** [comment]
The Steering Committee voted to accept this proposal.

**Comment by theresalech** [comment]
Issues Entered:
[Core](https://github.com/smartdevicelink/sdl_core/issues/1858)
[iOS](https://github.com/smartdevicelink/sdl_ios/issues/790)
[Android](https://github.com/smartdevicelink/sdl_android/issues/649)
[RPC](https://github.com/smartdevicelink/rpc_spec/issues/53)
