### ISSUE TITLE
[Accepted] SDL 0110 - Remove QT HMI from SDL Core

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_evolution#335]
Hello SDL community,

The review of "Remove QT HMI from SDL Core" begins now and runs through November 14, 2017.  The proposal is available here:

https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0110-remove-qt-hmi-from-sdl-core.md

Reviews are an important part of the SDL evolution process. All reviews should be sent to the associated Github issue at:

https://github.com/smartdevicelink/sdl_evolution/issues/335

What goes into a review?

The goal of the review process is to improve the proposal under review through constructive criticism and, eventually, determine the direction of SDL. When writing your review, here are some questions you might want to answer in your review:

* Is the problem being addressed significant enough to warrant a change to SDL?
* Does this proposal fit well with the feel and direction of SDL?
* If you have used competitors with a similar feature, how do you feel that this proposal compares to those?
* How much effort did you put into your review? A glance, a quick reading, or an in-depth study?
Please state explicitly whether you believe that the proposal should be accepted into SDL.

More information about the SDL evolution process is available at

https://github.com/smartdevicelink/sdl_evolution/blob/master/process.md

Thank you,
Theresa Lech

Program Manager - Livio
theresa@livio.io

**Comment by BrandonHe** [comment]
Hi @jacobkeeler 
We did receive several consultant about why component Qt_HMI in SDL_Core is not work. Thanks for your proposal. I read you also mentioned below in Potential Downside
>
>Several developers outside of the SDLC have stated that they wish to use the QT HMI, but are unable to because of it's outdated state. The argument for keeping this HMI is that it is far easier to integrate a QT-based HMI into an embedded system than a Web-based HMI. Removing this HMI might make the project less appealing to those looking to integrate SDL into their Head Unit.

Actually, we have maintained two locally QT HMI for a while. The second project encapsulated RPC json parsing and also realized a template manager.
[HMI_SDK](https://github.com/APCVSRepo/hmi_sdk)
[HMI_SDK_LIB](https://github.com/APCVSRepo/HMI_SDK_LIB)

Here are some examples for template _Media_ and _LARGE_GRAPHIC_WITH_SOFTBUTTONS_
![default](https://user-images.githubusercontent.com/13449160/32594995-15e42474-c569-11e7-91b5-3d7c06d593de.png)
![fm](https://user-images.githubusercontent.com/13449160/32595002-19ec0dde-c569-11e7-9ce1-8e3fc393db31.jpg)
![-](https://user-images.githubusercontent.com/13449160/32595008-1daa864e-c569-11e7-910f-22daf8b77e6a.png)
![-](https://user-images.githubusercontent.com/13449160/32595018-2343e578-c569-11e7-9360-59ccadf914b1.png)
![-](https://user-images.githubusercontent.com/13449160/32595032-2f9118e6-c569-11e7-9f32-c521e24488d7.png)

@theresalech @jacobkeeler 
Welcome your feedback and suggestions, we'd like to push it to global SmatDeviceLink to provide a Qt_HMI solution.

Thanks,

**Comment by jacobkeeler** [comment]
@BrandonHe This would make Alternative 1 much simpler, we could add this repository to the SmartDeviceLink group and offer it as a sample HMI.

Does this sample HMI still require the `dbus-1.7.8` 3rd-party library to be included in SDL Core? I believe that it would be very beneficial to be able to remove this library from the Core repository, as I know it has caused sizable issues in the past.

Ideally we want this HMI to act the same way as any of the other sample HMIs do, where they can be cloned and run separately, then connect.

**Comment by BrandonHe** [comment]
@jacobkeeler 

>
>This would make Alternative 1 much simpler, we could add this repository to the SmartDeviceLink group and offer it as a sample HMI.

This's also we want to see, we can setup  a meeting to discuss how-to and what your requirements.

>
>Does this sample HMI still require the dbus-1.7.8 3rd-party library to be included in SDL Core? I believe that it would be very beneficial to be able to remove this library from the Core repository, as I know it has caused sizable issues in the past.

No, we don't use dbus-1.7.8, but `JsonCpp-1.8.0` is still used.

>
>Ideally we want this HMI to act the same way as any of the other sample HMIs do, where they can be cloned and run separately, then connected.

You're right, this HMI can be cloned and run separately, and then connected with core to work together.

Thanks,

**Comment by JackLivio** [comment]
It is nice to see that there is a version of the QT HMI that is developed more than what is included in the core repository currently. This is still an open question to the consortium on whether or not this should continue to be supported.

Regardless, I believe the QT HMI should be removed from the core repository and moved to a different repository, or drop support all together depending on the consortiums decision. 

Things to consider:

 - If this QT HMI is to be used as a reference HMI for dev and testing, then it would be a redundant resource since we are currently developing the Generic HMI as the reference HMI for the SDL project. Unless it is preferred that we use a QT HMI instead as the reference hmi, then I suggest we do not continue to support the QT HMI for further development for this reason. 

 - The project maintainer does not have engineers who have development experience with QT.

 - Have any integrators that use a QT based environment used the existing QT HMI code in the sdl_core repository?

**Comment by joeljfischer** [comment]
@JackLivio One important note is that the Generic HMI we currently have is helpful for embedded developers using QT for their platform, but not as helpful as this would be.

With that said, I do not believe the SDLC should maintain a version of Generic HMI for every possible platform on the market (HTML5, QT, AGL, etc.). If QT is a large enough market that supporting this is what the SDLC wants to do, I will defer to the Core team on whether that is possible without additional support. Another note is the similarity of the HMI @BrandonHe proposed to a proprietary HMI.

I believe this proposal should be accepted, and the adding of a QT HMI outside of the SDL Core repository, as another HMI, considered separately.

**Comment by theresalech** [comment]
The Steering Committee voted to accept this proposal, thereby removing the QT HMI from SDL Core.  They agreed that if desired, a proposal can be entered to discuss adding a QT HMI outside of the SDL Core repository, as another HMI.

**Comment by theresalech** [comment]
Issue Entered: [[SDL 0110] Remove QT HMI from SDL Core](https://github.com/smartdevicelink/sdl_core/issues/1857)
