### ISSUE TITLE
[Accepted] SDL 0120 - GetSystemTime RPC

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_evolution#362]
Hello SDL community,

The review of "GetSystemTime RPC" begins now and runs through December 19, 2017.  The proposal is available here:

https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0120-GetSystemTime.md

Reviews are an important part of the SDL evolution process. All reviews should be sent to the associated Github issue at:

https://github.com/smartdevicelink/sdl_evolution/issues/362

What goes into a review?

The goal of the review process is to improve the proposal under review through constructive criticism and, eventually, determine the direction of SDL. When writing your review, here are some questions you might want to answer in your review:

* Is the problem being addressed significant enough to warrant a change to SDL?
* Does this proposal fit well with the feel and direction of SDL?
* If you have used competitors with a similar feature, how do you feel that this proposal compares to those?
* How much effort did you put into your review? A glance, a quick reading, or an in-depth study?
Please state explicitly whether you believe that the proposal should be accepted into SDL.

More information about the SDL evolution process is available at

https://github.com/smartdevicelink/sdl_evolution/blob/master/process.md

Thank you,
Theresa Lech

Program Manager - Livio
theresa@livio.io

**Comment by JackLivio** [comment]
[SDL core already has a time utility DateTime::getCurrentTime() that leverages <sys/time.h> gettimeofday()](https://github.com/smartdevicelink/sdl_core/blob/master/src/components/utils/src/date_time.cc#L43)

There are also instances of the cache manager and crypto manager getting time from the < ctime >  library via time() and localtime(). 

Here is the crypto manager's function that uses the time library to check time if update is needed. [CryptoManagerImpl::IsCertificateUpdateRequired()](https://github.com/smartdevicelink/sdl_core/blob/master/src/components/security_manager/src/crypto_manager_impl.cc#L266-L291). Is it a known issue that this function does not work properly?

Do we really need to introduce another source of time to Core?

Also this proposals describes a solution where time needs to be fetched from the HMI via an RPC message,  which will introduce lag so even that response's time parameter will be inaccurate?

**Comment by mrapitis** [comment]
@JackLivio  please find response below:

> 
> SDL core already has a time utility DateTime::getCurrentTime() that leverages <sys/time.h> gettimeofday()There are also instances of the cache manager and crypto manager getting time from the < ctime > library via time() and localtime().
>

True, the utility getCurrentTime method (and others) are used in various places within SDL core to calculate frequencies, perform logging, calculate differences, etc., however as you know the TLS handshake used by the security mechanism requires accurate system time which by default may not be provided by the system when using something like mktime inside of IsCertificateUpdateRequired.

> Here is the crypto manager's function that uses the time library to check time if update is needed. CryptoManagerImpl::IsCertificateUpdateRequired(). Is it a known issue that this function does not work properly?

Yes, some systems may not return an accurate time for this call.  In addition, some systems may actually allow this time to be configurable by the user -- again not providing an accurate value if the user has set the wrong date/time/timezone.

> Do we really need to introduce another source of time to Core?

Yes, providing the time information via the HMI RPC allows flexibility for the system integrator to supply an accurate system time based on their system implementation -- for example a system integrator could use the system GPS to supply an accurate time to SDL core from the HMI.

> Also this proposals describes a solution where time needs to be fetched from the HMI via an RPC message, which will introduce lag so even that response's time parameter will be inaccurate?

In our experience lag has not been an issue as the amount of time needed to transfer a message from the HMI to core is very small.

**Comment by jacobkeeler** [comment]
@mrapitis Is there any reason that the HMI would have more accurate time information than the system calls previously mentioned? Since they are normally on the same system, I would imagine that they would be able to get this value from the same place. Wouldn't that mean that the response from the HMI would be just as inaccurate as performing the equivalent system call?

**Comment by jacobkeeler** [comment]
Apologies, it appears I missed that part in your previous response: 
> Yes, providing the time information via the HMI RPC allows flexibility for the system integrator to supply an accurate system time based on their system implementation -- for example a system integrator could use the system GPS to supply an accurate time to SDL core from the HMI.

**Comment by JackLivio** [comment]
Ok thank you marcos for your response. Your explanations make sense. 

However why is the additional OnSystemTimeReady notification necessary?

**Comment by mrapitis** [comment]
@JackLivio 

> However why is the additional OnSystemTimeReady notification necessary?
This RPC is necessary to notify SDL core when system time is ready from the HMI.  In our example, we mentioned acquiring the system time from the GPS module, it can take some time for this to become available.

**Comment by theresalech** [comment]
Issues Entered:
[Core](https://github.com/smartdevicelink/sdl_core/issues/1963)
[RPC](https://github.com/smartdevicelink/rpc_spec/issues/60)
