### ISSUE TITLE
[Accepted with Revisions] SDL 0122 - Handling VR help requests when application does not send VR help prompt

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_evolution#364]
Hello SDL community,

The review of the revised proposal "SDL 0122 - Handling VR help requests when application does not send VR help prompt" begins now and runs through February 13, 2018. The original review of "Handling VR help requests when application does not send VR help prompt" occurred December 13 through December 19, 2017. The proposal is available here:

https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0122-New_rules_for_providing_VRHelpItems_VRHelpTitle.md

Reviews are an important part of the SDL evolution process. All reviews should be sent to the associated Github issue at:

https://github.com/smartdevicelink/sdl_evolution/issues/364

What goes into a review?

The goal of the review process is to improve the proposal under review through constructive criticism and, eventually, determine the direction of SDL. When writing your review, here are some questions you might want to answer in your review:

* Is the problem being addressed significant enough to warrant a change to SDL?
* Does this proposal fit well with the feel and direction of SDL?
* If you have used competitors with a similar feature, how do you feel that this proposal compares to those?
* How much effort did you put into your review? A glance, a quick reading, or an in-depth study?
Please state explicitly whether you believe that the proposal should be accepted into SDL.

More information about the SDL evolution process is available at

https://github.com/smartdevicelink/sdl_evolution/blob/master/process.md

Thank you,
Theresa Lech

Program Manager - Livio
theresa@livio.io

**Comment by JackLivio** [comment]
Overall I think this is a good way to handle sending VR.AddCommands as help prompts to the HMI in case an app does not send any help prompts via set global properties. The only thing I am a little concerned about is adding another timer to core with an arbitrary 10 second timeout.

When a VR add command gets sent from the phone, it should be immediately passed through to the HMI regardless. Since this proposal is a UI improvement and logic could be offloaded to the HMI side, wouldn't it be cleaner for the HMI to choose to use VR.AddCommands if a help prompt is triggered and no help prompts have been sent via setGlobalProperties?

**Comment by jacobkeeler** [comment]
My concerns mirror Jack's, I believe that this setup works well as far as defining a default help prompt, I just have an issue with the inclusion of an arbitrary timeout.

I believe that the better solution would where the HMI constructs this "default prompt" instead of Core. This "default prompt" could be constructed in the way described in this proposal, or in any other way that an OEM decides to implement. This functionality seems to be a bit outside the scope of SDL Core, and I don't believe any solution to this issue using just SDL Core would be very clean.

**Comment by robinmk** [comment]
@JackLivio 
@jacobkeeler 
1) Reg the timer - Under current design, the timer is chosen so that the number of messages b/w core and HMI is reduced. The value of 10 is somewhat arbitrary in that respect.

2)The design would ensure that HMI does not have to do anything specific to handle such cases as it would appear as though the apps sent these commands. The issue is caused due to apps not setting the corresponding parameters and I see value in SDL Core handling the design rather than every head unit having to implement it.

**Comment by theresalech** [comment]
The Steering Committee voted to return this proposal for revisions.  The proposal should be revised to include more implementation details, specifically those related to the timer.  The author can also work with the project maintainer offline to ensure the proposal contains enough information to allow for an informed Steering Committee vote.

**Comment by theresalech** [comment]
@GetmanetsIrina Do you have an update on these revisions?

**Comment by LuxoftAKutsan** [comment]
@theresalech 
Proposal modified with more implementation details and small fixes in summary part: 
https://github.com/smartdevicelink/sdl_evolution/pull/389

**Comment by theresalech** [comment]
The author has updated this proposal per the agreed upon revisions, and the revised proposal is now review ready.

**Comment by theresalech** [comment]
The revised proposal has now moved into review, and the Steering Committee will vote on this revised proposal during the 2018-02-13 meeting.

**Comment by joeljfischer** [comment]
I notice that the revised proposal still has the arbitrary 10 second timeout. Avoiding timers and invisible timeouts is definitely preferred, and even so, I don't think the "subjective analysis" that the user is unlikely to ask for help within 10 seconds of starting the application is correct. I would strongly prefer a more deterministic and non-timer based solution. It is noted that this was done to reduce the amount of requests sent between Core and HMI, is there an analysis of how many this is? I would think it better to send a few more requests when `AddCommands` / `DeleteCommands` come in (or a `SetGlobalProperties`) than to have what is likely to appear to the user as arbitrary behavior.

**Comment by JackLivio** [comment]
@joeljfischer As an alternate approach: Until a setGlobalProperties is received from the phone, Core will construct and send a new setGlobalProperties message to the hmi after each new addCommand received from the phone.  Then once a setGlobalProperties is received from the phone, Core will delete its internally created helpPromts lists and send the setGlobalProperties parameters from the phone to the hmi.

This would get rid of the need for an arbitrary timer and still be able to present the user some helpPrompt data almost right away after activating the app. The downside to this approach would be having potentially more messages sent to the hmi. If setGlobalProperties is never received from the phone, every add command from an app would generate a setGlobalProperties message with an updated helpPrompt list on top of the original addCommand. Also these messages might be completely unnecessary if a set global properties does eventually come.

To cutdown on the number of generated setGlobalProperty messages in the event of an app connecting with a lot of add commands, we could limit setGlobalProperties messages sent to the hmi to be created only from the first couple of addCommands until the actual setGlobalProperties message is received from the phone.

**Comment by robinmk** [comment]
@JackLivio , understood. My suggestion is to not put the limit.

**Comment by joeljfischer** [comment]
@JackLivio @robinmk I think the limit should be much higher than 5, but I think I can agree with that.

**Comment by theresalech** [comment]
The Steering Committee voted to defer this proposal, keeping it in review until our next meeting on 2018-02-20, to allow for more discussion on the review issue.  Specific items to discuss on the review issue include the limit on addComands (possibly increasing to 25 - 30) and the behavior of interaction choice sets within the proposal.

**Comment by robinmk** [comment]
Increasing the limit to 25-30 seems acceptable.

**Comment by joeljfischer** [comment]
@robinmk Do you have any additional information on how interaction choice sets may be handled. If the app performs a `CreateInteractionChoiceSet`, @JackLivio mentioned those are sent to the HMI as `addCommand`s. Would that throw cause those Choice Sets to be thrown into the VR help list? That would be less than ideal.

**Comment by robinmk** [comment]
Per the design, CreateInteractionChoiceSet should/would not trigger the SetGlobalProperties.
Even though from Core to HMI its via AddCommand, SDL will know not to apply the logic (proposed design) as the request from app to core is not an AddCommand.

**Comment by theresalech** [comment]
The Steering Committee has voted to accept this proposal with revisions.  The revision will be including a limit on `addCommand`s of 30.  It was also understood in the discussion that `CreateInteractionChoiceSet` should not trigger `SetGlobalProperties`.

**Comment by theresalech** [comment]
@GetmanetsIrina please advise when a new PR has been entered to update the proposal to reflect the agreed upon revisions. I'll then merge the PR so the proposal is up to date, and enter issues in the respective repositories for implementation. Thanks!

**Comment by theresalech** [comment]
Issues Entered:
[RPC](https://github.com/smartdevicelink/rpc_spec/issues/76)
[Core](https://github.com/smartdevicelink/sdl_core/issues/2154)
