### ISSUE TITLE
[Accepted with Revisions] SDL 0129 - Add Secondary AppHMIType Array iOS

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_evolution#375]
Hello SDL community,

The review of "Add Secondary AppHMIType Array iOS" begins now and runs through January 23, 2018.  The proposal is available here:

https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0129-ios-secondary-apptypes.md
Reviews are an important part of the SDL evolution process. All reviews should be sent to the associated Github issue at:

https://github.com/smartdevicelink/sdl_evolution/issues/375

What goes into a review?

The goal of the review process is to improve the proposal under review through constructive criticism and, eventually, determine the direction of SDL. When writing your review, here are some questions you might want to answer in your review:

* Is the problem being addressed significant enough to warrant a change to SDL?
* Does this proposal fit well with the feel and direction of SDL?
* If you have used competitors with a similar feature, how do you feel that this proposal compares to those?
* How much effort did you put into your review? A glance, a quick reading, or an in-depth study?
Please state explicitly whether you believe that the proposal should be accepted into SDL.

More information about the SDL evolution process is available at

https://github.com/smartdevicelink/sdl_evolution/blob/master/process.md

Thank you,
Theresa Lech

Program Manager - Livio
theresa@livio.io

**Comment by brettywhite** [comment]
Do you think the using language like `additionalHMITypes` is less confusing to a developer than `secondaryHMITypes`? To me, secondary makes it sound like they are different than the primary ones we are used to in SDL.

**Comment by tvkanters** [comment]
As mentioned in the potential downsides, this could be a rather confusing change. The naming also isn't very intuitive, and could be improved as mentioned above.
If we want to move forward to this, I'd suggest also including the alternative. I.e., in addition to adding the secondary types for a minor version upgrade, in the next major version we'd fix this properly by removing the existing `appType` and only using an array.

**Comment by joeljfischer** [comment]
I would be okay with `additionalHMITypes`. As far as in a future major version changing it to only be the array – I'm okay with that, though I think the one-and-then-others has the advantage of _maybe_ being clearer since most people only need one?

**Comment by theresalech** [comment]
The Steering Committee voted to accept this proposal with the following revision: update `secondaryHMITypes` to `additionalHMITypes`.  The Steering Committee also noted that removing the existing `appType` and only using an array would be a good change to include in the next iOS major version release.

**Comment by theresalech** [comment]
@joeljfischer please advise when a new PR has been entered to update the proposal to reflect the agreed upon revisions. I'll then merge the PR so the proposal is up to date, and enter an issue in the iOS repository for implementation. Thanks!

**Comment by theresalech** [comment]
PR has been merged and issue has been entered: [https://github.com/smartdevicelink/sdl_ios/issues/851](https://github.com/smartdevicelink/sdl_ios/issues/851)
