### ISSUE TITLE
[Rejected] SDL 0130 - SendLocation for Mobile Nav

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_evolution#376]
Hello SDL community,

The review of "SendLocation for Mobile Nav" begins now and runs through January 23, 2018.  The proposal is available here:

https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0130-SendLocation-for-Mobile-Nav.md

Reviews are an important part of the SDL evolution process. All reviews should be sent to the associated Github issue at:

https://github.com/smartdevicelink/sdl_evolution/issues/376

What goes into a review?

The goal of the review process is to improve the proposal under review through constructive criticism and, eventually, determine the direction of SDL. When writing your review, here are some questions you might want to answer in your review:

* Is the problem being addressed significant enough to warrant a change to SDL?
* Does this proposal fit well with the feel and direction of SDL?
* If you have used competitors with a similar feature, how do you feel that this proposal compares to those?
* How much effort did you put into your review? A glance, a quick reading, or an in-depth study?
Please state explicitly whether you believe that the proposal should be accepted into SDL.

More information about the SDL evolution process is available at

https://github.com/smartdevicelink/sdl_evolution/blob/master/process.md

Thank you,
Theresa Lech

Program Manager - Livio
theresa@livio.io

**Comment by brettywhite** [comment]
After taking a look at this I feel that it might be useful to apply this idea and traverse one more layer of abstraction before implementing it. 

To provide my thought process, this is essentially allowing inter-sdlapp-communication, but is tailored for navigation apps. I think it would be worth the discussion of allowing this functionality to be multi-purposed, ie. any sdl app could send information using this implementation to another sdl app. 

For example, a good one in my opinion, is iOS's implementation of custom URL schemes. link: [Apple Custom URL](https://developer.apple.com/library/content/documentation/iPhone/Conceptual/iPhoneOSProgrammingGuide/Inter-AppCommunication/Inter-AppCommunication.html)
This allows the app developer to create the parameters in which can be passed to them and the system then wakes the app, and passes in that URL, allowing it to be parsed and do whatever was intended. Other developers can then invoke external apps with an easy call. Even within the tone of navigation apps, a partner nav app may want more data than the `sendLocation` RPC can provide. This could be useful for nav and non-nav apps alike. 

Again, this is simply an idea and an example of a system that uses one of many ways of accomplishing this task.

**Comment by joeygrover** [comment]
It seems like this could be used beyond Navigation/SendLocation by virtue of extending SystemCapability. I think the solution works for the use case laid out, I would like to extrapolate this out for more use cases to ensure the solution works beyond this case. Maybe even extending SystemCapability to encompass what a few more of these services look like. For example, beyond just control of these functions what about the subscription to updates from the other apps? A media app sending song title updates and being able to pass that info to other connected apps for example.

I do like the idea that Core is the responsible module for routing messages to the appropriate service provider. I think that makes it easier on the app developers trying to use some of these features.

**Comment by kshala-ford** [comment]
You mean something similar to the SendURI #365 proposal but more generic? Apps could register custom schemes which can be used by other apps? I like the idea of providing IPC over SDL e.g. by using URI e.g. tell a media app to play a song or skip a song. This way apps could agree to an interface between each other. However `sendURL` is a very basic API without the capability of delivering results back to the sender. 

In the case of sending/redirecting locations for navigation we should reuse `SendLocation` as an RPC to provide information to the sender if the location was accepted, rejected or added to an existing route. Furthermore I don't believe `sendURL` on iOS is used for purposes like notify about waypoint changes to subscribed apps. We should reuse the existing waypoint RPCs and have Core accept waypoint changes and broadcast them to subscribed apps.

**Comment by theresalech** [comment]
During the discussion regarding this proposal, the Project Maintainer expressed concern with making sure that this is the right solution for all inter-app communication, and not only the specific SendLocation use case described.  They also advised that it would be important to understand how and where the logic described in this proposal (notably, how Core would check which application is currently selected) would be implemented within SDL Core.  The Project Maintainer then proposed an alternative solution, which could be applied to any RPCs/messages we want to send across, involving exposing SDL modules through the Remote Control feature.  The author agreed that this alternative should be considered as long as it also fulfills the basic use case this proposal is working to solve.  The Steering Committee then voted to defer this proposal and allow the Project Maintainer to submit an additional proposal with more details about the alternative solution.

**Comment by theresalech** [comment]
It was determined in the workshop that this proposal may be too specific, and a separate proposal should be entered describing a Pub/Sub Service Model with Custom URI Schemes. Additional details of the new proposal can be found in the workshop meeting minutes.

**Comment by theresalech** [comment]
The Steering Committee voted to reject this proposal in favor of [SDL 0167 - App Services](https://github.com/smartdevicelink/sdl_evolution/issues/485).
