### ISSUE TITLE
[Rejected] SDL 0143 - Add Service Discovery mechanism for TCP transport

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_evolution#407]
Hello SDL community,

The review of "Add Service Discovery mechanism for TCP transport'" begins now and runs through February 20, 2018.  The proposal is available here:

https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0143-mt-service-discovery.md

Reviews are an important part of the SDL evolution process. All reviews should be sent to the associated Github issue at:

https://github.com/smartdevicelink/sdl_evolution/issues/407

What goes into a review?

The goal of the review process is to improve the proposal under review through constructive criticism and, eventually, determine the direction of SDL. When writing your review, here are some questions you might want to answer in your review:

* Is the problem being addressed significant enough to warrant a change to SDL?
* Does this proposal fit well with the feel and direction of SDL?
* If you have used competitors with a similar feature, how do you feel that this proposal compares to those?
* How much effort did you put into your review? A glance, a quick reading, or an in-depth study?
Please state explicitly whether you believe that the proposal should be accepted into SDL.

More information about the SDL evolution process is available at

https://github.com/smartdevicelink/sdl_evolution/blob/master/process.md

Thank you,
Theresa Lech

Program Manager - Livio
theresa@livio.io

**Comment by joeljfischer** [comment]
Given [this comment on 0141](https://github.com/smartdevicelink/sdl_evolution/issues/405#issuecomment-366041405). I would prefer a solution that requires a connection over IAP (for iOS, perhaps Bluetooth / USB for Android) as the primary transport, and the Wi-Fi IP / Port given via the Start Service response. This proposal would then be unnecessary.

**Comment by shoamano83** [comment]
Thanks for your comment. As I mentioned in SDL 0141, this proposal was developed to support a use-case of Android SDL Proxy connecting solely with Wi-Fi (TCP) transport. In this use-case, Proxy cannot acquire IP address and port number through another transport.
So, if we give up with this use-case then this proposal may not be necessary.

**Comment by theresalech** [comment]
As the Steering Committee has decided on a different approach for the WiFi transport, described in the revisions to [SDL 0141](https://github.com/smartdevicelink/sdl_evolution/issues/405), this proposal is not currently necessary.  If a new proposal is entered in the future to enable WiFi as a primary transport, then the concept described in this proposal will be revisited.
