### ISSUE TITLE
[Accepted] SDL 0014 - Adding Audio File Playback to TTSChunk

### ISSUE THREAD

**Issue by joeljfischer** [smartdevicelink/sdl_evolution#42]
Hello SDL community,

The review of "Adding Audio File Playback to TTSChunk" begins now and runs through October 4, 2016. The proposal is available here:

https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0014-adding-audio-file-playback-to-ttschunk.md

Reviews are an important part of the SDL evolution process. All reviews should be sent to the associated Github issue at:

https://github.com/smartdevicelink/sdl_evolution/issues/42

What goes into a review?

The goal of the review process is to improve the proposal under review through constructive criticism and, eventually, determine the direction of SDL. When writing your review, here are some questions you might want to answer in your review:

* Is the problem being addressed significant enough to warrant a change to SDL?
* Does this proposal fit well with the feel and direction of SDL?
* If you have used competitors with a similar feature, how do you feel that this proposal compares to those?
* How much effort did you put into your review? A glance, a quick reading, or an in-depth study?
Please state explicitly whether you believe that the proposal should be accepted into SDL.

More information about the SDL evolution process is available at

https://github.com/smartdevicelink/sdl_evolution/blob/master/process.md

Thank you,
Joel Fischer

SDL iOS Maintainer - Livio
joel@livio.io

**Comment by joeljfischer** [comment]
* Is the problem being addressed significant enough to warrant a change to SDL?
> Yes, I believe that the ability to play general audio files directly from the head unit, as in non-media / from the phone audio, is useful.

* Does this proposal fit well with the feel and direction of SDL?
> I'm not sure. This proposal is to change `TTSChunk` but the proposal seems to imply that more than simply Text-to-Speech files will be played. I don't feel very good about having a struct named `TTSChunk` that plays generic, non-TTS files.

* If you have used competitors with a similar feature, how do you feel that this proposal compares to those?
> N/A

* How much effort did you put into your review? A glance, a quick reading, or an in-depth study? Please state explicitly whether you believe that the proposal should be accepted into SDL.
> I did an in-depth reading of this proposal and discussion with the author of the proposal. I think the ability to play audio files is warranted, but I would hesitate to accept this proposal without considering possible alternatives. I do not like that this is a generic "play audio" wrapped in a struct meant for Text-to-Speech. I do like that this requires so little changes to SDL and automatically fits with `PerformAudioPassThru`, `Alert`, etc.
I give this a very hesitant **yes**.

**Comment by joeljfischer** [comment]
This proposal was accepted. The committee feels it is a good feature to add to give apps some personality and to enable new features, and while the naming isn't ideal, it gives us the maximum amount of flexibility with the minimum extra development cost. 

The implementation will have to be fleshed out on core to ensure backward compatibility.

**Comment by theresalech** [comment]
Issues entered:
[Android](https://github.com/smartdevicelink/sdl_android/issues/419)
[Core](https://github.com/smartdevicelink/sdl_core/issues/1277)
[iOS](https://github.com/smartdevicelink/sdl_ios/issues/524)
