### ISSUE TITLE
[Accepted] SDL 0155 - Mobile Menu Manager

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_evolution#445]
Hello SDL community,

The review of "Mobile Menu Manager" begins now and runs through April 3, 2018. The proposal is available here:

https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0155-mobile-menu-manager.md

Reviews are an important part of the SDL evolution process. All reviews should be sent to the associated Github issue at:

https://github.com/smartdevicelink/sdl_evolution/issues/445

What goes into a review?

The goal of the review process is to improve the proposal under review through constructive criticism and, eventually, determine the direction of SDL. When writing your review, here are some questions you might want to answer in your review:

* Is the problem being addressed significant enough to warrant a change to SDL?
* Does this proposal fit well with the feel and direction of SDL?
* If you have used competitors with a similar feature, how do you feel that this proposal compares to those?
* How much effort did you put into your review? A glance, a quick reading, or an in-depth study?
Please state explicitly whether you believe that the proposal should be accepted into SDL.

More information about the SDL evolution process is available at

https://github.com/smartdevicelink/sdl_evolution/blob/master/process.md

Thank you,
Theresa Lech

Program Manager - Livio
theresa@livio.io

**Comment by AndrewRMitchell** [comment]
I do like the idea of a dataSource / delegate based API, but I think this is a good first step, and one that should be taken. Any changes needed when we get to that point are going to happen unless we flush that API out now, which I don't think is the right thing to do at this point. I therefor support the proposal as written.

**Comment by shengbi** [comment]
Will it support Menu -> 1st SubMenu -> 2nd SubMenu and the 2nd SubMenu can have a back button goes back to the 1st SubMenu? E.g. on SYNC 3, ScrollableMessage will automatically add a back-arrow in the top left corner but it would go all the way back to the main menu not the previous SubMenu.

**Comment by joeljfischer** [comment]
@shengbi 

> Will it support Menu -> 1st SubMenu -> 2nd SubMenu

It will not because that is not a supported feature of SDL at this point. It could in the future support it when that feature exists in SDL. 

> and the 2nd SubMenu can have a back button goes back to the 1st SubMenu? E.g. on SYNC 3, ScrollableMessage will automatically add a back-arrow in the top left corner but it would go all the way back to the main menu not the previous SubMenu.

No, because that is not something a mobile library can do. An OEM must develop that UI themselves, a mobile library has nothing to do with it.

**Comment by theresalech** [comment]
The Steering Committee fully agreed to accept this proposal.
