### ISSUE TITLE
[Accepted] SDL 0160 - Remote Control Radio Parameter Update

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_evolution#464]
Hello SDL community,

The review of "Remote Control Radio Parameter Update" begins now and runs through April 24, 2018. The proposal is available here:

https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0160-rc-radio-parameter-update.md

Reviews are an important part of the SDL evolution process. All reviews should be sent to the associated Github issue at:

https://github.com/smartdevicelink/sdl_evolution/issues/464

What goes into a review?

The goal of the review process is to improve the proposal under review through constructive criticism and, eventually, determine the direction of SDL. When writing your review, here are some questions you might want to answer in your review:

* Is the problem being addressed significant enough to warrant a change to SDL?
* Does this proposal fit well with the feel and direction of SDL?
* If you have used competitors with a similar feature, how do you feel that this proposal compares to those?
* How much effort did you put into your review? A glance, a quick reading, or an in-depth study?
Please state explicitly whether you believe that the proposal should be accepted into SDL.

More information about the SDL evolution process is available at

https://github.com/smartdevicelink/sdl_evolution/blob/master/process.md

Thank you,
Theresa Lech

Program Manager - Livio
theresa@livio.io

**Comment by kshala-ford** [comment]
To me the proposal looks good. I guess HD radio enable only makes sense with `RadioBand.XM` otherwise it's ignored?

Don't want to be fussy... but changing the maxvalue would be a signature change. The xml should be like (expecting version 5.0 comes after 4.5):

```xml
<param name="availableHDs" type="Integer" minvalue="1" maxvalue="7" mandatory="false" since="5.0">
  <description>number of HD sub-channels if available</description>
  <history>
    <param name="availableHDs" type="Integer" minvalue="1" maxvalue="3" mandatory="false" since="4.5" until="4.5" />
  </history>
</param>
<param name="hdChannel" type="Integer" minvalue="1" maxvalue="7" mandatory="false" since="5.0">
  <description>Current HD sub-channel if available</description>
  <history>
    <param name="hdChannel" type="Integer" minvalue="1" maxvalue="3" mandatory="false" since="4.5" until="4.5">
  </history>
</param>
```

**Comment by yang1070** [comment]
@kshala-ford 
HD radio relate to AM/FM radio.  It has nothing to do with XM radio. Here is a wiki link https://en.wikipedia.org/wiki/HD_Radio.

**Comment by theresalech** [comment]
The Steering Committee fully agreed to accept this proposal.

**Comment by theresalech** [comment]
Issues Entered:
[RPC Spec](https://github.com/smartdevicelink/rpc_spec/issues/83)
[Android](https://github.com/smartdevicelink/sdl_android/issues/741)
[iOS](https://github.com/smartdevicelink/sdl_ios/issues/945)
[Core](https://github.com/smartdevicelink/sdl_core/issues/2162)
