### ISSUE TITLE
[Accepted with Revisions] SDL 0165 - Remote Control – Lights – More Names and Status Values

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_evolution#479]
Hello SDL community,

The review of "Remote Control – Lights – More Names and Status Values" begins now and runs through May 1, 2018. The proposal is available here:

https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0165-rc-lights-more-names-and-status-values.md

Reviews are an important part of the SDL evolution process. All reviews should be sent to the associated Github issue at:

https://github.com/smartdevicelink/sdl_evolution/issues/479

What goes into a review?

The goal of the review process is to improve the proposal under review through constructive criticism and, eventually, determine the direction of SDL. When writing your review, here are some questions you might want to answer in your review:

* Is the problem being addressed significant enough to warrant a change to SDL?
* Does this proposal fit well with the feel and direction of SDL?
* If you have used competitors with a similar feature, how do you feel that this proposal compares to those?
* How much effort did you put into your review? A glance, a quick reading, or an in-depth study?
Please state explicitly whether you believe that the proposal should be accepted into SDL.

More information about the SDL evolution process is available at

https://github.com/smartdevicelink/sdl_evolution/blob/master/process.md

Thank you,
Theresa Lech

Program Manager - Livio
theresa@livio.io

**Comment by joeljfischer** [comment]
Just a few small notes:

1. I'd like to see documentation on each of the enum names.
2. What error and `info` should be returned if the developer uses an enum they shouldn't? I'd say probably `INVALID_DATA` and `info="The LightStatus enum passed is READ ONLY and cannot be written."

**Comment by yang1070** [comment]
@joeljfischer For your 2nd question, I agree with your suggestion in the case if the application uses a light status enum value that meant to be read-only.  info="The LightStatus enum passed is READ ONLY and cannot be written.", result code `INVALID_DATA` is good for indicates the error, but probably code `READ_ONLY` is more specific.

There is another case,  if the application uses a light name that is not in the supported light name list returned by the capabilities, sdl can use result code `UNSUPPORTED_RESOURCE`, and info "The requested LightName is not supported by the vehicle"

**Comment by AndrewRMitchell** [comment]
I'd also like to see documentation on each of the light names. And I had to go read 099 to get full context to make sure I was commenting on things that already existed (I was about to).

**Comment by yang1070** [comment]
```xml
+   <element name="REAR_CARGO_LIGHTS" value="512">
+     <description>
+       Cargo lamps eluminate the cargo area.
+     </description>
+   </element>
+   <element name="REAR_TRUCK_BED_LIGHTS" value="513">
+     <description>
+       Truck bed lamps light up the bed of the truck.
+     </description>
+   </element>
+   <element name="REAR_TRAILER_ASSIST_LIGHTS" value="514">
+     <description>
+       Trailer lights are lamps mounted on a trailer hitch.
+     </description>
+   </element>
+   <element name="LEFT_SPOT_LIGHTS" value="515">
+     <description>
+       It is the spotlights mounted on the left side of a vehicle.
+     </description>
+   </element>
+   <element name="RIGHT_SPOT_LIGHTS" value="516">
+     <description>
+       It is the spotlights mounted on the right side of a vehicle.
+     </description>
+   </element>
+   <element name="LEFT_PUDDLE_LIGHTS" value="517">
+     <description>
+       Puddle lamps illuminate the ground beside the door as the customer is opening or approaching the door.
+     </description>
+   </element>
+   <element name="RIGHT_PUDDLE_LIGHTS" value="518">
+     <description>
+       Puddle lamps illuminate the ground beside the door as the customer is opening or approaching the door.
+     </description>
+   </element>
```

**Comment by theresalech** [comment]
The Steering Committee voted to accept this proposal with the revisions.  The revisions will include the error and documentation as described in [this comment](https://github.com/smartdevicelink/sdl_evolution/issues/479#issuecomment-384992052) and [this comment](https://github.com/smartdevicelink/sdl_evolution/issues/479#issuecomment-385676952), respectively.

**Comment by theresalech** [comment]
@yang1070 please advise when a new PR has been entered to update the proposal to reflect the agreed upon revisions. I'll then merge the PR so the proposal is up to date, and enter issues in the respective repositories for implementation. Thanks!

**Comment by theresalech** [comment]
Proposal has been revised to reflect revisions, and issues have been entered:
[RPC](https://github.com/smartdevicelink/rpc_spec/issues/87)
[Core](https://github.com/smartdevicelink/sdl_core/issues/2172)
[iOS](https://github.com/smartdevicelink/sdl_ios/issues/954)
[Android](https://github.com/smartdevicelink/sdl_android/issues/751)
