### ISSUE TITLE
[Accepted with Revisions] SDL 0168 - RPC design refactoring

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_evolution#486]
Hello SDL community,

The review of "SDL 0168 - RPC design refactoring" begins now and runs through May 8, 2018.  The proposal is available here:

https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0168-rpc-design-refactoring.md

Reviews are an important part of the SDL evolution process. All reviews should be sent to the associated Github issue at:

https://github.com/smartdevicelink/sdl_evolution/issues/486

What goes into a review?

The goal of the review process is to improve the proposal under review through constructive criticism and, eventually, determine the direction of SDL. When writing your review, here are some questions you might want to answer in your review:

* Is the problem being addressed significant enough to warrant a change to SDL?
* Does this proposal fit well with the feel and direction of SDL?
* If you have used competitors with a similar feature, how do you feel that this proposal compares to those?
* How much effort did you put into your review? A glance, a quick reading, or an in-depth study?
Please state explicitly whether you believe that the proposal should be accepted into SDL.

More information about the SDL evolution process is available at

https://github.com/smartdevicelink/sdl_evolution/blob/master/process.md

Thank you,
Theresa Lech

Program Manager - Livio
theresa@livio.io

**Comment by LuxoftAKutsan** [comment]
@Jack as first step I would just extract `Remote control` group from overall RPC's. 
As next step I see some Navigation Group, may be VR/TTS group, this could be investigated.
BTW,  HMI interfaces have already some RPC splitting by functionality. 
Not all of them are applicable for MOBILE_API (for example Add command required for both of them) but I would think in same direction.

**Comment by theresalech** [comment]
The Steering Committee voted to accept this proposal with the following revision: extract both `Remote control` and `Vehicle data` groups into separate plugins from the other RPCs.

**Comment by theresalech** [comment]
Proposal has been revised to reflect revisions, and issue has been entered:[[SDL 0168] RPC design refactoring](https://github.com/smartdevicelink/sdl_core/issues/2189)
