### ISSUE TITLE
[Returned for Revisions] SDL 0169 - Arguments initialText and hintText for SDL Keyboard

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_evolution#488]
Hello SDL community,

The review of "SDL 0169 - Arguments initialText and hintText for SDL Keyboard" begins now and runs through May 15, 2018.  The proposal is available here:

https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0169-initial-and-hint-text-for-keyboard.md

Reviews are an important part of the SDL evolution process. All reviews should be sent to the associated Github issue at:

https://github.com/smartdevicelink/sdl_evolution/issues/488

What goes into a review?

The goal of the review process is to improve the proposal under review through constructive criticism and, eventually, determine the direction of SDL. When writing your review, here are some questions you might want to answer in your review:

* Is the problem being addressed significant enough to warrant a change to SDL?
* Does this proposal fit well with the feel and direction of SDL?
* If you have used competitors with a similar feature, how do you feel that this proposal compares to those?
* How much effort did you put into your review? A glance, a quick reading, or an in-depth study?
Please state explicitly whether you believe that the proposal should be accepted into SDL.

More information about the SDL evolution process is available at

https://github.com/smartdevicelink/sdl_evolution/blob/master/process.md

Thank you,
Theresa Lech

Program Manager - Livio
theresa@livio.io

**Comment by kshala-ford** [comment]
I read through the proposal but I'm not sure if I fully understand the requested changes. To my understanding it's proposed to
1. change how HMI should use `.initialText` in the HMI integration guideline 
2. add a new parameter `.hintText` to the mobile API  (which is mentioned but not specified)

I agree: It would make more sense to explain to the developers "Use `.initialText` to set the initial text of the text field" in the documentation. However this would be backwards incompatible and (in combination with 2.) a breaking change. Furthermore the parameter would behave differently for list/icon/voice mode.

The closest you can get with the current API would be to 
- keep using `.initialText` as a brief hint which disappears when entering text and 
- use `SetGlobalProperties.autoCompleteText` as one specific example the user can select

It's not perfect... but that would work today.

**Comment by theresalech** [comment]
The Steering Committee voted to defer this proposal, keeping it in review until our next meeting on 2018-05-22.

In addition to the points made in [this comment](https://github.com/smartdevicelink/sdl_evolution/issues/488#issuecomment-388799354), it was noted that this proposal will need to include the specific RPC Mobile API changes, which would likely be backwards incompatible (breaking) changes, as they change how `initialText` is used.  It was also agreed that the proposal should detail that this feature would require a major version change.

**Comment by theresalech** [comment]
This proposal has remained inactive for an extended period of time and will therefore be closed.  The issue will remain in a `returned for revisions` status and unlocked so the author can notify the Project Maintainer when it is ready to be revisited.

**Comment by kshala-ford** [comment]
@theresalech Ford EU has received a change request by app partners related to this proposal. I would like to take over the proposal and do some revisions.
