### ISSUE TITLE
[Accepted with Revisions] SDL 0158 - Cloud App Transport Adapter (Revised)

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_evolution#493]
Hello SDL community,

The review of the revised "Cloud App Transport Adapter" proposal begins now and runs through May 22, 2018. The proposal is available here:

https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0158-cloud-app-transport-adapter.md

Reviews are an important part of the SDL evolution process. All reviews should be sent to the associated Github issue at:

https://github.com/smartdevicelink/sdl_evolution/issues/493

Reviews of the original "Cloud App Transport Adapter" proposal can be found on this issue: https://github.com/smartdevicelink/sdl_evolution/issues/452

What goes into a review?

The goal of the review process is to improve the proposal under review through constructive criticism and, eventually, determine the direction of SDL. When writing your review, here are some questions you might want to answer in your review:

* Is the problem being addressed significant enough to warrant a change to SDL?
* Does this proposal fit well with the feel and direction of SDL?
* If you have used competitors with a similar feature, how do you feel that this proposal compares to those?
* How much effort did you put into your review? A glance, a quick reading, or an in-depth study?
Please state explicitly whether you believe that the proposal should be accepted into SDL.

More information about the SDL evolution process is available at

https://github.com/smartdevicelink/sdl_evolution/blob/master/process.md

Thank you,
Theresa Lech

Program Manager - Livio
theresa@livio.io

**Comment by AndrewRMitchell** [comment]
I just wanted to say thank you. I know it took us a long time to get here, but I think the resulting document is well worth the effort put in to it. I may have my own personal concerns, but this addresses most of them, and gives us a way forward on the rest. Kudos to everyone involved.

**Comment by theresalech** [comment]
The Steering Committee voted to accept this proposal, with the following revision: where it is mentioned in the proposal to send a status of "CONNECTING", it should say "RETRY" instead.

**Comment by theresalech** [comment]
@JackLivio please advise when a new PR has been entered to update the proposal to reflect the agreed upon revisions. I'll then merge the PR so the proposal is up to date, and enter an issue in the Core repository for implementation. Thanks!
