### ISSUE TITLE
[Accepted with Revisions] SDL 0171 - Android Manager APIs

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_evolution#500]
Hello SDL community,

The review of "SDL 0171 - Android Manager APIs" begins now and runs through June 5, 2018.  The proposal is available here:

https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0171-android-manager-apis.md

Reviews are an important part of the SDL evolution process. All reviews should be sent to the associated Github issue at:

https://github.com/smartdevicelink/sdl_evolution/issues/500

What goes into a review?

The goal of the review process is to improve the proposal under review through constructive criticism and, eventually, determine the direction of SDL. When writing your review, here are some questions you might want to answer in your review:

* Is the problem being addressed significant enough to warrant a change to SDL?
* Does this proposal fit well with the feel and direction of SDL?
* If you have used competitors with a similar feature, how do you feel that this proposal compares to those?
* How much effort did you put into your review? A glance, a quick reading, or an in-depth study?
Please state explicitly whether you believe that the proposal should be accepted into SDL.

More information about the SDL evolution process is available at

https://github.com/smartdevicelink/sdl_evolution/blob/master/process.md

Thank you,
Theresa Lech

Program Manager - Livio
theresa@livio.io

**Comment by joeljfischer** [comment]
Minor notes (note that I'm not super familiar with the Android library):

### SdlManager
1. I don't know if you want to do the same as the iOS library in combining the `isMediaApp` and `AppType` setters. If the app has a `MEDIA` app type, the iOS lib automatically sets `isMediaApp`. This has worked well so far.

2. The Builder appears to be missing some things such as `shortAppName` etc.

### BaseSubManager
1. You may find that you need additional manager states for individual managers than those available in the `BaseSubManager`.

### SoftButtonManager
1. The soft button manager and text and graphic manager are noted as non-developer facing but are listed as `public`.

2. In order for `endUpdates` with a completion handler, the `update()` method would need one as well.

### Other
1. The `CompletionListener` should probably return a developer inspectable error so the developer knows what went wrong.

* Notes for future managers: Menu, Choice Set, Change Registration

**Comment by bilal-alsharifi** [comment]
Thanks for going over the proposal and providing helpful your comments @joeljfischer 

> I don't know if you want to do the same as the iOS library in combining the isMediaApp and AppType setters. If the app has a MEDIA app type, the iOS lib automatically sets isMediaApp. This has worked well so far.

I think combining the isMediaApp and AppType setters as you described will be a very good idea. Because the difference between the `MEDIA` app type and `isMediaApp` flag is confusing.

> The Builder appears to be missing some things such as shortAppName etc.

Yes we missed that one, we probably should also add `vrSynonyms`, `ttsChunks`, and `hmiLanguage` in addition to the `shortAppName`.

> You may find that you need additional manager states for individual managers than those available in the BaseSubManager.

We added only the basic states for now. We can add more states to `ManagerState` as needed.

> The soft button manager and text and graphic manager are noted as non-developer facing but are listed as public.

I think the modifiers should be changed to make `TextAndGraphicManager ` and `SoftButtonManager` only accessible within their package.

> In order for endUpdates with a completion handler, the update() method would need one as well.

You are right. We probably have to add `CompletionListener` to the `update()` method as well.

**Comment by theresalech** [comment]
The Steering Committee voted to accept this proposal with revisions.  The revisions will include those outlined in [this comment](https://github.com/smartdevicelink/sdl_evolution/issues/500#issuecomment-394739127) from one of the authors of the proposal.

**Comment by theresalech** [comment]
@bilal-alsharifi @joeygrover @brettywhite please advise when a new PR has been entered to update the proposal to reflect the agreed upon revisions. I'll then merge the PR so the proposal is up to date, and enter an issue in the Android repository for implementation. Thanks!

**Comment by theresalech** [comment]
Proposal has been revised to reflect revisions, and issue has been entered: [[SDL 0171] Android Manager APIs](https://github.com/smartdevicelink/sdl_android/issues/782)
