### ISSUE TITLE
[Accepted with Revisions] SDL 0174 - Deprecate RPCRequestFactory

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_evolution#509]
Hello SDL community,

The review of "SDL 0174 - Deprecate RPCRequestFactory" begins now and runs through June 12, 2018.  The proposal is available here:

https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0174-deprecate-rpc-request-factory.md

Reviews are an important part of the SDL evolution process. All reviews should be sent to the associated Github issue at:

https://github.com/smartdevicelink/sdl_evolution/issues/509

What goes into a review?

The goal of the review process is to improve the proposal under review through constructive criticism and, eventually, determine the direction of SDL. When writing your review, here are some questions you might want to answer in your review:

* Is the problem being addressed significant enough to warrant a change to SDL?
* Does this proposal fit well with the feel and direction of SDL?
* If you have used competitors with a similar feature, how do you feel that this proposal compares to those?
* How much effort did you put into your review? A glance, a quick reading, or an in-depth study?
Please state explicitly whether you believe that the proposal should be accepted into SDL.

More information about the SDL evolution process is available at

https://github.com/smartdevicelink/sdl_evolution/blob/master/process.md

Thank you,
Theresa Lech

Program Manager - Livio
theresa@livio.io

**Comment by bilal-alsharifi** [comment]
Thanks Joel for reviewing the proposal.

> Note that the potential downside is not quite clear. This proposal only deprecates RPCRequestFactory, which is a minor change. At the time of the next major change the deprecated class will be removed. This proposal itself is not a major change.

Yes that is right. Deprecating the class as described in the proposal is a minor change as you said but removing the deprecated class later will be a major change. Sorry for being not very clear about that point.

**Comment by theresalech** [comment]
The Steering Committee voted to accept this proposal with revisions.  The revisions will be clarifying that the proposal itself is not a major change, but instead, at the time of the next major change, the deprecated class will be removed.

**Comment by theresalech** [comment]
@bilal-alsharifi please advise when a new PR has been entered to update the proposal to reflect the agreed upon revisions. I'll then merge the PR so the proposal is up to date, and enter an issue in the Android repository for implementation. Thanks!

**Comment by theresalech** [comment]
Proposal has been revised and issue has been entered: [[SDL 0174] Deprecate RPCRequestFactory](https://github.com/smartdevicelink/sdl_android/issues/792).
