### ISSUE TITLE
[Accepted with Revisions] SDL 0175 - Updating DOP value range for GPS notification

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_evolution#510]
Hello SDL community,

The review of the revised proposal "SDL 0175 - Updating DOP value range for GPS notification" begins now and runs through June 26, 2018.  The original review of "SDL 0175 - Updating DOP value range for GPS notification" took place June 6 through June 12, 2018.  The proposal is available here:

https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0175-Updating-DOP-value-range-for-GPS-notification.md

Reviews are an important part of the SDL evolution process. All reviews should be sent to the associated Github issue at:

https://github.com/smartdevicelink/sdl_evolution/issues/510

What goes into a review?

The goal of the review process is to improve the proposal under review through constructive criticism and, eventually, determine the direction of SDL. When writing your review, here are some questions you might want to answer in your review:

* Is the problem being addressed significant enough to warrant a change to SDL?
* Does this proposal fit well with the feel and direction of SDL?
* If you have used competitors with a similar feature, how do you feel that this proposal compares to those?
* How much effort did you put into your review? A glance, a quick reading, or an in-depth study?
Please state explicitly whether you believe that the proposal should be accepted into SDL.

More information about the SDL evolution process is available at

https://github.com/smartdevicelink/sdl_evolution/blob/master/process.md

Thank you,
Theresa Lech

Program Manager - Livio
theresa@livio.io

**Comment by joeljfischer** [comment]
As a first note, to change a parameter from required to optional is a major version change to the mobile API spec. This is not noted in the proposal.

**Comment by joeygrover** [comment]
The proposed RPC spec change is incorrect. The history tagged version shows what I believe the author wishes to be the new param values to be.

**Comment by theresalech** [comment]
The Steering Committee voted to return this proposal for revisions.  The author will revise the proposal to update the proposed RPC Spec Change to be the correct format, and also note the major version change.

**Comment by theresalech** [comment]
The author has updated this proposal per the agreed upon revisions, and the revised proposal has now moved into review. The Steering Committee will vote on this revised proposal during the 2018-06-26 meeting.

**Comment by joeljfischer** [comment]
No maxvalue is defined for the new `pdop`, etc. values. Other than that, assuming the author is okay with this being a major version change (and therefore probably not being implemented for quite a while), I don't have a problem with it.

**Comment by atiwari9** [comment]
@joeljfischer  - Max value is capped by type _Integer_. Do we still need to mention _maxValue_ even it is capped by data type? 

I am ok with this being major version change.

**Comment by atiwari9** [comment]
@joeljfischer  - Ok, i'll include the maxValue then. Since the intent is to remove the maxValue cap, i'd keep it at relatively higher value @ _maxValue=1000_

**Comment by theresalech** [comment]
The Steering Committee voted to accept this proposal with revisions.  The revision will be to include maxValue as described in [this comment](https://github.com/smartdevicelink/sdl_evolution/issues/510#issuecomment-400474515) from the author.

**Comment by theresalech** [comment]
@atiwari9 please advise when a new PR has been entered to update the proposal to reflect the agreed upon revisions. I'll then merge the PR so the proposal is up to date, and enter issues in the respective repositories for implementation. Thanks!

**Comment by theresalech** [comment]
Proposal has been revised to reflect revisions and issues have been entered:
[RPC](https://github.com/smartdevicelink/rpc_spec/issues/105)
[Core](https://github.com/smartdevicelink/sdl_core/issues/2317)
[iOS](https://github.com/smartdevicelink/sdl_ios/issues/1003)
[Android](https://github.com/smartdevicelink/sdl_android/issues/803)
