### ISSUE TITLE
[Accepted] SDL 0178 - Interior Vehicle Data Subscription Management and Data Caching in SDL

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_evolution#524]
Hello SDL community,

The review of "SDL 0178 - Interior Vehicle Data Subscription Management and Data Caching in SDL" begins now and runs through June 26, 2018.  The proposal is available here:

https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0178-GetInteriorVehicleData.md

Reviews are an important part of the SDL evolution process. All reviews should be sent to the associated Github issue at:

https://github.com/smartdevicelink/sdl_evolution/issues/524

What goes into a review?

The goal of the review process is to improve the proposal under review through constructive criticism and, eventually, determine the direction of SDL. When writing your review, here are some questions you might want to answer in your review:

* Is the problem being addressed significant enough to warrant a change to SDL?
* Does this proposal fit well with the feel and direction of SDL?
* If you have used competitors with a similar feature, how do you feel that this proposal compares to those?
* How much effort did you put into your review? A glance, a quick reading, or an in-depth study?
Please state explicitly whether you believe that the proposal should be accepted into SDL.

More information about the SDL evolution process is available at

https://github.com/smartdevicelink/sdl_evolution/blob/master/process.md

Thank you,
Theresa Lech

Program Manager - Livio
theresa@livio.io

**Comment by joeljfischer** [comment]
Unfortunately, the sequence diagrams do not appear to be present in the proposal. The change seems okay, though the HMI API change would be major, unless it were deprecated and sent by Core as `0`, for example.

**Comment by yang1070** [comment]
@joeljfischer It's strange. I cannot see the diagrams within Ford network. I can see it using the same computer at home or using my phone's browser. I'd like to know if anybody else encounter the same issue of diagram not showing up.

**Comment by yang1070** [comment]
@joeljfischer It's OK with me to deprecated the `appID` parameter in HMI API and SDL always set it as `0`.

**Comment by joeygrover** [comment]
Overall I like having core manage the logic of its clients. I believe the HMI and modules becomes much clearer with this dynamic.

I think deprecation of the `appID` parameter would be good if we where avoiding a breaking change, but if the release plans to be a breaking change it seems best to just do away with it.

The only area I have a question on is the actual cached data.  I might have just not understood, but let me know if my assumptions are correct:

1.  If no app subscribes to a module, its data will not be cached. Therefore, every `GetInteriorVehicleData` request from the app will be forwarded to the HMI/module until a subscription is requested.
2. If an app subscribes to a module, Core will then start to cache that module's data and update it when it receives an `OnInteriorVehicleData` from the HMI, and forwards the notification to the apps that are subscribed.

**Comment by yang1070** [comment]
@joeygrover Yes, your assumptions are correct.

**Comment by theresalech** [comment]
The Steering Committee voted to accept this proposal.  It was noted that if this feature is included in a minor Core release, we will deprecate the `appID` parameter, and if it's included in a major Core release, we will remove the parameter from the HMI API.

**Comment by theresalech** [comment]
Issues Entered:
[RPC](https://github.com/smartdevicelink/rpc_spec/issues/106)
[Core](https://github.com/smartdevicelink/sdl_core/issues/2318)
