### ISSUE TITLE
[Accepted] SDL 0179 - Pixel density and Scale

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_evolution#526]
Hello SDL community,

The review of "SDL 0179 - Pixel density and Scale" begins now and runs through June 26, 2018.  The proposal is available here:

https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0179-pixel-density-and-scale.md

Reviews are an important part of the SDL evolution process. All reviews should be sent to the associated Github issue at:

https://github.com/smartdevicelink/sdl_evolution/issues/526

What goes into a review?

The goal of the review process is to improve the proposal under review through constructive criticism and, eventually, determine the direction of SDL. When writing your review, here are some questions you might want to answer in your review:

* Is the problem being addressed significant enough to warrant a change to SDL?
* Does this proposal fit well with the feel and direction of SDL?
* If you have used competitors with a similar feature, how do you feel that this proposal compares to those?
* How much effort did you put into your review? A glance, a quick reading, or an in-depth study?
Please state explicitly whether you believe that the proposal should be accepted into SDL.

More information about the SDL evolution process is available at

https://github.com/smartdevicelink/sdl_evolution/blob/master/process.md

Thank you,
Theresa Lech

Program Manager - Livio
theresa@livio.io

**Comment by joeljfischer** [comment]
I think that these are good changes. The guidelines for OEMs on keeping a 50x50px button at a certain size is important, while also keeping to whole px values if possible.

**Comment by joeygrover** [comment]
For the most part I agree with the proposal. I would suggest still considering adding the additional parameters to the protocol video service `StartService(ACK)`. If the module wanted to NAK a start service request based on their parameters used it might be helpful (incorrect scale or lack thereof for example).

**Comment by kshala-ford** [comment]
@joeygrover I don't know if that's really necessary. First: It would be not more than a confirmation but still it's no guarantee that the application will scale the screen. Second: (at least for iOS) Scaling would be handled automatically by the car window. The app developer wouldn't even recognize the requested scale.

**Comment by theresalech** [comment]
The Steering Committee fully agreed to accept this proposal.

**Comment by theresalech** [comment]
Issues Entered:
[RPC](https://github.com/smartdevicelink/rpc_spec/issues/107)
[Core](https://github.com/smartdevicelink/sdl_core/issues/2319)
[iOS](https://github.com/smartdevicelink/sdl_ios/issues/1007)
[Android](https://github.com/smartdevicelink/sdl_android/issues/804)
