### ISSUE TITLE
[Accepted with Revisions] SDL 0180 - Broaden Choice Uniqueness

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_evolution#530]
Hello SDL community,

The review of "SDL 0180 - Broaden Choice Uniqueness" begins now and runs through July 10, 2018.  The proposal is available here:

https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0180-broaden-choice-uniqueness.md

Reviews are an important part of the SDL evolution process. All reviews should be sent to the associated Github issue at:

https://github.com/smartdevicelink/sdl_evolution/issues/530

What goes into a review?

The goal of the review process is to improve the proposal under review through constructive criticism and, eventually, determine the direction of SDL. When writing your review, here are some questions you might want to answer in your review:

* Is the problem being addressed significant enough to warrant a change to SDL?
* Does this proposal fit well with the feel and direction of SDL?
* If you have used competitors with a similar feature, how do you feel that this proposal compares to those?
* How much effort did you put into your review? A glance, a quick reading, or an in-depth study?
Please state explicitly whether you believe that the proposal should be accepted into SDL.

More information about the SDL evolution process is available at

https://github.com/smartdevicelink/sdl_evolution/blob/master/process.md

Thank you,
Theresa Lech

Program Manager - Livio
theresa@livio.io

**Comment by joeygrover** [comment]
I agree with the proposal that the use of primary text as a key is a terrible idea and should be changed. I'd like to know how it's planned to have the managers handle the backwards compatibility cases.

- How will the managers know if a choice item and a sub-menu add command have the same primary text? I believe the managers are managing each of these lists separately so a cross check would have to occur. Might be valuable to see how the logic would be created here.
-  Would the primary text have something appended to it to handle the backwards compatible issue?

**Comment by joeljfischer** [comment]
> How will the managers know if a choice item and a sub-menu add command have the same primary text? I believe the managers are managing each of these lists separately so a cross check would have to occur. Might be valuable to see how the logic would be created here.

I'm sorry if this is unclear. To my knowledge, each of these lists is separate on Core as well. So this proposal is to alter each, separately.

> Would the primary text have something appended to it to handle the backwards compatible issue?

This is a good point. We would probably have to check the connected version of Core and append something like `(1)`, `(2)` for previous versions.

**Comment by joeygrover** [comment]
>I'm sorry if this is unclear. To my knowledge, each of these lists is separate on Core as well. So this proposal is to alter each, separately.

>Edit: Also, to be clear, the primary text isn't actually the key. The limitation of unique primary text doesn't appear to be a limitation of e.g. it being a dictionary key. They are keyed by the choiceID / menuID. The restriction appears to be arbitrary.

Alright I think I misunderstood part of the issue, understood.

> This is a good point. We would probably have to check the connected version of Core and append something like (1), (2) for previous versions.

I think numbering seems easiest, though I do worry that if the text is exact except for the number it might be confusing for app developers.

**Comment by atiwari9** [comment]
@joeljfischer  - For sub-menu AddCommand, is the intention to possibly have multiple AddCommands with same menuName in given SubMenu? If yes, how would the consumer differentiate between these commands since menuName is the only user side HMI element.?

**Comment by joeljfischer** [comment]
@atiwari9 I understand your point, but (1) they can also set an icon and VR commands, (2) we don't know how developers might use it. For example, if there are 2 McDonalds that so happen to be 3.9 miles away and they try to show "McDonalds (3.9 miles)", they shouldn't be prevented from doing so by an arbitrary error they almost certainly are not prepared to handle. 

Maybe that's slightly confusing to the user at the time, but it's better than an error. Adding in that they could send an icon with the direction which would make it clear, for example, then you have a restriction that's clearly harmful to the developer.

**Comment by atiwari9** [comment]
@joeljfischer  - I understand the motivation for allowing same menuName for choices since app can provide secondary text to provide more details e.g. Address, Direction etc. But for HMI AddCommand, same name could be confusing to the user as such. But in the end it will be up to the app developers to ensure that user is not confused between the options if we remove this check for AddCommand. We could potentially mention this in developer guidelines as well.

**Comment by theresalech** [comment]
The Steering Committee voted to accept this proposal with the following revisions: numbers should be added after duplicate(s) for older versions of core, and documentation should call out that while the primary text doesn't have to be unique, it has to be clear.

**Comment by theresalech** [comment]
@joeljfischer please advise when a new PR has been entered to update the proposal to reflect the agreed upon revisions. I'll then merge the PR so the proposal is up to date, and enter issues in the respective repositories for implementation. Thanks!

**Comment by theresalech** [comment]
JavaScript Suite issue: https://github.com/smartdevicelink/sdl_javascript_suite/issues/345
