### ISSUE TITLE
[Accepted] SDL 0181 - SDL shall not put RC applications to HMI level NONE when user disables RC in HMI

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_evolution#531]
Hello SDL community,

The review of "SDL 0181 - SDL shall not put RC applications to HMI level NONE when user disables RC in HMI" begins now and runs through July 10, 2018.  The proposal is available here:

https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0181-keep-rc-app-hmi-level-when-disable-rc.md

Reviews are an important part of the SDL evolution process. All reviews should be sent to the associated Github issue at:

https://github.com/smartdevicelink/sdl_evolution/issues/531

What goes into a review?

The goal of the review process is to improve the proposal under review through constructive criticism and, eventually, determine the direction of SDL. When writing your review, here are some questions you might want to answer in your review:

* Is the problem being addressed significant enough to warrant a change to SDL?
* Does this proposal fit well with the feel and direction of SDL?
* If you have used competitors with a similar feature, how do you feel that this proposal compares to those?
* How much effort did you put into your review? A glance, a quick reading, or an in-depth study?
Please state explicitly whether you believe that the proposal should be accepted into SDL.

More information about the SDL evolution process is available at

https://github.com/smartdevicelink/sdl_evolution/blob/master/process.md

Thank you,
Theresa Lech

Program Manager - Livio
theresa@livio.io

**Comment by JackLivio** [comment]
> If the user tries to activate an RC app when RC is disabled, HMI shows a pop up “Enable remote control feature for all mobile apps? Please press Yes to enable remote control or No to cancel. See Settings to disable.”

How is this pop up created? Is this created by an alert originating from the phone, or Core? Or is this logic solely contained within the HMI?

**Comment by yang1070** [comment]
@JackLivio The pop up logic is purely in sdl hmi. It has nothing related to core or mobile.

**Comment by theresalech** [comment]
The Steering Committee fully agreed to accept this proposal.

**Comment by theresalech** [comment]
Issues entered:
[Core](https://github.com/smartdevicelink/sdl_core/issues/2377)
[SDL HMI](https://github.com/smartdevicelink/sdl_hmi/issues/102)
