### ISSUE TITLE
[Accepted with Revisions] SDL 0182 - Audio Source AM/FM/XM/DAB

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_evolution#532]
Hello SDL community,

The review of "SDL 0182 - Audio Source AM/FM/XM/DAB" begins now and runs through July 10, 2018.  The proposal is available here:

https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0182-audio-source-am-fm-xm.md

Reviews are an important part of the SDL evolution process. All reviews should be sent to the associated Github issue at:

https://github.com/smartdevicelink/sdl_evolution/issues/532

What goes into a review?

The goal of the review process is to improve the proposal under review through constructive criticism and, eventually, determine the direction of SDL. When writing your review, here are some questions you might want to answer in your review:

* Is the problem being addressed significant enough to warrant a change to SDL?
* Does this proposal fit well with the feel and direction of SDL?
* If you have used competitors with a similar feature, how do you feel that this proposal compares to those?
* How much effort did you put into your review? A glance, a quick reading, or an in-depth study?
Please state explicitly whether you believe that the proposal should be accepted into SDL.

More information about the SDL evolution process is available at

https://github.com/smartdevicelink/sdl_evolution/blob/master/process.md

Thank you,
Theresa Lech

Program Manager - Livio
theresa@livio.io

**Comment by joeljfischer** [comment]
I have some issues:

* I can't find the `RADIO_TUNER` option that is supposed removed from the `PrimaryAudioSource` in the RPC [MOBILE_API](https://github.com/smartdevicelink/rpc_spec) spec. I checked the RPC v4.6.0 branch as well.
* If it _is_ there, removing it is a breaking change that I would not recommend. It would be very difficult to mitigate and backward support for app developers. The impact is not small, as the proposal indicates.

**Comment by joeygrover** [comment]
This proposal should have actually been an update to a proposal that has not been implemented but it slated for the next release of projects. The proposal is number [0099](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0099-new-remote-control-modules-and-parameters.md). 

While initially the inclusion seems a little odd (blurring lines between radio module and audio source), I believe it does make sense to set the correct tuner audio source first since that will likely require a little extra time instead of trying to combine the ability with setting actual frequency/channel into the RadioModule set request.

**Comment by yang1070** [comment]
Yes, it is an update to the proposal 0099. We have the implementation of proposal  0099, but the implementation is still under review and not released yet.

**Comment by theresalech** [comment]
The Steering Committee voted to accept this proposal, with the following revision: the `Motivation` section of the proposal should reference that this is an update to proposal [SDL 0099](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0099-new-remote-control-modules-and-parameters.md), and include a link to that proposal.

**Comment by theresalech** [comment]
@yang1070 please advise when a new PR has been entered to update the proposal to reflect the agreed upon revisions. I'll then merge the PR so the proposal is up to date, and update issues in the respective repositories for implementation. Thanks!

**Comment by theresalech** [comment]
Proposal has been updated to reflect revisions.  Issues have been entered:
[RPC](https://github.com/smartdevicelink/rpc_spec/issues/109)
[Core](https://github.com/smartdevicelink/sdl_core/issues/2338)
[iOS](https://github.com/smartdevicelink/sdl_ios/issues/1022)
[Android](https://github.com/smartdevicelink/sdl_android/issues/809)
