### ISSUE TITLE
[Accepted] SDL 0184 - Cancel Interaction RPC

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_evolution#539]
Hello SDL community,

The review of the revised (and renamed) proposal "SDL 0184 - Cancel Interaction RPC" begins now and runs through August 14, 2018.  The original review of "SDL 0184 - Dismiss Alert RPC" occurred July 11 - July 17, 2018.  The proposal is available here:

https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0184-cancel-interaction.md

Reviews are an important part of the SDL evolution process. All reviews should be sent to the associated Github issue at:

https://github.com/smartdevicelink/sdl_evolution/issues/539

What goes into a review?

The goal of the review process is to improve the proposal under review through constructive criticism and, eventually, determine the direction of SDL. When writing your review, here are some questions you might want to answer in your review:

* Is the problem being addressed significant enough to warrant a change to SDL?
* Does this proposal fit well with the feel and direction of SDL?
* If you have used competitors with a similar feature, how do you feel that this proposal compares to those?
* How much effort did you put into your review? A glance, a quick reading, or an in-depth study?
Please state explicitly whether you believe that the proposal should be accepted into SDL.

More information about the SDL evolution process is available at

https://github.com/smartdevicelink/sdl_evolution/blob/master/process.md

Thank you,
Theresa Lech

Program Manager - Livio
theresa@livio.io

**Comment by JackLivio** [comment]
@joeljfischer The Motivation section of the proposal mentions that apps can't dismiss Alerts or a **Scrollable Message**. 

Just to be clear, are you suggesting the proposed RPC to only be able to dismiss Alerts created from the AlertRequest RPC?

Or are you suggesting the new RPC is able to dismiss any "pop-up" like view on the HMI (Alert, Scrollable Message, PerformInteraction, Slider)?

**Comment by JackLivio** [comment]
Also because apps have the ability to display alerts while another app is in full, would it be allowed for one app to dismiss the alert of a different app?

**Comment by joeljfischer** [comment]
> Or are you suggesting the new RPC is able to dismiss any "pop-up" like view on the HMI (Alert, Scrollable Message, PerformInteraction, Slider)?

Yes, sorry it was unclear. Any "pop-up" is contained in this proposal.

> Also because apps have the ability to display alerts while another app is in full, would it be allowed for one app to dismiss the alert of a different app?

No, only your own app's pop-ups would be able to be cleared.

**Comment by joeygrover** [comment]
>Yes, sorry it was unclear. Any "pop-up" is contained in this proposal.

I think this RPC might be to broad if that is the intention. I believe it would be better to give some sort of correlation between what "pop-up" should be dismissed by the request rather than a generic request that will close any "pop-up" that is currently being displayed by the app.

I would also suggests a less confusing name for the RPC as I don't consider PerformInteractions to be Alerts,`DismissDialog` perhaps.

**Comment by theresalech** [comment]
This proposal has been revised per the agreed upon revisions and the updated proposal is now in review until 2018-08-14.

**Comment by theresalech** [comment]
There was not a quorum present at the Steering Committee Meeting on 2018-08-14, so a vote on this proposal was unable to take place.  The review of this issue will extend another week, and the Steering Committee will vote during the 2018-08-21 meeting, pending a quorum is present.

**Comment by theresalech** [comment]
The Steering Committee fully agreed to accept this proposal.

**Comment by theresalech** [comment]
Issues have been entered:
[RPC](https://github.com/smartdevicelink/rpc_spec/issues/122)
[Core](https://github.com/smartdevicelink/sdl_core/issues/2533)
[iOS](https://github.com/smartdevicelink/sdl_ios/issues/1055)
[Android](https://github.com/smartdevicelink/sdl_android/issues/840)
