### ISSUE TITLE
[Accepted with Revisions] SDL 0185 - Remove Hello SDL iOS Repository

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_evolution#541]
Hello SDL community,

The review of "SDL 0185 - Remove Hello SDL iOS Repository" begins now and runs through July 17, 2018.  The proposal is available here:

https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0185-remove-hello-sdl-ios.md

Reviews are an important part of the SDL evolution process. All reviews should be sent to the associated Github issue at:

https://github.com/smartdevicelink/sdl_evolution/issues/541

What goes into a review?

The goal of the review process is to improve the proposal under review through constructive criticism and, eventually, determine the direction of SDL. When writing your review, here are some questions you might want to answer in your review:

* Is the problem being addressed significant enough to warrant a change to SDL?
* Does this proposal fit well with the feel and direction of SDL?
* If you have used competitors with a similar feature, how do you feel that this proposal compares to those?
* How much effort did you put into your review? A glance, a quick reading, or an in-depth study?
Please state explicitly whether you believe that the proposal should be accepted into SDL.

More information about the SDL evolution process is available at

https://github.com/smartdevicelink/sdl_evolution/blob/master/process.md

Thank you,
Theresa Lech

Program Manager - Livio
theresa@livio.io

**Comment by joeygrover** [comment]
I agree with the idea, but it would be important to maintain a consistent experience when developing between iOS and Android. At this point the Android library relies on the hello_sdl_android repo. It is possible to add modules to the existing Android SDL library so a similar experience could be created. I would suggest a proposal that essentially agrees to move sample apps into the library repos and remove both hello sdl repos.

**Comment by theresalech** [comment]
The Steering Committee voted to accept this proposal with the following revision: the proposal will be updated to extend to the hello_sdl_android repository as well, and note that the Android sample app be added to the sdl_android repository.

**Comment by theresalech** [comment]
Proposal has been updated to reflect revisions. Issues have been entered:
[iOS](https://github.com/smartdevicelink/sdl_ios/issues/1030)
[Android](https://github.com/smartdevicelink/sdl_android/issues/817)
