### ISSUE TITLE
[Accepted with Revisions] SDL 0186 - Template Titles

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_evolution#542]
Hello SDL community,

The review of "SDL 0186 - Template Titles" begins now and runs through July 17, 2018.  The proposal is available here:

https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0186-template-titles.md

Reviews are an important part of the SDL evolution process. All reviews should be sent to the associated Github issue at:

https://github.com/smartdevicelink/sdl_evolution/issues/542

What goes into a review?

The goal of the review process is to improve the proposal under review through constructive criticism and, eventually, determine the direction of SDL. When writing your review, here are some questions you might want to answer in your review:

* Is the problem being addressed significant enough to warrant a change to SDL?
* Does this proposal fit well with the feel and direction of SDL?
* If you have used competitors with a similar feature, how do you feel that this proposal compares to those?
* How much effort did you put into your review? A glance, a quick reading, or an in-depth study?
Please state explicitly whether you believe that the proposal should be accepted into SDL.

More information about the SDL evolution process is available at

https://github.com/smartdevicelink/sdl_evolution/blob/master/process.md

Thank you,
Theresa Lech

Program Manager - Livio
theresa@livio.io

**Comment by robinmk** [comment]
Considering the case where the weather app may use the same type of template to display the weekly view or hourly view, the SHOW RPC maybe a better candidate for adding this parameter.

**Comment by joeljfischer** [comment]
Sorry for not responding to this until now. I think that is a compromise that may have to be made, though I'm not a fan of it. It would be nice if every time we were saying "show this new screen," a semantic call was made that would present a new "blank" screen of whatever the chosen layout was, with the title, coloring, etc. that we wanted. Unfortunately, while this is how developers are used to doing it on mobile apps, the web, etc., it's not really how `setDisplayLayout` works. So that may have to be an abstraction we make in the high level interface as much as possible.

With all of that said, I'm okay changing this parameter to `Show`.

**Comment by joeygrover** [comment]
Agree with Joel's comment. If the HMI actually "reset" the template when a `SetDisplayLayout` request was sent would be great with the additions we have now, but since it doesn't `Show` does seem likely to be the better candidate.

**Comment by theresalech** [comment]
The Steering Committee voted to accept this proposal with revisions.  The revisions will include adding the parameter to the `Show` RPC and also renaming the parameter to something more specific, such as `TemplateTitle`.

**Comment by theresalech** [comment]
@joeljfischer please advise when a new PR has been entered to update the proposal to reflect the agreed upon revisions. I'll then merge the PR so the proposal is up to date, and enter issues in the respective repositories for implementation. Thanks!

**Comment by theresalech** [comment]
Proposal has been updated to reflect revisions. Issues have been entered:
[Android] (https://github.com/smartdevicelink/sdl_android/issues/818)
[Core](https://github.com/smartdevicelink/sdl_core/issues/2393)
[iOS](https://github.com/smartdevicelink/sdl_ios/issues/1031)
[RPC](https://github.com/smartdevicelink/rpc_spec/issues/112)
