### ISSUE TITLE
[Accepted with Revisions] SDL 0150 Revisions - Revise SDL-0150 - Video Streaming State

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_evolution#555]
Hello SDL community,

The review of "Revise SDL-0150 - Video Streaming State" begins now and runs through July 24, 2018. This will be a review of proposed revisions to a previously accepted but not yet implemented proposal, [SDL 0150](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0150-video-streaming-state.md).  

The pull request outlining the revisions under review is available here:

https://github.com/smartdevicelink/sdl_evolution/pull/548

Reviews are an important part of the SDL evolution process. All reviews should be sent to the associated Github issue at:

https://github.com/smartdevicelink/sdl_evolution/issues/555

What goes into a review?

The goal of the review process is to improve the proposal under review through constructive criticism and, eventually, determine the direction of SDL. When writing your review, here are some questions you might want to answer in your review:

* Is the problem being addressed significant enough to warrant a change to SDL?
* Does this proposal fit well with the feel and direction of SDL?
* If you have used competitors with a similar feature, how do you feel that this proposal compares to those?
* How much effort did you put into your review? A glance, a quick reading, or an in-depth study?
Please state explicitly whether you believe that the proposal should be accepted into SDL.

More information about the SDL evolution process is available at

https://github.com/smartdevicelink/sdl_evolution/blob/master/process.md

Thank you,
Theresa Lech

Program Manager - Livio
theresa@livio.io

**Comment by joeygrover** [comment]
If the parameter goes to non mandatory I believe we should include a `defValue`, I would assume `NOT_STREAMABLE` makes the most sense.

**Comment by joeljfischer** [comment]
@joeygrover I'm not sure how Core deals with `defValue`, does it always send that value if it's not specified to Core?

Assuming not, using `NOT_STREAMABLE` would put us in an odd situation, since if it's `NULL` we assume it's `STREAMABLE` for backward compatibility reasons. So we'd have to check version as well.

If `NULL` and version is `< 5.0` - `STREAMABLE`
If `NULL` and version is `>= 5.0` - `NOT_STREAMABLE`

**Comment by joeygrover** [comment]
Agreed, default should be `STREAMABLE` based on previous implementations without the parameter.

**Comment by theresalech** [comment]
The Steering Committee voted to accept this proposal with the revision of including a `defValue` of `STREAMABLE`.

**Comment by theresalech** [comment]
@joeljfischer please advise when this proposal has been updated to reflect the accepted revision.

**Comment by theresalech** [comment]
Proposal has been updated to reflect accepted revision and issues have been updated accordingly:
[Android](https://github.com/smartdevicelink/sdl_android/issues/734)
[Core](https://github.com/smartdevicelink/sdl_core/issues/2129)
[iOS](https://github.com/smartdevicelink/sdl_ios/issues/929)
[RPC](https://github.com/smartdevicelink/rpc_spec/issues/73)
