### ISSUE TITLE
[Accepted with Revisions] SDL 0167 - App Services - Media Service

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_evolution#557]
Hello SDL community,

The review of the Media Service service type of the larger proposal “SDL 0167 - App Services” begins now and runs through July 24, 2018. The original review of “SDL 0167 - App Services” occurred May 2 - May 8, 2018 with the vote of acceptance pending each service type review on the feature happening July 10, 2018. The app service type of the proposal in review, Media, is available here:

https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0167-app-services.md#media

The original review can be found here:

https://github.com/smartdevicelink/sdl_evolution/issues/485

Reviews are an important part of the SDL evolution process. All reviews should be sent to the associated Github issue at:

https://github.com/smartdevicelink/sdl_evolution/issues/557

What goes into a review?

The goal of the review process is to improve the proposal under review through constructive criticism and, eventually, determine the direction of SDL. When writing your review, here are some questions you might want to answer in your review:

* Is the problem being addressed significant enough to warrant a change to SDL?
* Does this proposal fit well with the feel and direction of SDL?
* If you have used competitors with a similar feature, how do you feel that this proposal compares to those?
* How much effort did you put into your review? A glance, a quick reading, or an in-depth study?
Please state explicitly whether you believe that the proposal should be accepted into SDL.

More information about the SDL evolution process is available at

https://github.com/smartdevicelink/sdl_evolution/blob/master/process.md

Thank you,
Theresa Lech

Program Manager - Livio
theresa@livio.io

**Comment by joeljfischer** [comment]
I think several additions could be made:

```
<param name="trackNumber" type="Int" mandatory="false"/>
<param name="isExplicit" type="Bool" mandatory="false"/>
<param name="playbackDuration" type="Bool" mandatory="false"/>
```

I'm not sure about the utility of `mediaStation`. If we're adding radio-specific data, then we should add podcast and audiobook specific data as well. We are using the nomenclature of `album` and `artist` but a lot of media doesn't use those fields. For example, what does a podcast put as the album or artist? Or an Audiobook? Those fields don't exactly apply. So we can either make them more generic, or we can do something like:

```xml
<enum name="MediaType">
  <element name="music">
  <element name="podcast">
  <element name="audiobook">
  <element name="other">
</enum>

<struct name="MediaServiceData">
  <param name="mediaType" type="MediaType" mandatory="false"/>
  <param name="mediaTitle" type="String" mandatory="false"/>
  <param name="mediaArtist" type="String" mandatory="false"/>
  <param name="mediaAlbum" type="String" mandatory="false"/>
  <param name="podcastTitle" type="String" mandatory="false"/>
  <param name="audiobookName" type="String" mandatory="false"/>
</struct>
```

Then the developer would be expected to use the `podcastTitle` or `audiobookName` in place of the artist / album, while still using the title for the episode name / audiobook chapter name. This is how iTunes does it for podcasts, though not for audiobooks (I'm not sure how they manage that data).

**Comment by robinmk** [comment]
1. In my opinion, it makes sense to add the types of data that the system can identify. 
In that regards, this proposal seems to directly use the meta-data types which were previously defined in the proposal:https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0073-Adding-Metadata-Types.md

2. A concern (maybe unfounded) I have is regarding the potential for too many notifications (`OnAppServiceData`) if the ServiceData contained a param whose value might change frequently (like media timer). I am not sure what would be the best way to control that but to list a few ideas:
a. Indicate via some param in the API if that ServiceData item can be subscribed.
b. Ensuring not to support parameters which may frequently change.
c. Defining a period for updates.

**Comment by joeljfischer** [comment]
> In my opinion, it makes sense to add the types of data that the system can identify.
In that regards, this proposal seems to directly use the meta-data types which were previously defined in the proposal:https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0073-Adding-Metadata-Types.md

I disagree with this. Those metadata types were all strings designed for the four metadata text fields, not at all for something like this proposal. Having a boolean field like `isExplicit` is impossible using those types, but is still very useful. We shouldn't limit ourselves to those types.

**Comment by robinmk** [comment]
How will these data be set by a service provider? My understanding is that the `AppServiceData` can only be fetched.

**Comment by joeygrover** [comment]
Well that would work for core sending to subscribed clients, but do we want to rate limit from app service publisher to core?

**Comment by theresalech** [comment]
The Steering Committee voted to defer this proposal, keeping it in review until our next meeting on 2018-07-31, to allow additional discussion on the review issue.  It was also decided that the requested rate limiting change should be opened as a new PR against the original app services proposal.

**Comment by theresalech** [comment]
The Steering Committee voted to defer this proposal, keeping it in review until our next meeting on 2018-08-07, to allow for additional discussion of xml changes.

**Comment by joeljfischer** [comment]
After discussion with Joey, we think a more neutral approach is best with clear documentation on how to apply various parameters to different media types:

```xml
<enum name="MediaType">
  <element name="MUSIC">
  <element name="PODCAST">
  <element name="AUDIOBOOK">
  <element name="OTHER">
</enum>
	  
<struct name="MediaServiceData">
  <param name="mediaType" type="MediaType" mandatory="false">
    <description>The type of the currently playing or paused track.</description>
  </param>
  <param name="mediaTitle" type="String" mandatory="false">
    <description>
      Music: The name of the current track
      Podcast: The name of the current episode
      Audiobook: The name of the current chapter
    </description>
  </param>
  <param name="mediaArtist" type="String" mandatory="false">
    <description>
      Music: The name of the current album artist
      Podcast: The provider of the podcast (hosts, network, company)
      Audiobook: The book author's name
    </description>
  </param>
  <param name="mediaAlbum" type="String" mandatory="false">
    <description>
      Music: The name of the current album
      Podcast: The name of the current podcast show
      Audiobook: The name of the current book
    </description>
  </param>
  <param name="playlistName" type="String" mandatory="false">
    <description>
      Music: The name of the playlist or radio station, if the user is playing from a playlist, otherwise, Null
      Podcast: The name of the playlist, if the user is playing from a playlist, otherwise, Null
      Audiobook: Likely not applicable, possibly a collection or "playlist" of books
    </description>
  </param>
  <param name="isExplicit" type="Bool" mandatory="false">
    <description>
      Whether or not the content currently playing (e.g. the track, episode, or book) contains explicit content
    </description>
  </param>
  <param name="trackPlaybackProgress" type="Int" mandatory="false">
    <description>
      Music: The current progress of the track in seconds
      Podcast: The current progress of the episode in seconds
      Audiobook: The current progress of the current segment (e.g. the chapter) in seconds
    </description>
  </param>
  <param name="trackPlaybackDuration" type="Int" mandatory="false">
    <description>
      Music: The total duration of the track in seconds
      Podcast: The total duration of the episode in seconds
      Audiobook: The total duration of the current segment (e.g. the chapter) in seconds
    </description>
  </param>
  <param name="queuePlaybackProgess" type="Int" mandatory="false">
    <description>
      Music: The current progress of the playback queue in seconds
      Podcast: The current progress of the playback queue in seconds
      Audiobook: The current progress of the playback queue (e.g. the book) in seconds
    </description>
  </param>
  <param name="queuePlaybackDuration" type="Int" mandatory="false">
    <description>
      Music: The total duration of the playback queue in seconds
      Podcast: The total duration of the playback queue in seconds
      Audiobook: The total duration of the playback queue (e.g. the book) in seconds
    </description>
  </param>
  <param name="queueCurrentTrackNumber" type="Int" mandatory="false">
    <description>
      Music: The current number (1 based) of the track in the playback queue
      Podcast: The current number (1 based) of the episode in the playback queue
      Audiobook: The current number (1 based) of the episode in the playback queue (e.g. the chapter number in the book)
    </description>
  </param>
  <param name="queueTotalTrackCount" type="Int" mandatory="false">
    <description>
      Music: The total number of tracks in the playback queue
      Podcast: The total number of episodes in the playback queue
      Audiobook: The total number of sections in the playback queue (e.g. the number of chapters in the book)
    </description>
  </param>
</struct>
```

**Comment by theresalech** [comment]
The Steering Committee voted to accept the Media Service type section of the larger App Services proposal, with the revisions included in [this comment](https://github.com/smartdevicelink/sdl_evolution/issues/557#issuecomment-410051609)

**Comment by theresalech** [comment]
@joeygrover please confirm when the Media Service type section of the App Services proposal has been updated to reflect agreed upon revisions.

**Comment by joeygrover** [comment]
Updates contained in #658.

**Comment by jordynmackool** [comment]
Issues have been entered:
[android](https://github.com/smartdevicelink/sdl_android/issues/970)
[iOS](https://github.com/smartdevicelink/sdl_ios/issues/1148)
[core](https://github.com/smartdevicelink/sdl_core/issues/2806)
[rpc_spec](https://github.com/smartdevicelink/rpc_spec/issues/146)
