### ISSUE TITLE
[Accepted] SDL 0190 - Handle response from HMI during resumption data

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_evolution#562]
Hello SDL community,

The review of "SDL 0190 - Handle response from HMI during resumption data" begins now and runs through July 31, 2018.  The proposal is available here:

https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0190-resumption-data-error-handling.md

Reviews are an important part of the SDL evolution process. All reviews should be sent to the associated Github issue at:

https://github.com/smartdevicelink/sdl_evolution/issues/562

What goes into a review?

The goal of the review process is to improve the proposal under review through constructive criticism and, eventually, determine the direction of SDL. When writing your review, here are some questions you might want to answer in your review:

* Is the problem being addressed significant enough to warrant a change to SDL?
* Does this proposal fit well with the feel and direction of SDL?
* If you have used competitors with a similar feature, how do you feel that this proposal compares to those?
* How much effort did you put into your review? A glance, a quick reading, or an in-depth study?
Please state explicitly whether you believe that the proposal should be accepted into SDL.

More information about the SDL evolution process is available at

https://github.com/smartdevicelink/sdl_evolution/blob/master/process.md

Thank you,
Theresa Lech

Program Manager - Livio
theresa@livio.io

**Comment by joeljfischer** [comment]
I'm a little confused, does Core just simply not handle _any_ errors from HMI at this time?

If so, this appears to be a reasonable approach.

**Comment by LuxoftAKutsan** [comment]
@joeljfischer yes. Now during resumption SDL send al required requests for data restoring, but do not handle responses from HMI.

**Comment by JackLivio** [comment]
> If HMI responds with any kind of error or does not respond to any requests sent during resumption, SDL should revert already restored data with appropriate RPCs:

Is this statement describing the current behavior of Core, or is this statement describing a part that the proposal means to implement?

**Comment by theresalech** [comment]
As the Project Maintainer's questions were answered by the proposal's author, the Steering Committee fully agreed to accept this proposal.

**Comment by theresalech** [comment]
Issue entered: [[SDL 0190] Handle response from HMI during resumption data](https://github.com/smartdevicelink/sdl_core/issues/2486)
