### ISSUE TITLE
[Accepted with Revisions] SDL 0191 - Retry Failed File Uploads

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_evolution#564]
Hello SDL community,

The review of "SDL 0191 - Retry Failed File Uploads" begins now and runs through July 31, 2018.  The proposal is available here:

https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0191-retry-failed-file-uploads.md

Reviews are an important part of the SDL evolution process. All reviews should be sent to the associated Github issue at:

https://github.com/smartdevicelink/sdl_evolution/issues/564

What goes into a review?

The goal of the review process is to improve the proposal under review through constructive criticism and, eventually, determine the direction of SDL. When writing your review, here are some questions you might want to answer in your review:

* Is the problem being addressed significant enough to warrant a change to SDL?
* Does this proposal fit well with the feel and direction of SDL?
* If you have used competitors with a similar feature, how do you feel that this proposal compares to those?
* How much effort did you put into your review? A glance, a quick reading, or an in-depth study?
Please state explicitly whether you believe that the proposal should be accepted into SDL.

More information about the SDL evolution process is available at

https://github.com/smartdevicelink/sdl_evolution/blob/master/process.md

Thank you,
Theresa Lech

Program Manager - Livio
theresa@livio.io

**Comment by joeygrover** [comment]
I believe this same functionality should be added to the Android library as well. As a future improvement on these types of proposals I would encourage to include the other mobile platform as well. This is important if we want to continue to bring the APIs and behavior between the two back together.

**Comment by theresalech** [comment]
The Steering Committee voted to accept this proposal with the following revision: the proposal should be updated to include adding this functionality to the Android library as well.

**Comment by theresalech** [comment]
@NicoleYarroch please advise when a new PR has been entered to update the proposal to reflect the agreed upon revisions. I'll then merge the PR so the proposal is up to date, and enter issues in the respective repositories for implementation. Thanks!

**Comment by theresalech** [comment]
Proposal has been revised, and issues have been entered:
[iOS](https://github.com/smartdevicelink/sdl_ios/issues/1043)
[Android](https://github.com/smartdevicelink/sdl_android/issues/830)
