### ISSUE TITLE
[Accepted] SDL 0194 - Android Transport Layer Overhaul

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_evolution#579]
Hello SDL community,

The review of "SDL 0194 - Android Transport Layer Overhaul" begins now and runs through August 14, 2018.  The proposal is available here:

https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0194-android-transport-overhaul.md

Reviews are an important part of the SDL evolution process. All reviews should be sent to the associated Github issue at:

https://github.com/smartdevicelink/sdl_evolution/issues/579

What goes into a review?

The goal of the review process is to improve the proposal under review through constructive criticism and, eventually, determine the direction of SDL. When writing your review, here are some questions you might want to answer in your review:

* Is the problem being addressed significant enough to warrant a change to SDL?
* Does this proposal fit well with the feel and direction of SDL?
* If you have used competitors with a similar feature, how do you feel that this proposal compares to those?
* How much effort did you put into your review? A glance, a quick reading, or an in-depth study?
Please state explicitly whether you believe that the proposal should be accepted into SDL.

More information about the SDL evolution process is available at

https://github.com/smartdevicelink/sdl_evolution/blob/master/process.md

Thank you,
Theresa Lech

Program Manager - Livio
theresa@livio.io

**Comment by shiniwat** [comment]
While I am looking into recent change to feature/multiplexing_only branch, and trying to understand overall approach mentioned in the proposal, I have a couple of questions:
### Backward compatibility of SDL Proxy
This Transport Layer refactoring involves many changes between SdlRouterService and TransportBroker, and the updated SdlProxyBase requires exactly the same version of SdlRouterService. Assuming SdlRouterService will be always the latest version, how do we support the SDL app that uses older Android Proxy on the device?

### Running with older SDL Core that does not support multiple transports
The proposed solution does not seem to clarify how the Transport Layer will work when running with older SDLCore that does not support simultaneous multiple transports. 
Looks like MultiplexTcpTransport is used only for secondary transport, so it doesn't work with older SDLCore, right? 
MultiplexUsbTransport can be primary transport, and if the app specifies requriesHighBandwidth flag set, the app won't work until MultiplexUsbTransport gets connected when running with older SDLCore, right?

**Comment by joeygrover** [comment]
>and the updated SdlProxyBase requires exactly the same version of SdlRouterService. 

This is not true. Backwards compatibility will always be ensured. I believe there is a little bit more work/code to be done here, but as of right now if an older proxy client connects it doesn't include the transport to use and one will be chosen for it with bluetooth being the prioritized transport as that is what they would expect. 

(Still needs to be coded) Once the client has a session established the transport will be attached to their `RegisteredApp` instance in the router service, after that point, the router service will reference that transport as its primary (and only) transport. 

>The proposed solution does not seem to clarify how the Transport Layer will work when running with older SDLCore that does not support simultaneous multiple transports.

The first section is based solely on single transport connections. Not until the [Simultaneous Transport section](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0194-android-transport-overhaul.md#simultaneous-transport-modifications) does it specifically mention how it will work with multiple transports. Therefore, the proposed solution works with older core implementations. It has been tested with a Ford Gen3 TDK to ensure that an older implementation works and the behavior when switching between transports. 

1. If bluetooth connects, apps will be notified
2. If app can accept bluetooth as a primary transport, it will bind to router service and connect to BT
3. USB connects, PFD is sent to router service and router service connects, apps are notified
4. If session over BT is still active, notification will be ignored. If there is no session active and app can accept USB as primary transport it will bind to router service and connect over USB
5. BT is disconnected, apps are notified of d/c
6. If a session was active over BT it will dispose of that session
7. If a transport is still active that can act as a primary transport (USB in this case), it will attempt to cycle the proxy and reconnect over USB

>Looks like MultiplexTcpTransport is used only for secondary transport, so it doesn't work with older SDLCore, right?

TCP was never a production transport previously to the [Simulations Transport](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0141-multiple-transports.md) proposal so this transport is not required to work with older head units at this time.

The current TCP transport will still work at the moment even though it is deprecated which should be evident from this graphic: 

![New Layers](https://github.com/smartdevicelink/sdl_evolution/blob/master/assets/proposals/NNNN-android-transport-overhaul/TransportOverhaul_bridge.png?raw=true "New transport layers")


>MultiplexUsbTransport can be primary transport, and if the app specifies requriesHighBandwidth flag set, the app won't work until MultiplexUsbTransport gets connected when running with older SDLCore, right?

Correct.

**Comment by theresalech** [comment]
There was not a quorum present at the Steering Committee Meeting on 2018-08-14, so a vote on this proposal was unable to take place.  The review of this issue will extend another week, and the Steering Committee will vote during the 2018-08-21 meeting, pending a quorum is present.

**Comment by shiniwat** [comment]
Thanks for the comments. 
> Backwards compatibility will always be ensured
Regarding compatibility between SdlProxyBase and SdlRouterService, I just wanted make sure if we keep them backward compatible. It's fine if backward compatibility is always ensured. Looks like TransportBroker and SdlPacket is going to take care of Router Messaging Version for backward compatibility.

Regarding my second question, thanks for the answer too.
I was asking this because I think a notification is required when USB transport gets connected. In case of secondary transport (i.e. when running with SDLCore 5.0 or later),  onTransportConnected event will be handled in SdlRouterService, and NAVI and/or AUDIO session will be initiated. However, we still need to notify the event to apps when running with older SDLCore, so that SDL apps can restart the RPC session with different transport. In case of legacy USBTransport, USBTransport.ACTION_USB_ACCESSORY_ATTACHED broadcast event is fired, and I think similar notification is needed for MultiplexUsbTransport as well.

**Comment by joeygrover** [comment]
The router service notifies all connected/bound proxies when any transport connects or disconnects. It also sends the regular `START_ROUTER_SERVICE_ACTION` for apps to be notified that are not currently registered/bound with the router service. Right now the config allows for a requirement of high bandwidth transport which doesn't allow a connection on a transport that can't support video/audio streaming. If it's desired for an app to be able to register over a low bandwidth transport, then reregister over a high bandwidth one when available that could be added. 

For example,:

1.  BT connects nav app registers on module 
2. Displays "Please connect USB" or similar text when it goes into HMI_FULL. 
3. User plugs in USB
4. Router service notifies app via HARDWARE_EVENT message, 
5. App cycles proxy to use USB

If USB is disconnected with BT still available should the app reregister again on BT? This use case introduces a bit more complex logic to maintain, so if it is added I'd like to make sure it's a use case that would be utilized by app partners.

**Comment by shiniwat** [comment]
Well, my second question is based on the case where running with older (< 5.0) SDLCore.
In this case, if requiresHighBandwidth app tries to run RegisterAppInterface on BT transport, it fails, and proxy gets closed. So it cannot get into HMI_NONE state.
In addition, when user plugs in USB, RouterService notifies app via HARDWARE_EVENT message, but it is handled inside of TransportBroker and there is no way for SDL apps to know that event. My previous comment means Transport connection event should be exposed to the app.
Again, they may not be needed if the SDL app runs with SDL Core 5.0, because secondary transport connection will be handled inside of SDL Proxy.

**Comment by joeygrover** [comment]
This case is handled. Per my previous comment:

>  It also sends the regular `START_ROUTER_SERVICE_ACTION` for apps to be notified that are not currently registered/bound with the router service.


1. The high bandwidth app will receive the first BT connection event through the`START_ROUTER_SERVICE_ACTION`  intent
2. It will register to the router service
3. Router service supplies currently connected transports
4. HBA attempts to use BT and sends `StartService`
5. HBA receives `StartServiceACK` if the packet is of version < 5.0.0 and the transport does not support high bandwidth the HBA proxy will close (including unbinding to the router service)
6. User connects the USB cable to module and phone
7. The high bandwidth app will receive the USB connection event through the`START_ROUTER_SERVICE_ACTION`  intent
8. Follows steps 2-5 but remains connected as it is on a high bandwidth transport

**Comment by theresalech** [comment]
It was confirmed in the Steering Committee meeting that questions posed on the review issue were answered by the author in his comments.  The Steering Committee then fully agreed to accept this proposal.

**Comment by theresalech** [comment]
Issue Entered: [[SDL 0194] Android Transport Layer Overhaul](https://github.com/smartdevicelink/sdl_android/issues/841)
