### ISSUE TITLE
[Accepted] SDL 0199- Adding GPS Shift Support

### ISSUE THREAD

**Issue by jordynmackool** [smartdevicelink/sdl_evolution#598]
Hello SDL community,

The review of "SDL 0199- Adding GPS Shift support" begins now and runs through September 25, 2018. The proposal is available here:

https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0199-Adding-GPS-Shift-support.md

Reviews are an important part of the SDL evolution process. All reviews should be sent to the associated Github issue at:

https://github.com/smartdevicelink/sdl_evolution/issues/598

What goes into a review?

The goal of the review process is to improve the proposal under review through constructive criticism and, eventually, determine the direction of SDL. When writing your review, here are some questions you might want to answer in your review:

* Is the problem being addressed significant enough to warrant a change to SDL?
* Does this proposal fit well with the feel and direction of SDL?
* If you have used competitors with a similar feature, how do you feel that this proposal compares to those?
* How much effort did you put into your review? A glance, a quick reading, or an in-depth study?
Please state explicitly whether you believe that the proposal should be accepted into SDL.

More information about the SDL evolution process is available at

https://github.com/smartdevicelink/sdl_evolution/blob/master/process.md

Thank you,
Jordyn Mackool

Program Manager - Livio
jordyn@livio.io

**Comment by joeljfischer** [comment]
I don't have an issue with this change.

**Comment by jordynmackool** [comment]
The Steering Committee fully agreed to accept this proposal on 2018-09-25.

**Comment by jordynmackool** [comment]
Issues have been entered: 
[Core](https://github.com/smartdevicelink/sdl_core/issues/2639)
[iOS](https://github.com/smartdevicelink/sdl_ios/issues/1083)
[Android](https://github.com/smartdevicelink/sdl_android/issues/875)
[sdl_hmi](https://github.com/smartdevicelink/sdl_hmi/issues/124)
[rpc_spec](https://github.com/smartdevicelink/rpc_spec/issues/128)
[manticore](https://github.com/smartdevicelink/manticore/issues/49)
