### ISSUE TITLE
[Accepted with Revisions] SDL 0022 - Reduce RSVP default security

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_evolution#60]
Hello SDL community,

The review of "Reduce RSVP default security" begins now and runs through December 20, 2016. The proposal is available here:

https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0022-android-rsvp-off.md

Reviews are an important part of the SDL evolution process. All reviews should be sent to the associated Github issue at:

https://github.com/smartdevicelink/sdl_evolution/issues/60

What goes into a review?

The goal of the review process is to improve the proposal under review through constructive criticism and, eventually, determine the direction of SDL. When writing your review, here are some questions you might want to answer in your review:

* Is the problem being addressed significant enough to warrant a change to SDL?
* Does this proposal fit well with the feel and direction of SDL?
* If you have used competitors with a similar feature, how do you feel that this proposal compares to those?
* How much effort did you put into your review? A glance, a quick reading, or an in-depth study?
Please state explicitly whether you believe that the proposal should be accepted into SDL.

More information about the SDL evolution process is available at

https://github.com/smartdevicelink/sdl_evolution/blob/master/process.md

Thank you,
Theresa Lech

Program Manager - Livio
theresa@livio.io

**Comment by ssmereka** [comment]
Agree that this is a good idea.  To put some numbers to it, one application calling the RSVP server generates about 23.1 million requests per day.  It's easy to see this could get expensive to run if not limited.

**Comment by Toyota-Sbetts** [comment]
While we understand the need to reduce the volume of requests incoming to the RSVP server, we have a few concerns regarding the current proposal:

1. "FLAG_MULTI_SECURITY_OFF" should not be the default and maybe should be reserved for DEBUG mode only (similar to current implementation).  We're concerned that any production app using the "OFF" flag could be intercepted by an incorrectly implemented or malicious router.  Any app that incorrectly broadcasts it's router service would be accepted and any app that connects to that router service will be denied to the connected router service.  We think this would allow for any applications (approved or not) to possibly block app connections to both legacy and multiplexing enabled embedded systems.

2. The frequency of updating the trusted router list should be considered more thoroughly.  If our approved router is somehow compromised and we must change our router and update the trusted router list, it's possible for users to be unable to connect to our new router until after the allotted time.  We can't tell our customers to wait up to 30 or even 7 days before apps will start working again.

3. Is the "trusted app store" check worth doing?  We already know this can be spoofed and anyone side-loading an app can probably figure out how to spoof this check.

**Comment by joeygrover** [comment]
The main goal here is to reduce the burden on the server. Every app has to obtain a list so that creates a lot of hits on the server and will get very expensive to the SLDC. 

The list should update if the user installs/uninstalls/updates any of the SDL enabled apps. So if the user updated to the fixed app, the list would be obtained. I have to double check it happens regardless of the threshold of 30 or 7 days, if not it easily could be made to.

The app store check is not for users side loading apps, they do that at their own risks.

**Comment by Toyota-Sbetts** [comment]
@joeygrover - Thanks for the feedback Joey!  I'm sorry for bringing these concerns late in the review process.  We understand the main goal, but we're concerned that the current proposal as is produces too much risk.

> So if the user updated to the fixed app, the list would be obtained

Only for the updated app, correct?  What if the app acting as router is updated?  Our understanding is none of the other apps will be updated and will only update the trusted router list on their cadence.  This means none of the other SDL apps will trust the new router until their current list expires.  If none of the other SDL apps are in the trusted list or an OEM implementation only allows for their app to act as router, then all other SDL apps will be unavailable until they update their list.  Please let us know if this understanding isn't correct.

> The app store check is not for users side loading apps, they do that at their own risks.

Perhaps we can discuss this in the meeting, but what is the app store check for then?  What additional security does it provide for app developers, OEMs, or others?

**Comment by joeygrover** [comment]
Each app will update their list when any of the other SDL enabled apps are updated/installed/uninstalled. The RSVP class sends a list of installed SDL enabled apps along with their respective versions to the wopr.jr server so that the server only responds with a list of relevant trusted router services. Therefore, the RSVP class caches the last request body it used to obtain the last list to compare against to see if anything has changed and if it has, request a new list.

**Comment by mrapitis** [comment]
The tiered solution makes sense and will likely reduce server burden.  Taking Sbetts comments into account, it may safer to default to security on vs off so that the developer is making a conscious decision when selecting a lower tier.

**Comment by theresalech** [comment]
This proposal has been accepted with revisions.  The steering committee has agreed that default security will need to be set to at least medium and ensure that when an app is installed, uninstalled and/or updated, the next time any of the SDL enabled apps connect to a car they will each obtain a new list regardless of the set retrieval interval.
