### ISSUE TITLE
SDL 0203- Cloud App Library - Phase 1

### ISSUE THREAD

**Issue by jordynmackool** [smartdevicelink/sdl_evolution#617]
Hello SDL community,

The review of "SDL 0203- Cloud App Library - Phase 1" begins now and runs through November 20, 2018. The proposal is available here:

https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0203-cloud_client_library_phase_1.md

Reviews are an important part of the SDL evolution process. All reviews should be sent to the associated Github issue at:

https://github.com/smartdevicelink/sdl_evolution/issues/617

What goes into a review?

The goal of the review process is to improve the proposal under review through constructive criticism and, eventually, determine the direction of SDL. When writing your review, here are some questions you might want to answer in your review:

* Is the problem being addressed significant enough to warrant a change to SDL?
* Does this proposal fit well with the feel and direction of SDL?
* If you have used competitors with a similar feature, how do you feel that this proposal compares to those?
* How much effort did you put into your review? A glance, a quick reading, or an in-depth study?
Please state explicitly whether you believe that the proposal should be accepted into SDL.

More information about the SDL evolution process is available at

https://github.com/smartdevicelink/sdl_evolution/blob/master/process.md

Thank you,
Jordyn Mackool

Program Manager - Livio
jordyn@livio.io

**Comment by kshala-ford** [comment]
I read the proposal with interest and do agree in having a java_common library reused for other purposes. This will open the gate to reuse code for other platforms than Android. 

I'm curious about [Phase 2 intentions](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0203-cloud_client_library_phase_1.md#phase-2-intentions) though you mention it's not part of this proposal. When speaking about javascript and node.js are you saying to "write a pure javascript library" or a "node library with bridge to java_common"?

I do struggle with the subsection [SDL Cloud as embedded app](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0203-cloud_client_library_phase_1.md#sdl-cloud-as-embedded-app). First of all I would expect a sdl_java_embedded library that uses the sdl_java_common library (just as sdl_android or sdl_java_cloud will use sdl_java_common). Because Oracle charges for Java it'll be an extra pricetag to the head unit. I get the point in moving the app's logic closer to the actual user to make the app more responsive. Also I don't think java should be only programming language supported for embedded but this will result into the need for OEMs to support all of them. I don't believe every OEM decides to add Java support and with more languages for embedded this could get worse. If java and javascript are candidates for embedded I believe OEMs might not consider to support both. This will affect attractiveness to app developers.

**Comment by joeygrover** [comment]
I would say phase 2 is to create a brand new library in another language and framework. The provided information was simply as an example. I was just suggesting that phase 1 would allow us to have a phase 2 and not increase our maintenance burden substionaly for support two completely different frameworks/languages. 

I don't think there's much to build on top of the common library for the embedded library, but easily added if necessary. I am not 100% but I believe Java 7 is currently still under the previous licensing model, and 8 & 9 being the same way except for no updates. While these versions are older, we're actually limited based on the Android platform on which version we can use. (We currently use Java 7). 

I'm struggling to find the suggestion/issue with your last comment. We should only support one language/platform? So we should consider only Java, Javascript or a different language? The way I see using Java is that the difference between an app's cloud and embedded integration will be very minimal and allows them to support both fairly easily while also reducing our maintenance burden. There are few other languages/platforms that would offer the same advantage. Web technologies tend to be extremely transient so I'm hesitant to put all efforts into a singular framework that could be unsupported in a couple years. Also, most embedded languages/frameworks don't translate well into cloud technologies or app companies will not have expertise in them to be able to support them.

**Comment by justinjdickow** [comment]
The "SDL Cloud as separate endpoint" seems to be the most practical approach.

If the SDL Cloud Application is provided as a service (or a server that an OEM can control) with web hooks then developers can just implement REST APIs using whatever frameworks they choose.

**Comment by joeygrover** [comment]
@justinjdickow Agreed. In my opinion, it allows the SDL integration to be separated from the main logic and can be secured by the normal REST API of the app. I think each situation will be different so it's important to allow for all types of integration and using Java does allow this so our solution shouldn't limit how a developer can use it.

@kshala-ford The common library will work on embedded devices by default, what additional items do you want to see in the embedded extension? That's my question. You are requesting a specific embedded library but I'd like to know what you see in it that isn't included in the common base?

### Java version

We will use Java 7 as we are limited by Android.

### Licensing issues:

>Second if the license changes (and it's totally realistic) forcing OEMs to remove Java embedded apps support would be a nightmare for this feature.

This is true about any language or framework so I don't believe it can be used for or against a specific language/framework.
 
 - [Oracle FAQ](https://www.oracle.com/technetwork/java/javase/overview/faqs-jsp-136696.html)
- [Oracle Subscription Model](https://www.oracle.com/technetwork/java/javaseproducts/overview/javasesubscriptionfaq-4891443.html)

Excerpts:

#### Is Java still free?
>The current version of Java - Java SE 11 is available from Oracle under an open source license at http://jdk.java.net/11/. Java SE 8 remains free of charge for general purpose desktop and server use and is available under the Oracle Binary Code License (BCL) at https://www.oracle.com/javadownload.

#### Where can I get information on licensing?
>Java SE releases prior to JDK 11 are available under the Binary Code License (BCL) with no additional cost for its use. Starting with JDK 11 Oracle offers Java SE binaries under either the Oracle Java SE OTN License or under GPL license (as described below). Java SE commercial binaries are provided under separate but similar licensing terms. Product License and Terms, Read Me files and more are available on the Oracle Technology Network. 
>
>Starting with Java SE 9 Oracle also offers OpenJDK binaries under the GNU General Public License (GPL) for users who want the latest Java SE version and do not require long term support.


### Different frameworks

I agree that limiting the exposure to platforms is important from an app developer perspective, so I will ask again, can you suggest an alternative that could be considered to what's laid out in the proposal?

**Comment by jordynmackool** [comment]
The Steering Committee fully agreed to accept this proposal on 2018-11-21.

**Comment by theresalech** [comment]
Implemented via https://github.com/smartdevicelink/sdl_android/pull/983
