### ISSUE TITLE
SDL 0205 - Avoid Custom button subscription in case HMI incompatibility

### ISSUE THREAD

**Issue by jordynmackool** [smartdevicelink/sdl_evolution#632]
Hello SDL community,

The review of "SDL 0205 - Avoid Custom button subscription in case HMI incompatibility" begins now and runs through December 11, 2018. The proposal is available here:

https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0205-Avoid_custom_button_subscription_when_HMI_does_not_support.md

Reviews are an important part of the SDL evolution process. All reviews should be sent to the associated Github issue at:

https://github.com/smartdevicelink/sdl_evolution/issues/632

What goes into a review?

The goal of the review process is to improve the proposal under review through constructive criticism and, eventually, determine the direction of SDL. When writing your review, here are some questions you might want to answer in your review:

* Is the problem being addressed significant enough to warrant a change to SDL?
* Does this proposal fit well with the feel and direction of SDL?
* If you have used competitors with a similar feature, how do you feel that this proposal compares to those?
* How much effort did you put into your review? A glance, a quick reading, or an in-depth study?
Please state explicitly whether you believe that the proposal should be accepted into SDL.

More information about the SDL evolution process is available at

https://github.com/smartdevicelink/sdl_evolution/blob/master/process.md

Thank you,
Jordyn Mackool

Program Manager - Livio
jordyn@livio.io

**Comment by kshala-ford** [comment]
To my understanding it reduces the overhead of unneeded calls to HMI if `CUSTOM_BUTTON` is not supported. I do have one question:

> In case CUSTOM_BUTTON is not supported by hmi_capabilities: SDL should not send Buttons.SubscribeButtons(CUSTOM_BUTTON) to HMI.

I was looking for this function in the HMI_API and couldn't find it. I'm not an expert in HMI API. Can you please clarify what HMI function this should be?

I believe this proposal is about button subscription from the app through SDL core to the HMI. If SDL should not send the request to the HMI who's then responding back to the app? May be I'm completely wrong here but I want to ensure requests always receive a response.

**Comment by GetmanetsIrina** [comment]
@kshala-ford , currently on SDL develop branch the button subscription on SDL triggers not the Buttons.SubscribeButtons message to HMI, but the Buttons.OnButtonSubscription notification.
Changes of the SDL subscription were provided in https://github.com/smartdevicelink/sdl_evolution/issues/568, so within these changes SDL will send Buttons.SubscribeButtons request.

**Comment by JackLivio** [comment]
@GetmanetsIrina 

> In case CUSTOM_BUTTON is not supported by hmi_capabilities: SDL should not send Buttons.SubscribeButtons(CUSTOM_BUTTON) to HMI.

How would core respond to the mobile proxy in this event?

**Comment by LuxoftAKutsan** [comment]
@JackLivio  SDL should successfully response (on RAI) to mobile in any case. HMI limitations should not cause errors during registration.

**Comment by JackLivio** [comment]
What would be the response to ButtonSubscription? `UNSUPPORTED_RESOURCE`?

**Comment by LuxoftAKutsan** [comment]
@JackLivio  if mobile application send `SubscribeButton (buttonName = CUSTOM_BUTTON)` and CUSTOM_BUTTON is not supported by HMI (absent in hmi_capabilities), SDL will respond with  `UNSUPPORTED_RESOURCE` result code.

**Comment by jordynmackool** [comment]
The Steering Committee voted to accepted this proposal with the revision on 2018-12-11. The revisions will include adding UNSUPPORTED_RESOURCE response in the event that a CUSTOM_BUTTON is not supported as noted in [this comment](https://github.com/smartdevicelink/sdl_evolution/issues/632#issuecomment-446365125).
