### ISSUE TITLE
SDL 0208 - Block Old SDL Head Units from Mobile

### ISSUE THREAD

**Issue by jordynmackool** [smartdevicelink/sdl_evolution#635]
Hello SDL community,

The review of "SDL 0208 - Block Old SDL Head Units from Mobile" begins now and runs through December 11, 2018. The proposal is available here:

https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0208-block-sdl-head-units.md

Reviews are an important part of the SDL evolution process. All reviews should be sent to the associated Github issue at:

https://github.com/smartdevicelink/sdl_evolution/issues/635

What goes into a review?

The goal of the review process is to improve the proposal under review through constructive criticism and, eventually, determine the direction of SDL. When writing your review, here are some questions you might want to answer in your review:

* Is the problem being addressed significant enough to warrant a change to SDL?
* Does this proposal fit well with the feel and direction of SDL?
* If you have used competitors with a similar feature, how do you feel that this proposal compares to those?
* How much effort did you put into your review? A glance, a quick reading, or an in-depth study?
Please state explicitly whether you believe that the proposal should be accepted into SDL.

More information about the SDL evolution process is available at

https://github.com/smartdevicelink/sdl_evolution/blob/master/process.md

Thank you,
Jordyn Mackool

Program Manager - Livio
jordyn@livio.io

**Comment by shoamano83** [comment]
Out of curiosity, is it a really good idea to make an app not showing on old HU? A user doesn't (and most likely cannot) know SDL version of the HU. It may be confusing when he/she connects a phone with SDL-capable HU, and some apps are shown on HU while others don't.

I don't have strong opinion though, probably an app can be still launched on an old HU, emitting a message like "this app isn't compatible with the HU" and stops working?

**Comment by joeygrover** [comment]
@shoamano83 I believe apps could still create such an integration for older, unsupported head units, however, I don't believe it should be that much of a burden on them if they don't wish to support the older hardware; it would require them to be able to test that integration against older hardware/software and that could be difficult. I do agree it could be confusing to a user, but that's the app's experience and they should be allowed to define it.

I think we could add onto this in the future to an additional config to allow the library to connect to the unsupported hardware/software and push a message similar to what you mentioned to the screen.

**Comment by kshala-ford** [comment]
Could we use 
- NSUInteger for protocol version. I'm more in favor of a integer integer and not short variants. That just causes warnings with casting values.
- `SDLMessageVersion` or `SdlMsgVersion` for RPC version? I see this as mandatory. Do not use string for blocking apps out of the system! It'll be a testing nightmare with app developers making mistakes with the version string.

I'm thinking of having a new `RAI` parameter like `minimumMessageVersion`. Though it would affect more platforms (RPC and Core) it'll avoid app to flicker on the HMI. Also it's only a minor version change :+1: See XML below:

```xml
 <function name="RegisterAppInterface" functionID="RegisterAppInterfaceID" messagetype="request" since="1.0">
  <param name="minimumMsgVersion" type="SyncMsgVersion" mandatory="false" since="5.1">
    <description>If supported by IVI your app registration request will be rejected if the IVI msg version is lower than the app's minimum msg version.</description>
  </param>
</function>
```

**Comment by joeljfischer** [comment]
1. After further looking into it, I think it should be a string. We do now technically use minor versions. I'm sure you will argue in favor of what you do in your second bullet, but we already do our comparisons via strings since it's passed as a string in the protocol control packets. See SDLGlobals.m for more details.
2. I disagree. It's easier for developers to understand, and they will just be given the string to add from an OEM. Additionally, we will just assert in the library if they do it improperly and it can't be parsed. No testing nightmare necessary.

For your alternative solution, it unfortunately won't work. If we added that new parameter, no older head unit would support it, so we could only block future new head units, and that defeats the purpose of this proposal.

Regarding your appendix, I see no reason why the current proposal would interfere with that, do you?

**Comment by jordynmackool** [comment]
The Steering Committee voted to accepted this proposal with the revision on 2018-12-11.  The author will alter the proposal to have the protocol and RPC versions changed to be version objects like the Android native version object.

**Comment by jordynmackool** [comment]
Revisions were made and issues have been entered:
[ios](https://github.com/smartdevicelink/sdl_ios/issues/1142)
[android](https://github.com/smartdevicelink/sdl_android/issues/955)
