### ISSUE TITLE
SDL 0211 - Service Status Update to HMI

### ISSUE THREAD

**Issue by jordynmackool** [smartdevicelink/sdl_evolution#641]
Hello SDL community,

The review of "SDL 0211 - Service Status Update to HMI" begins now and runs through December 18, 2018. The proposal is available here:

https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0211-ServiceStatusUpdateToHMI.md

Reviews are an important part of the SDL evolution process. All reviews should be sent to the associated Github issue at:

https://github.com/smartdevicelink/sdl_evolution/issues/641

What goes into a review?

The goal of the review process is to improve the proposal under review through constructive criticism and, eventually, determine the direction of SDL. When writing your review, here are some questions you might want to answer in your review:

* Is the problem being addressed significant enough to warrant a change to SDL?
* Does this proposal fit well with the feel and direction of SDL?
* If you have used competitors with a similar feature, how do you feel that this proposal compares to those?
* How much effort did you put into your review? A glance, a quick reading, or an in-depth study?
Please state explicitly whether you believe that the proposal should be accepted into SDL.

More information about the SDL evolution process is available at

https://github.com/smartdevicelink/sdl_evolution/blob/master/process.md

Thank you,
Jordyn Mackool

Program Manager - Livio
jordyn@livio.io

**Comment by joeljfischer** [comment]
First of all, I think this is a wonderful improvement that is sorely needed.

Question:
* I think the new `Common.ServiceType` should include more than the `Video` service, especially since we are discussing adding encryption to other services such as the RPC service.

**Comment by robinmk** [comment]
This is a good point. We can add both the Audio and RPC service as well. The flow would remain the same.

**Comment by robinmk** [comment]
We should also add an optional 'appID' parameter to the `OnServiceUpdate` RPC. This would help the HMI map the updates to a particular app.

```xml
<function name="OnServiceUpdate" messagetype="notification">
  <description>
    Must be sent by SDL to HMI when there is an update on status of certain services.
  </description>
  <param name="serviceType" type="Common.ServiceType" mandatory="true">
    <description>Specifies the service which has been updated.</description>
  </param>
  <param name="serviceEvent" type="Common.ServiceEvent" mandatory="false">
    <description>Specifies service update event.</description>
  </param>
  <param name="reason" type="Common.ServiceUpdateReason" mandatory="false">
    <description>
      The reason for a service event. Certain events may not have a reason, such as when a service is ACCEPTED (which is the normal expected behavior).
    </description>
  </param>
  <param name="appID" type="Integer" mandatory="false">
      <description>ID of the application which triggered the update.</description>
  </param>
</function>
```

Note that the only time when SDL would not be able provide the appID would be during the first StartService request for the RPC service before RAI was sent.

**Comment by jordynmackool** [comment]
The Steering Committee voted to accept this proposal with revisions on 2018-12-18. The author is to update the proposal to include both the Audio and RPC services discussed in [this comment](https://github.com/smartdevicelink/sdl_evolution/issues/641#issuecomment-447112795) and adding an optional 'appID' parameter to the OnServiceUpdate RPC as noted in t[his comment](https://github.com/smartdevicelink/sdl_evolution/issues/641#issuecomment-448337280).

**Comment by jordynmackool** [comment]
Revisions were made and issues have been entered:
[core](https://github.com/smartdevicelink/sdl_core/issues/2791)
[rpc_spec](https://github.com/smartdevicelink/rpc_spec/issues/143)
[iOS](https://github.com/smartdevicelink/sdl_ios/issues/1141)
[android](https://github.com/smartdevicelink/sdl_android/issues/953)

**Comment by theresalech** [comment]
It was determined updates to `rpc_spec`, `ios`, and `android` are not required for this feature, as it only makes changes to the hmi_api.

**Comment by theresalech** [comment]
Issue entered for sdl_hmi: https://github.com/smartdevicelink/sdl_hmi/issues/186
