### ISSUE TITLE
SDL 0212 - Add Ability to Reuse a SyncFileName for a PutFile

### ISSUE THREAD

**Issue by jordynmackool** [smartdevicelink/sdl_evolution#642]
Hello SDL community,

The review of "SDL 0212 - Add Ability to Reuse a SyncFileName for a PutFile" begins now and runs through December 18, 2018. The proposal is available here:

https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0212-add-ability-to-reuse-a-syncfilename-for-a-putfile.md

Reviews are an important part of the SDL evolution process. All reviews should be sent to the associated Github issue at:

https://github.com/smartdevicelink/sdl_evolution/issues/642

What goes into a review?

The goal of the review process is to improve the proposal under review through constructive criticism and, eventually, determine the direction of SDL. When writing your review, here are some questions you might want to answer in your review:

* Is the problem being addressed significant enough to warrant a change to SDL?
* Does this proposal fit well with the feel and direction of SDL?
* If you have used competitors with a similar feature, how do you feel that this proposal compares to those?
* How much effort did you put into your review? A glance, a quick reading, or an in-depth study?
Please state explicitly whether you believe that the proposal should be accepted into SDL.

More information about the SDL evolution process is available at

https://github.com/smartdevicelink/sdl_evolution/blob/master/process.md

Thank you,
Jordyn Mackool

Program Manager - Livio
jordyn@livio.io

**Comment by joeljfischer** [comment]
Should another parameter be added with the name of the updated file?

**Comment by mrapitis** [comment]
Will this proposal allow the HMI to be notified whenever a putfile is pushed to the system? This is as opposed to the current design of only notifying the HMI for a system file as seen in the code linked below?
https://github.com/smartdevicelink/sdl_core/blob/d36316738785c96dab2ee892762ed08c059fffde/src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/put_file_request.cc#L287

If so, this would be a welcomed addition and will go hand in hand with the previously accepted proposal here: 
https://github.com/smartdevicelink/sdl_evolution/issues/128
Sending a PutFile notification to the HMI regardless of type (system or not) will provide the HMI with the opportunity to post processing graphics for commands that leverage them like Shows, Alerts, etc.

**Comment by NicoleYarroch** [comment]
@mrapitis Yes, the proposal will allow the HMI to be notified whenever a `PutFile` is pushed to the system.

**Comment by NicoleYarroch** [comment]
@JackLivio Is there any concern that sending a `onPutFile` notification where the `syncFileName` is the same but the image data has not changed will cause flickering, or is the image cached until another RPC using the image is sent?

**Comment by JackLivio** [comment]
@NicoleYarroch It depends on when and how the HMI renders images. I think both Sync and the Generic HMI in a browser cache the image data so it won't flicker in this case. Also onPutfFile shouldn't really be sent if the syncFileName and image data is unchanged?

**Comment by jordynmackool** [comment]
The Steering Committee voted to accept this proposal with revisions on 2018-12-18. The author is to updated this proposal to include an additional parameter name of the updated file to the HMI notification as called out in [this comment](https://github.com/smartdevicelink/sdl_evolution/issues/642#issuecomment-447108125).

**Comment by jordynmackool** [comment]
The accepted revisions were made on 2019-01-17. An issue has been entered:

[core](https://github.com/smartdevicelink/sdl_core/issues/2799)

**Comment by theresalech** [comment]
[sdl_hmi issue](https://github.com/smartdevicelink/sdl_hmi/issues/195)
