### ISSUE TITLE
SDL 0214 - Secondary Transport Optimization

### ISSUE THREAD

**Issue by jordynmackool** [smartdevicelink/sdl_evolution#652]
Hello SDL community,

The review of "SDL 0214 - Secondary Transport Optimization" begins now and runs through January 15, 2019. The proposal is available here:

https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0214-secondary-transport-optimization.md

Reviews are an important part of the SDL evolution process. All reviews should be sent to the associated Github issue at:

https://github.com/smartdevicelink/sdl_evolution/issues/652

What goes into a review?

The goal of the review process is to improve the proposal under review through constructive criticism and, eventually, determine the direction of SDL. When writing your review, here are some questions you might want to answer in your review:

* Is the problem being addressed significant enough to warrant a change to SDL?
* Does this proposal fit well with the feel and direction of SDL?
* If you have used competitors with a similar feature, how do you feel that this proposal compares to those?
* How much effort did you put into your review? A glance, a quick reading, or an in-depth study?
Please state explicitly whether you believe that the proposal should be accepted into SDL.

More information about the SDL evolution process is available at

https://github.com/smartdevicelink/sdl_evolution/blob/master/process.md

Thank you,
Jordyn Mackool

**Comment by JackLivio** [comment]
@joeygrover Would this require a new protocol version?

**Comment by NicoleYarroch** [comment]
> App wishes to start either the video or audio service

Does this happens the first time the `hmiLevel` is `FULL` or is it in any non-`NONE` `hmiLevel`?

**Comment by joeygrover** [comment]
The service is opened on first HMI_FULL. Otherwise the app has not been interacted with yet and therefore shouldn't use additional resources until then. The stream itself can pause between hmi states. However, in iOS's case does it stop the service moving from HMI_FULL or HMI_LIMITED?

**Comment by NicoleYarroch** [comment]
In the iOS library it appears that the TCP transport is disconnected when the app on the device is backgrounded and re-established when the app is foregrounded. It does not look like the TCP transport is disconnected when the `hmiLevel` changes to `LIMITED`, `NONE` or  `BACKGROUND` from `FULL` .

**Comment by joeygrover** [comment]
So essentially after the two conditionals of first HMI_FULL and app in foreground are met, a flag to open and reopen the TCP transport should be set, which would then in turn start the video and/or audio service.

**Comment by NicoleYarroch** [comment]
Sounds good. Should the TCP transport be disconnect every time the `hmiLevel` changes from `FULL` to another `hmiLevel` or should it just be left open?

**Comment by jordynmackool** [comment]
The Steering Committee voted to fully accept this proposal on 2019-01-15. Issues have been entered: 
[core](https://github.com/smartdevicelink/sdl_core/issues/2797)
[ios](https://github.com/smartdevicelink/sdl_ios/issues/1145)
[Android](https://github.com/smartdevicelink/sdl_android/issues/967)
