### ISSUE TITLE
Revisions to 0167-app-services 

### ISSUE THREAD

**Issue by jordynmackool** [smartdevicelink/sdl_evolution#675]
Hello SDL community,

The original proposal "SDL 0167 - App Services" was accepted by the Steering Committee on 2018-05-23, alterations to the proposal have been requested through a pull request.

This review will focus on only the changes present in this pull request "Revisions to 0167-app-services #673" begins now and runs through February 12, 2019.

**Note: All comments should be contained in this issue!**

The original proposal is available here:

https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0167-app-services.md

**Noted Revisions**

- Fix various typos and unify naming conventions.
- Make AppServiceType a documentation item and change all uses of the AppServiceType to String. This will allow for support of future app services that core does not recognize.
- Add notes regarding system capability updates.
- Change serviceIcon type to Image.
- Change uriScheme to type String.
- Change handledRPCs type to Integer. Change is for similar reasons that appServiceType should be sent as a String. Also handledRPCs as an integer will allow for better integration with policies.
- Defined functionIDs for new RPCs.
- Remove servicesSupported from AppServicesCapabilities. The available serviceTypes can be found in the appServices parameter. appServices -> updatedAppServiceRecord -> serviceManifest -> serviceType.
- Remove configuration for supportedAppServices in the ini file. Proposal states that core should be able to handle future unknown service types with conflicts with defining service types in core’s static ini file.
- Define policy table structure.

Reviews are an important part of the SDL evolution process. All reviews should be sent to the associated Github issue at:

#675

What goes into a review?

The goal of the review process is to improve the proposal under review through constructive criticism and, eventually, determine the direction of SDL. When writing your review, here are some questions you might want to answer in your review:

* Is the problem being addressed significant enough to warrant a change to SDL?
* Does this proposal fit well with the feel and direction of SDL?
* If you have used competitors with a similar feature, how do you feel that this proposal compares to those?
* How much effort did you put into your review? A glance, a quick reading, or an in-depth study?
  Please state explicitly whether you believe that the proposal should be accepted into SDL.

More information about the SDL evolution process is available at

https://github.com/smartdevicelink/sdl_evolution/blob/master/process.md

Thank you,
Jordyn Mackool

**Comment by jacobkeeler** [comment]
A few potential additional revisions:
1. Remove the `defvalue` from `AppServiceActivation.setAsDefault`, since that would imply that the service is unset from the default if the parameter is omitted.
2. Remove the `serviceType` from `AppServiceActivation`, since it would seem that Core could infer this from the `serviceID` (correct me if I'm misunderstanding this)

**Comment by joeygrover** [comment]
```
<param name="serviceType" type="String" mandatory="true">
    <description>The type of service that is to be offered by this app. See AppServiceType</description>
</param>
```

I think we should add a little bit more to the description here, just so it's very clear that values should only be from the `AppServiceType` enum, but for validation purposes will be sent as strings to allow Core to handle future services that it doesn't have enum values for.

This actually applies to all usages of String as replacement for `AppServiceType`; a more detailed description should be added. 

```
<param name="handledRPCs" type="Integer" array="true" mandatory="false">
    <description> This field contains the Function IDs for the RPCs that this service intends to handle correctly. This means the service will provide meaningful responses. See FunctionID.</description>
</param>
```

Similar comment for this as well.  

>Note: A published app services can change the capabilities of other systemCapabilityType(s) and trigger a corresponding onSystemCapabilityUpdated for that type. For example, an app that publishes a navigation service on a head unit that does not support navigation will send onSystemCapabilityUpdated notifications to apps that are subscribed to systemCapabilityTypes NAVIGATION and/or APP_SERVICES.

I would change the second sentence to: `For example, an app that publishes a navigation service on a head unit that does not have a native navigation solution will send [...]` 

```
<param name="appServiceCapability" type="AppServicesCapabilities" mandatory="false"/>
```

I'm not a fan of this name change. While it is in line with the other capabilities, the naming and type differ. There is a struct named `AppServiceCapability` while this param with the name `appServiceCapability` is actually a type `AppServicesCapabilities`. If we rename this param I think we should consider more intuitive naming to the structs as well.

**Comment by JackLivio** [comment]
Possible Description Updates

```
<param name="serviceType" type="String" mandatory="true">
    <description>The type of service that is to be offered by this app. See AppServiceType for known enum equivalent types. Parameter is a string to allow for new service types to be used by apps on older versions of SDL Core.</description>
</param>
```

```
<param name="handledRPCs" type="Integer" array="true" mandatory="false">
    <description> This field contains the Function IDs for the RPCs that this service intends to handle correctly. This means the service will provide meaningful responses. See FunctionID for enum equivalent values. This parameter is an integer to allow for new function IDs to be used by apps on older versions of SDL Core.</description>
</param>
```

> I would change the second sentence to: `For example, an app that publishes a navigation service on a head unit that does not have a native navigation solution will send [...]`

Ok.

> I'm not a fan of this name change.

Ok. I woudlnt be opposed to leaving it to how it was in the original proposal. Alternate naming could be.

```
<struct name="SystemCapability">
	...
	<param name="appServicesCapability" type="AppServicesCapability" mandatory="false"/>
</struct>

<struct name="AppServicesCapability">
	<description> Capabilities of app services including what service types are supported and the current state of services. </description>
   	<param name="appServiceRecordCapability" type="AppServiceRecordCapability" array="true" mandatory="false">
   	    <description> An array of currently available services. If this is an update to the capability the affected services will include an update reason in that item</description>
   	</param>
</struct>

<struct name="AppServiceRecordCapability">
   	<param name="updateReason" type="ServiceUpdateReason" mandatory="false">
   	    <description>Only included in OnSystemCapbilityUpdated. Update reason for this service record.</description>
   	</param>
   	<param name="updatedAppServiceRecord" type="AppServiceRecord" mandatory="true">
   	    <description>Service record for a specific app service provider</description>
   	</param>
</struct>

```

Main change there is renaming AppServiceCapability -> AppServiceRecordCapability since the struct really only has information related to the service record.

**Comment by jordynmackool** [comment]
The Steering Committee voted to accept this proposal with revisions. The author is to revert the change of renaming `AppServiceCapability` params in the `SystemCapability` struct to align with how the proposal was originally accepted.
- It was also noted that the only AppServiceTypes that will be included in the Q1 releases are `MEDIA`, `WEATHER` and `NAVIGATION`.
- ` The VOICE_ASSISTANT service data should be removed from the main proposal and put into a new section titled “Amendments” in the proposal with a note that it was removed from the first proposal.
-  GENERIC, COMMUNICATION_VOIP, MESSAGING and TTS should be removed from this proposal as they will not be implemented in this iteration. When these specific AppServiceTypes are to be added, they will need to be submitted in separate proposals and voted on.
