### ISSUE TITLE
Revise SDL-0189 to remove UI/TTS OnResetTimeout and remove range for requested

### ISSUE THREAD

**Issue by jordynmackool** [smartdevicelink/sdl_evolution#688]
Hello SDL community,

The original proposal "SDL 0189 - Restructuring OnResetTimeout" was accepted by the Steering Committee on 2018-07-26, alterations to the proposal have been requested through a pull request.

This review will focus on only the changes present in this pull request: "[Revise SDL-0189 to remove UI/TTS OnResetTimeout and remove range for requested #682](https://github.com/smartdevicelink/sdl_evolution/pull/682) " 

The review for this PR begins now and runs through March 05, 2019.

**Note: All comments should be contained in this issue!**

The original proposal is available here:

https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0189-Restructuring-OnResetTimeout.md

Reviews are an important part of the SDL evolution process. All reviews should be sent to the associated Github issue at:

#688

What goes into a review?

The goal of the review process is to improve the proposal under review through constructive criticism and, eventually, determine the direction of SDL. When writing your review, here are some questions you might want to answer in your review:

* Is the problem being addressed significant enough to warrant a change to SDL?
* Does this proposal fit well with the feel and direction of SDL?
* If you have used competitors with a similar feature, how do you feel that this proposal compares to those?
* How much effort did you put into your review? A glance, a quick reading, or an in-depth study?
  Please state explicitly whether you believe that the proposal should be accepted into SDL.

More information about the SDL evolution process is available at

https://github.com/smartdevicelink/sdl_evolution/blob/master/process.md

Thank you,
Jordyn Mackool

**Comment by jordynmackool** [comment]
For ease of understanding, here is the new SDL-0189 Restructuring OnResetTimeout Proposal to remove UI/TTS OnResetTimeout and remove range for requested:

# Revise SDL-0189 to remove UI/TTS OnResetTimeout and remove range for requested

* Altered Proposal: [SDL-0189](0189-Restructuring-OnResetTimeout.md)
* Author: [Ankur Tiwari](https://github.com/ATIWARI9)
* Status: **In Review**
* Impacted Platforms: [Core / RPC]

## Introduction

It was noted in [this](https://github.com/smartdevicelink/sdl_evolution/issues/556#issuecomment-407786014) comment that:
> Lastly, it was noted that details of deprecating an HMI API will be determined upon implementation.

But while trying to implement this proposal it was brought to attention that _keywords "since" and "deprecated" are introduced  to mobile API only, not applicable to HMI API"_.

Also, _requestID_ param needs update as during implementation it is found that _requestID_ (same as correlation_id) is 32 bit unsigned integer.

## Motivation

We need to update the API as per proposed implementation for _OnResetTimeout_


## Proposed solution

* To remove _UI/TTS_ _OnResetTimeout_ from _HMI_API_ as it has already been noted that older HMI implementations would not work with this change.
* To remove range from _requestID_ param so that it conforms to range for unsigned 32bit signed Integer.


## Potential downsides

* Nothing that has not been noted in original proposal.

## Impact on existing code

* Same as original proposal as this change is being worked on currently.

## Alternatives considered

* Keep the _UI/TTS_ _OnResetTimeout_
  * This might cause confusion for HMI implementation.

**Comment by joeljfischer** [comment]
So, since `deprecated` doesn't exist in `HMI_API`, the solution would be to entirely remove the RPC, correct? So the `HMI_API` and Core would need to jump major versions?

**Comment by yang1070** [comment]
@joeljfischer Yes, it will remove the RPC  from the HMI_API.  In HMI API, we have something like 
```xml
<interface name="Common" version="2.0.0" date="2018-09-05">
```
this change will need a version change in HMI API.

However, The mobile API does not change. Therefore, I don't expect a major version change of core,

**Comment by jordynmackool** [comment]
The Steering Committee voted to accept this proposal with revisions. The revisions will include greater clarification on the change that will be made to the HMI API, noting that it would be a major version change not only to HMI but to core as well. Additionally, the current logic presented in the accepted proposal can stay intact until a major version change.
There was much discussion on whether or not breaking changes in the HMI directly impact core’s versioning. It was determined that we must update Core’s version based on updates to the HMI_API version. If there is a breaking change made in either the HMI or in the MOBILE API then the core versioning will need to be updated to align, this will be precedent moving forward.

**Comment by jordynmackool** [comment]
@atiwari9 please notify me when revisions have been made.

**Comment by theresalech** [comment]
Proposal has been updated to reflect revisions and comments have been left on implementation issues to reference revisions:
[Core](https://github.com/smartdevicelink/sdl_core/issues/2422)
[RPC](https://github.com/smartdevicelink/rpc_spec/issues/114)
