### ISSUE TITLE
[Accepted with Revisions] SDL 0222 - Add System Software Name parameter to Register App Interface Response

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_evolution#701]
Hello SDL community,

The review of "SDL 0222 - Add System Software Name parameter to Register App Interface Response" begins now and runs through April 17, 2019.  The proposal is available here:

https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0222-rair-system-software-name.md

Reviews are an important part of the SDL evolution process. All reviews should be sent to the associated Github issue at:

https://github.com/smartdevicelink/sdl_evolution/issues/701

What goes into a review?

The goal of the review process is to improve the proposal under review through constructive criticism and, eventually, determine the direction of SDL. When writing your review, here are some questions you might want to answer in your review:

* Is the problem being addressed significant enough to warrant a change to SDL?
* Does this proposal fit well with the feel and direction of SDL?
* If you have used competitors with a similar feature, how do you feel that this proposal compares to those?
* How much effort did you put into your review? A glance, a quick reading, or an in-depth study?
Please state explicitly whether you believe that the proposal should be accepted into SDL.

More information about the SDL evolution process is available at

https://github.com/smartdevicelink/sdl_evolution/blob/master/process.md

Thank you,
Theresa Lech

Program Manager - Livio
theresa@livio.io

**Comment by joeljfischer** [comment]
This is super embarrassing, but the name of the parameter in the proposed solution is `systemSoftwareVersion`, when it should obviously be `systemSoftwareName`.

**Comment by theresalech** [comment]
The Steering Committee voted to accept this proposal with the following revision: parameter `systemSoftwareVersion` should be changed to `systemSoftwareName`.  During the meeting, the author of the proposal also spoke to the proposal's purpose.  He noted that it makes it easier for app developers who are trying to do analytics for crash logs, especially in cases where an OEM offers more than one type of SDL-enabled system, so that the developer can correlate make / model / modelYear with system software version and SDL version.

**Comment by theresalech** [comment]
@joeljfischer please advise when a new PR has been entered to update the proposal to reflect the agreed upon revisions. I'll then merge the PR so the proposal is up to date, and enter issues in the respective repositories for implementation. Thanks!

**Comment by jordynmackool** [comment]
The author has updated the proposal per the accepted revisions. Issues have been entered for:
[Core](https://github.com/smartdevicelink/sdl_core/issues/2886)
[iOS](https://github.com/smartdevicelink/sdl_ios/issues/1241)
[Java Suite](https://github.com/smartdevicelink/sdl_java_suite/issues/1045)
[RPC](https://github.com/smartdevicelink/rpc_spec/issues/157)
