### ISSUE TITLE
[Accepted with Revisions] SDL 0225 - Update Published App Services

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_evolution#713]
Hello SDL community,

The review of "SDL 0225 - Update Published App Services" begins now and runs through May 7, 2019.  The proposal is available here:

https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0225-update-published-app-services.md

Reviews are an important part of the SDL evolution process. All reviews should be sent to the associated Github issue at:

https://github.com/smartdevicelink/sdl_evolution/issues/713

What goes into a review?

The goal of the review process is to improve the proposal under review through constructive criticism and, eventually, determine the direction of SDL. When writing your review, here are some questions you might want to answer in your review:

* Is the problem being addressed significant enough to warrant a change to SDL?
* Does this proposal fit well with the feel and direction of SDL?
* If you have used competitors with a similar feature, how do you feel that this proposal compares to those?
* How much effort did you put into your review? A glance, a quick reading, or an in-depth study?
Please state explicitly whether you believe that the proposal should be accepted into SDL.

More information about the SDL evolution process is available at

https://github.com/smartdevicelink/sdl_evolution/blob/master/process.md

Thank you,
Theresa Lech

Program Manager - Livio
theresa@livio.io

**Comment by JackLivio** [comment]
I think this is probably implied but an app should only be able to delete services that it created itself. Core will need to validate that the requesting app id maps to the service id in the request. Core should respond with disallowed otherwise.

**Comment by joeygrover** [comment]
| 1. I'm thinking the new RPC should be called `UnpublishAppService`  instead of `DeleteAppService`. 

| 2. I think it should be stated if nothing is updated when an app sends another `PublishAppService` RPC that Core will not send out any update to clients.  

|3. Is there any necessity in adding a flag to `PublishAppService` such as `overwriteExistingService` that would designate if Core should overwrite or not? I'm not 100% there should be, just asking the author their thoughts on it.

**Comment by jacobkeeler** [comment]
@joeygrover 
1. Fine with me

2. Agreed, I feel that it might be implied, but it is much better for development to have it in writing.

3. I don't believe this would be necessary. As far as I can tell, the only difference between overwriting a service and updating its manifest is that this service would be given a new service ID. If an app really wants to fully replace one of their existing services, they could just delete the original service then publish another. In any case, I think that this would be an incredibly unlikely scenario.

**Comment by theresalech** [comment]
The Steering Committee voted to accept this proposal with revisions.  The revisions will include:

- Add clarifying language to speak to [this comment](https://github.com/smartdevicelink/sdl_evolution/issues/713#issuecomment-487985968)
- Rename `DeleteAppService` to `UnpublishAppService`
- Add language to specify that if nothing is updated when an app sends another `PublishAppService` RPC, Core will not send out any update to clients.

**Comment by theresalech** [comment]
@jacobkeeler please advise when a new PR has been entered to update the proposal to reflect the agreed upon revisions. I'll then merge the PR so the proposal is up to date, and update issues in the respective repositories for implementation. Thanks!

**Comment by theresalech** [comment]
Proposal has been revised and issues have been entered:

- [Core](https://github.com/smartdevicelink/sdl_core/issues/2911)
- [RPC](https://github.com/smartdevicelink/rpc_spec/issues/161)
- [iOS](https://github.com/smartdevicelink/sdl_ios/issues/1260)
- [Java Suite](https://github.com/smartdevicelink/sdl_java_suite/issues/1060)
- [Server](https://github.com/smartdevicelink/sdl_server/issues/125)
- [Generic HMI](https://github.com/smartdevicelink/generic_hmi/issues/161)
