### ISSUE TITLE
[Accepted] SDL 0229 - SDL Server Version Tracking

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_evolution#722]
Hello SDL community,

The review of "SDL 0229 - SDL Server Version Tracking" begins now and runs through May 14, 2019.  The proposal is available here:

https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0229-sdl-server-version-tracking.md

Reviews are an important part of the SDL evolution process. All reviews should be sent to the associated Github issue at:

https://github.com/smartdevicelink/sdl_evolution/issues/722

What goes into a review?

The goal of the review process is to improve the proposal under review through constructive criticism and, eventually, determine the direction of SDL. When writing your review, here are some questions you might want to answer in your review:

* Is the problem being addressed significant enough to warrant a change to SDL?
* Does this proposal fit well with the feel and direction of SDL?
* If you have used competitors with a similar feature, how do you feel that this proposal compares to those?
* How much effort did you put into your review? A glance, a quick reading, or an in-depth study?
Please state explicitly whether you believe that the proposal should be accepted into SDL.

More information about the SDL evolution process is available at

https://github.com/smartdevicelink/sdl_evolution/blob/master/process.md

Thank you,
Theresa Lech

Program Manager - Livio
theresa@livio.io

**Comment by JackLivio** [comment]
This might be a different proposal, but if we are suggesting sdl server versioning should we discuss ways this information can be passed to the vehicle/SDL Core?

Adding version negotiation between core and the SDL server might be more of a headache than its worth right now, but use cases in the future could emerge to justify the work.

**Comment by nickschwab** [comment]
@JackLivio The idea of versioning the Policy Table schema has been discussed in passing, but would be a very large endeavor to maintain backward compatibility. Is that what you mean by passing SDL Server version information to Core? If so, let's talk offline about creating a different proposal since this one addresses a much smaller problem :)

**Comment by theresalech** [comment]
The Steering Committee fully agreed to accept this proposal.

**Comment by theresalech** [comment]
Issue entered: https://github.com/smartdevicelink/sdl_server/issues/126
