### ISSUE TITLE
[In Review] SDL 0233 - SDL Server Statistics Recording & Visualizations

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_evolution#740]
Hello SDL community,

The review of "SDL 0233 - SDL Server Statistics Recording & Visualizations" begins now and runs through May 28, 2019.  The proposal is available here:

https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0233-policy-server-statistics-recording-visualizations.md

Reviews are an important part of the SDL evolution process. All reviews should be sent to the associated Github issue at:

https://github.com/smartdevicelink/sdl_evolution/issues/740

What goes into a review?

The goal of the review process is to improve the proposal under review through constructive criticism and, eventually, determine the direction of SDL. When writing your review, here are some questions you might want to answer in your review:

* Is the problem being addressed significant enough to warrant a change to SDL?
* Does this proposal fit well with the feel and direction of SDL?
* If you have used competitors with a similar feature, how do you feel that this proposal compares to those?
* How much effort did you put into your review? A glance, a quick reading, or an in-depth study?
Please state explicitly whether you believe that the proposal should be accepted into SDL.

More information about the SDL evolution process is available at

https://github.com/smartdevicelink/sdl_evolution/blob/master/process.md

Thank you,
Theresa Lech

Program Manager - Livio
theresa@livio.io

**Comment by joeljfischer** [comment]
Could you elaborate on any potential GDPR / privacy issues related to storing this kind of data?

**Comment by nickschwab** [comment]
> Could you elaborate on any potential GDPR / privacy issues related to storing this kind of data?

@joeljfischer The data gathered in regard to this proposal will be stored anonymously and does not contain any personally-identifiable information such as email address, IP address, name, address, etc. However, since Policy Table Updates themselves may contain personally-identifiable information, it is recommended that OEMs do their own due diligence in regard to GDPR and their SDL implementation.

**Comment by theresalech** [comment]
The Steering Committee fully agreed to accept this proposal.

**Comment by theresalech** [comment]
Issues Entered:

- [Server](https://github.com/smartdevicelink/sdl_server/issues/132)
- [Core](https://github.com/smartdevicelink/sdl_core/issues/2938)
