### ISSUE TITLE
[Accepted with Revisions] SDL 0236 - Update mismatch in TireStatus structure

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_evolution#743]
Hello SDL community,

The review of "SDL 0236 - Update mismatch in TireStatus structure" begins now and runs through May 28, 2019.  The proposal is available here:

https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0236-TireStatus-Mismatch.md

Reviews are an important part of the SDL evolution process. All reviews should be sent to the associated Github issue at:

https://github.com/smartdevicelink/sdl_evolution/issues/743

What goes into a review?

The goal of the review process is to improve the proposal under review through constructive criticism and, eventually, determine the direction of SDL. When writing your review, here are some questions you might want to answer in your review:

* Is the problem being addressed significant enough to warrant a change to SDL?
* Does this proposal fit well with the feel and direction of SDL?
* If you have used competitors with a similar feature, how do you feel that this proposal compares to those?
* How much effort did you put into your review? A glance, a quick reading, or an in-depth study?
Please state explicitly whether you believe that the proposal should be accepted into SDL.

More information about the SDL evolution process is available at

https://github.com/smartdevicelink/sdl_evolution/blob/master/process.md

Thank you,
Theresa Lech

Program Manager - Livio
theresa@livio.io

**Comment by joeljfischer** [comment]
Unfortunately, this is a breaking change. Older head units implementing this feature, which is already released, require these parameters to be there. Therefore imagine a future proxy that doesn't send those parameters connects to a head unit that requires the parameters. As we have said previously when these topics come up, _any change that alters the mandatory-ness of a parameter is a breaking change_.

**Comment by yang1070** [comment]
@joeljfischer I think it was a typo or miss understanding by the author.
We believe it will be a breaking change, and that's the reason we use the value `6.0` (next major version change) in the `since` tag and `until` tag of the parameters in the API file.

```xml
        <param name="pressureTelltale" type="WarningLightStatus" mandatory="false" since="6.0">
            <description>Status of the Tire Pressure Telltale. See WarningLightStatus.</description>
            <history>
                <param name="pressureTelltale" type="WarningLightStatus" mandatory="true" since="2.0" until="6.0">
            </history>
        </param>
```

What I have learned is the following, 
- the current implementation of sdl core will validate the in-coming rpc messages from mobile and/or from hmi to make sure a mandatory parameter must be included, but it does not validate the out-going messages send by sdl core to the mobile. 
- the current implementation of mobile proxy will still accept the in-coming rpc message from sdl core even if a mandatory parameter as is missing, the programming api will return null if we try to read the value of the missing parameter.

so there will be no major code change on both proxy and core side, except updating the mobile api xml file. But we understand it is still a breaking change.

**Comment by joeljfischer** [comment]
> the current implementation of mobile proxy will still accept the in-coming rpc message from sdl core even if a mandatory parameter as is missing, the programming api will return null if we try to read the value of the missing parameter.

This is technically true, however, because we mark nullability in the library, this can and will lead to errors and crashes if data is not there when we are guaranteeing to developers that it will always be there. This is especially true in Swift.

**Comment by theresalech** [comment]
The Steering Committee voted to accept this proposal with the following revision: clarify that this update will be a breaking change.

**Comment by theresalech** [comment]
@yang1070 @robinmk please advise when a new PR has been entered to update the proposal to reflect the agreed upon revision. I'll then merge the PR so the proposal is up to date, and submit issues in the respective repositories for implementation. Thanks!

**Comment by theresalech** [comment]
Proposal has been updated to include requested revision and implementation issues have been entered:
[Core](https://github.com/smartdevicelink/sdl_core/issues/2940)
[RPC](https://github.com/smartdevicelink/rpc_spec/issues/168)
[iOS](https://github.com/smartdevicelink/sdl_ios/issues/1297)
[Java Suite](https://github.com/smartdevicelink/sdl_java_suite/issues/1089)

**Comment by theresalech** [comment]
JavaScript Suite Issue: https://github.com/smartdevicelink/sdl_javascript_suite/issues/339
