### ISSUE TITLE
[Accepted with Revisions] SDL 0237 - Add Feature to Disable "Video Streaming Backgrounded String" Feature

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_evolution#753]
Hello SDL community,

The review of "SDL 0237 - Add Feature to Disable "Video Streaming Backgrounded String" Feature" begins now and runs through June 11, 2019.  The proposal is available here:

https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0237-add-feature-to-disable-video-streaming-backgrounded-string-feature.md

Reviews are an important part of the SDL evolution process. All reviews should be sent to the associated Github issue at:

https://github.com/smartdevicelink/sdl_evolution/issues/753

What goes into a review?

The goal of the review process is to improve the proposal under review through constructive criticism and, eventually, determine the direction of SDL. When writing your review, here are some questions you might want to answer in your review:

* Is the problem being addressed significant enough to warrant a change to SDL?
* Does this proposal fit well with the feel and direction of SDL?
* If you have used competitors with a similar feature, how do you feel that this proposal compares to those?
* How much effort did you put into your review? A glance, a quick reading, or an in-depth study?
Please state explicitly whether you believe that the proposal should be accepted into SDL.

More information about the SDL evolution process is available at

https://github.com/smartdevicelink/sdl_evolution/blob/master/process.md

Thank you,
Theresa Lech

Program Manager - Livio
theresa@livio.io

**Comment by joeljfischer** [comment]
I'm in favor of this proposal, however I think that `sendVideoBackgroundedString` should be renamed to `showVideoBackgroundDisplay`.

**Comment by t-yoshii** [comment]
Hello @joeljfischer ,

Thanks for your comments.

> sendVideoBackgroundedString should be renamed to showVideoBackgroundDisplay

I think it is good too.

**Comment by theresalech** [comment]
The Steering Committee voted to accept this proposal with the following revision: rename `sendVideoBackgroundedString` to `showVideoBackgroundDisplay`.

**Comment by theresalech** [comment]
@t-yoshii please advise when a new PR has been entered to update the proposal to reflect the agreed upon revision. I'll then merge the PR so the proposal is up to date, and submit an issue in the iOS repository for implementation. Thanks!

**Comment by theresalech** [comment]
Proposal has been updated to reflect revision, and implementation issue has been entered: https://github.com/smartdevicelink/sdl_ios/issues/1304.
