### ISSUE TITLE
[Accepted with Revisions] SDL 0213 Revisions - rc-radio-climate-parameter-update

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_evolution#761]
Hello SDL community,

The review of "Revision 0213-rc-radio-climate-parameter-update" begins now and runs through June 18, 2019. This will be a review of proposed revisions to a previously accepted but not yet implemented proposal, [SDL 0213](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0213-rc-radio-climate-parameter-update.md).  

The pull request outlining the revisions under review is available here:

https://github.com/smartdevicelink/sdl_evolution/pull/757

Reviews are an important part of the SDL evolution process. All reviews should be sent to the associated Github issue at:

https://github.com/smartdevicelink/sdl_evolution/issues/761

What goes into a review?

The goal of the review process is to improve the proposal under review through constructive criticism and, eventually, determine the direction of SDL. When writing your review, here are some questions you might want to answer in your review:

* Is the problem being addressed significant enough to warrant a change to SDL?
* Does this proposal fit well with the feel and direction of SDL?
* If you have used competitors with a similar feature, how do you feel that this proposal compares to those?
* How much effort did you put into your review? A glance, a quick reading, or an in-depth study?
Please state explicitly whether you believe that the proposal should be accepted into SDL.

More information about the SDL evolution process is available at

https://github.com/smartdevicelink/sdl_evolution/blob/master/process.md

Thank you,
Theresa Lech

Program Manager - Livio
theresa@livio.io

**Comment by joeljfischer** [comment]
1\. Does `availableHDsAvailable` need a history tag for the pre-deprecation version?

**Comment by JackLivio** [comment]
1. Thank you for pointing that out. 

I would like to change the RPC availableHDsAvailable entry to:

```
        <param name="availableHDsAvailable" type="Boolean" mandatory="false" deprecated="true" since="5.x">
            <description>
                Availability of the getting the number of available HD channels.
                True: Available, False: Not Available, Not present: Not Available.
            </description>
            <history>
                <param name="availableHDsAvailable" type="Boolean" mandatory="false" since="4.5" until="5.x"/>
            </history>
        </param>
```

**Comment by theresalech** [comment]
The Steering Committee voted to accept these changes, with the revision noted in [this comment](https://github.com/smartdevicelink/sdl_evolution/issues/761#issuecomment-502773390).  The Steering Committee also voted to keep this feature in the planned October releases, thereby making the Core and RPC Spec releases major version changes (6.0).

**Comment by theresalech** [comment]
@JackLivio please advise when PR #757 has been updated to reflect the agreed upon revisions.  I'll then merge so that the proposal .md file for SDL 0213 incorporates these changes, and update the implementation issues for SDL 0213 accordingly.

**Comment by JackLivio** [comment]
@theresalech Accepted revisions have been updated.

**Comment by theresalech** [comment]
Implementation issues have been updated to reflect accepted revisions:

- [RPC](https://github.com/smartdevicelink/rpc_spec/issues/144)
- [Core](https://github.com/smartdevicelink/sdl_core/issues/2793)
- [iOS](https://github.com/smartdevicelink/sdl_ios/issues/1143)
- [Java Suite](https://github.com/smartdevicelink/sdl_java_suite/issues/960)
