### ISSUE TITLE
[Accepted with Revisions] SDL 0242 - Subtle Alert Style

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_evolution#777]
Hello SDL community,

The review of "SDL 0242 - Subtle Alert Style" begins now and runs through July 16, 2019.  The proposal is available here:

https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0242-alert-style-subtle.md

Reviews are an important part of the SDL evolution process. All reviews should be sent to the associated Github issue at:

https://github.com/smartdevicelink/sdl_evolution/issues/777

What goes into a review?

The goal of the review process is to improve the proposal under review through constructive criticism and, eventually, determine the direction of SDL. When writing your review, here are some questions you might want to answer in your review:

* Is the problem being addressed significant enough to warrant a change to SDL?
* Does this proposal fit well with the feel and direction of SDL?
* If you have used competitors with a similar feature, how do you feel that this proposal compares to those?
* How much effort did you put into your review? A glance, a quick reading, or an in-depth study?
Please state explicitly whether you believe that the proposal should be accepted into SDL.

More information about the SDL evolution process is available at

https://github.com/smartdevicelink/sdl_evolution/blob/master/process.md

Thank you,
Theresa Lech

Program Manager - Livio
theresa@livio.io

**Comment by JackLivio** [comment]
I am good with the original proposal. However, I just want to reiterate the authors point that by not having a separate RPC, the subtle alert style will not be able to have special policy exemptions from the policies applied to the "prominent" alert request. 

For example,  If there is a use case where an OEM wants to allow subtle alerts in none, but only allow prominent alerts in at least background, this proposal would have to implement the alternate approach 1.

**Comment by theresalech** [comment]
The Steering Committee voted to accept this proposal with the following revision: update to use alternate approach 1, for the reasons identified in [this comment](https://github.com/smartdevicelink/sdl_evolution/issues/777#issuecomment-511516024) from the Project Maintainer.

**Comment by theresalech** [comment]
@joeljfischer please advise when a new PR has been entered to update the proposal to reflect the agreed upon revisions. I'll then merge the PR so the proposal is up to date, and enter issues in the respective repositories for implementation. Thanks!

**Comment by theresalech** [comment]
Author has updated proposal to include agreed upon revisions, and implementation issues have been entered (see above).
