### ISSUE TITLE
[Accepted with Revisions] SDL 0221 Revisions - Remote Control - Allow Multiple Modules per Module Type

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_evolution#791]
Hello SDL community,

The review of "Revise SDL-0221 Remote Control - Allow Multiple Modules per Module Type" begins now and runs through July 30, 2019. This will be a review of proposed revisions to a previously accepted but not yet implemented proposal, [SDL 0221](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0221-multiple-modules.md).  

The pull request outlining the revisions under review is available here:

https://github.com/smartdevicelink/sdl_evolution/pull/786

Reviews are an important part of the SDL evolution process. All reviews should be sent to the associated Github issue at:

https://github.com/smartdevicelink/sdl_evolution/issues/791

What goes into a review?

The goal of the review process is to improve the proposal under review through constructive criticism and, eventually, determine the direction of SDL. When writing your review, here are some questions you might want to answer in your review:

* Is the problem being addressed significant enough to warrant a change to SDL?
* Does this proposal fit well with the feel and direction of SDL?
* If you have used competitors with a similar feature, how do you feel that this proposal compares to those?
* How much effort did you put into your review? A glance, a quick reading, or an in-depth study?
Please state explicitly whether you believe that the proposal should be accepted into SDL.

More information about the SDL evolution process is available at

https://github.com/smartdevicelink/sdl_evolution/blob/master/process.md

Thank you,
Theresa Lech

Program Manager - Livio
theresa@livio.io

**Comment by JackLivio** [comment]
1. 
> If a mobile app uses the SupportedSeat id and omits moduleId in a RPC request, SDL shall add the moduleId parameter to HMI request according to the following rules:

Eventually "id" will be marked removed from the mobile api in version 7.0. Are these the behaviors for core only when the app registers and negotiates as a <=6.0 rpc spec version? In other words a >= 7.0 rpc app that sends "id" should get an invalid data error returned. 


2.
 > if id = FRONT_PASSENGER then moduleId = moduleId of second published module in seatControlCapabilities

This creates the requirement that order now matters. When you say published module do you mean the results of HMI RPC RC.GetCapabilities?

3. 
> If a mobile app includes both SupportedSeat id and moduleId in a RPC request, SDL shall forward the request as is to HMI.

This should only apply to apps that negotiate a >= 6.0 and  < 7.0 rpc spec version.

**Comment by LuxoftAKutsan** [comment]
1. Correct
2. Yes.
3. Yes.

**Comment by theresalech** [comment]
The Steering Committee voted to accept this proposal with revisions.  The revisions will include adding clarifying language, specifying behavior for specific versions, as outlined in [this comment](https://github.com/smartdevicelink/sdl_evolution/issues/791#issuecomment-516089005) from the Project Maintainer.

**Comment by theresalech** [comment]
@LuxoftAKutsan please advise when PR #786 has been updated to reflect these agreed upon revisions.  I'll then merge the PR so the proposal file is up to date, and make note of these changes on the respective implementation issues for SDL 0221.  Thanks!

**Comment by theresalech** [comment]
Agreed upon revisions have been added to PR, and PR has been merged, so proposal file is now up to date.  Comments have been left on implementation issues to call out these revisions:
[SDL HMI](https://github.com/smartdevicelink/sdl_hmi/issues/198)
[Java Suite](https://github.com/smartdevicelink/sdl_java_suite/issues/1070)
[iOS](https://github.com/smartdevicelink/sdl_ios/issues/1272)
[RPC Spec](https://github.com/smartdevicelink/rpc_spec/issues/165)
[Core](https://github.com/smartdevicelink/sdl_core/issues/2919)
