### ISSUE TITLE
[In Review] SDL 0179 Revisions - Pixel Density and Scale

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_evolution#808]
Hello SDL community,

The review of "Revise SDL-0179 Pixel Density and Scale" begins now and runs through August 20, 2019. This will be a review of proposed revisions to a previously accepted but not yet implemented proposal, [SDL 0179](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0179-pixel-density-and-scale.md).  

The pull request outlining the revisions under review is available here:

https://github.com/smartdevicelink/sdl_evolution/pull/805

Reviews are an important part of the SDL evolution process. All reviews should be sent to the associated Github issue at:

https://github.com/smartdevicelink/sdl_evolution/issues/808

What goes into a review?

The goal of the review process is to improve the proposal under review through constructive criticism and, eventually, determine the direction of SDL. When writing your review, here are some questions you might want to answer in your review:

* Is the problem being addressed significant enough to warrant a change to SDL?
* Does this proposal fit well with the feel and direction of SDL?
* If you have used competitors with a similar feature, how do you feel that this proposal compares to those?
* How much effort did you put into your review? A glance, a quick reading, or an in-depth study?
Please state explicitly whether you believe that the proposal should be accepted into SDL.

More information about the SDL evolution process is available at

https://github.com/smartdevicelink/sdl_evolution/blob/master/process.md

Thank you,
Theresa Lech

Program Manager - Livio
theresa@livio.io

**Comment by kshala-ford** [comment]
Thanks to the author for writing this proposal revision. I think the change should be in [Mobile & HMI API Changes](https://github.com/smartdevicelink/sdl_evolution/blob/b2882551457c422f8b7b51f695c16060f4f7358a/proposals/0179-pixel-density-and-scale.md#mobile--hmi-api-changes) instead of [Alternatives Considered](https://github.com/smartdevicelink/sdl_evolution/blob/b2882551457c422f8b7b51f695c16060f4f7358a/proposals/0179-pixel-density-and-scale.md#alternatives-considered).

So the change should be

```xml
<struct name="VideoStreamingCapability">
: 
<param name="diagonalScreenSize" type="Float" mandatory="false">
 <description>The diagonal screen size in inches.</description>
</param>
<param name="pixelPerInch" type="Float" mandatory="false">
 <description>PPI is the diagonal resolution in pixels divided by the diagonal screen size in inches.</description>
</param>
<param name="scale" type="Float" minvalue="1" maxvalue="10" mandatory="false">
  <description>The scaling factor the app should use to change the size of the projecting view.</description>
</param>
</struct>
```

**Comment by joeljfischer** [comment]
The `pixelsPerInch` and `diagonalScreenSize` can probably also have `minValue`s of `0`, even if we don't cap it with a max value.

**Comment by theresalech** [comment]
The Steering Committee agreed to accept this proposal with the revisions described in [this comment](https://github.com/smartdevicelink/sdl_evolution/issues/808#issuecomment-519120487) and [this comment](https://github.com/smartdevicelink/sdl_evolution/issues/808#issuecomment-519608226).

**Comment by theresalech** [comment]
@NicoleYarroch please let me know when the PR #805 has been updated to reflect the agreed upon revisions noted above.

**Comment by theresalech** [comment]
PR #805 has been updated to reflect agreed upon revisions and merged so proposals.md file is up to date.  Comments have been left on implementation issues for SDL 0179 to note the changes to the feature (see links above).
