### ISSUE TITLE
[Accepted with Revisions] SDL 0252 - Aligning HMI and MOBILE API for pcmStreamCapabilities

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_evolution#829]
Hello SDL community,

The review of "SDL 0252 - Aligning HMI and MOBILE API for pcmStreamCapabilities" begins now and runs through October 8, 2019.  The proposal is available here:

https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0252-Aligning-HMI-and-MOBILE-API-for-pcmStreamCapabilities.md

Reviews are an important part of the SDL evolution process. All reviews should be sent to the associated Github issue at:

https://github.com/smartdevicelink/sdl_evolution/issues/829

What goes into a review?

The goal of the review process is to improve the proposal under review through constructive criticism and, eventually, determine the direction of SDL. When writing your review, here are some questions you might want to answer in your review:

* Is the problem being addressed significant enough to warrant a change to SDL?
* Does this proposal fit well with the feel and direction of SDL?
* If you have used competitors with a similar feature, how do you feel that this proposal compares to those?
* How much effort did you put into your review? A glance, a quick reading, or an in-depth study?
Please state explicitly whether you believe that the proposal should be accepted into SDL.

More information about the SDL evolution process is available at

https://github.com/smartdevicelink/sdl_evolution/blob/master/process.md

Thank you,
Theresa Lech

Program Manager - Livio
theresa@livio.io

**Comment by joeljfischer** [comment]
The main downside that I can see is that this is a major version change due to how it's implemented when it could be a minor version change.

`<param name="pcmStreamCapabilities" type="Common.AudioPassThruCapabilities" mandatory="true"/>`

This adds a mandatory parameter, which makes it a major version change. If it's made non-mandatory, it would be a minor version change.

**Comment by kshala-ford** [comment]
Since the parameter is optional in the mobile API it could also be optional in the HMI API I suppose. I think this would be an acceptable revision assuming the Project Maintainers are looking for an optional param?

**Comment by hwilli88** [comment]
@joeljfischer @kshala-ford 

Agree to change to non-mandatory.

<param name="pcmStreamCapabilities" type="Common.AudioPassThruCapabilities" mandatory="false"/>

**Comment by theresalech** [comment]
The Steering Committee voted to accept this proposal with the following revision: change `pcmStreamCapabilities` to non-mandatory, as described in [this comment](https://github.com/smartdevicelink/sdl_evolution/issues/829#issuecomment-539505777).
