### ISSUE TITLE
[Rejected] SDL 0254 - New vehicle data HVBatteryLevel

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_evolution#842]
Hello SDL community,

The review of "SDL 0254 - New vehicle data HVBatteryLevel" begins now and runs through October 15, 2019.  The proposal is available here:

https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0254-New-vehicle-data-HVBatteryLevel.md

Reviews are an important part of the SDL evolution process. All reviews should be sent to the associated Github issue at:

https://github.com/smartdevicelink/sdl_evolution/issues/842

What goes into a review?

The goal of the review process is to improve the proposal under review through constructive criticism and, eventually, determine the direction of SDL. When writing your review, here are some questions you might want to answer in your review:

* Is the problem being addressed significant enough to warrant a change to SDL?
* Does this proposal fit well with the feel and direction of SDL?
* If you have used competitors with a similar feature, how do you feel that this proposal compares to those?
* How much effort did you put into your review? A glance, a quick reading, or an in-depth study?
Please state explicitly whether you believe that the proposal should be accepted into SDL.

More information about the SDL evolution process is available at

https://github.com/smartdevicelink/sdl_evolution/blob/master/process.md

Thank you,
Theresa Lech

Program Manager - Livio
theresa@livio.io

**Comment by kshala-ford** [comment]
I do support this proposal, knowing the level of charge for battery electric vehicles is a demanded information. I think with HVBattery you mean high voltage batteries ~300V DC for the electric powertrain and you want to distinguish from 12V/48V batteries?

The single concern I have is that this proposal would introduce a third vehicle data item related to energy sources for engines. `fuelLevel` which only returns a single percentage of a primary propellant. `fuelRange` is more flexible per energy source but doesn't return level. Would it make sense to add level to the `FuelRange` struct? It might be easier to implement from the SDL perspective (looking at Core and policy changes) but on the other side `fuel` sounds odd on BEV...

Question: Are absolute numbers or information such as capacity (and probably also unit) available? The percentage itself wouldn't tell the kWh remaining. Knowing the absolute capacity of the battery can be useful information. Remaining kWh can be calculated by multiplying the percentage level.

**Comment by kshala-ford** [comment]
Tried to create a suggestion of adding the proposed param to fuel range. I believe it makes sense because the fuel range is directly related to level. I reviewed the proposal again and found that min/max is set to 0-150%. Could you provide more details to why you picked these min/max values? I excluded min/max from below suggestion.

```xml
+<enum name="CapacityUnit">
+    <element name="LITERS" />
+    <element name="KILOWATTHOURS" />
+</enum>

<struct name="FuelRange" since="5.0">
    <param name="type" type="FuelType" mandatory="false"/>
    <param name="range" type="Float" minvalue="0" maxvalue="10000" mandatory="false">
        <description>
            The estimate range in KM the vehicle can travel based on fuel level and consumption.
        </description>
    </param>
+   <param name="level" type="Float" mandatory="false"> <!-- Excluding min/max for now... -->
+       <description>The relative remaining capacity of this fuel type (percentage).</description>
+   </param>
+   <param name="levelState" type="ComponentVolumeStatus" mandatory="false">
+        <description>The fuel level state</description>
+    </param>
+   <param name="capacity" type="Float" mandatory="false">
+       <descriptino>The absolute capacity of this fuel type.</description>
+   </param>
+   <param name="capacityType" type="CapacityType" mandatory="false">
+       <description>The unit of the capacity of this fuel type such as liters for gasoline or kWh for batteries.</description>
+   </param>
</struct>
```

**Comment by atiwari9** [comment]
@kshala-ford  - Your point about "_Fuel does not make sense for EV_" is the sole reason we needed new vehicle data item. If it was not that, we could internally map the battery charge signal to `FuelLevel` itself.

I however like the idea of `capacity` for batterypack. I do not think we have a way to communicate that to the app right now, So i'd welcome the addition of available capacity in kWh for battery.

For the range of battery level, usually the signals shoot up t more than 100% when battery is fully charged as theoretical 100% is marked at lesser level than actual. So this is just to avoid SDL Core filtering out that data.

To incorporate available capacity, we can add a struct like

```xml
<struct name="HVBatteryLevel" since="X.x">
    <param name="batteryLevel" type="Float" minvalue="0" maxvalue="150" mandatory="false" since="X.x">
        <description>Percentage of High Voltage battery charge available</description>
    </param>
    <param name="availableCapacity" type="Integer" minvalue="0" maxvalue="1000" mandatory="false" since="X.x">
        <description>Available battery capacity in kWh</description>
    </param>
</struct>
```

**Comment by kshala-ford** [comment]
@atiwari9 i did not say it doesn’t make sense. It just sounds odd. Mapping the charge to fuel level is not possible even when you would accept the naming if you consider hybrid or hydrogen vehicles.

The attempt of https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0072-New-vehicle-data-FuelRange.md was to unify and streamline the vehicle data structure with the variety of vehicle types and their types of energy sources (any propellant or electrical charge). I’m afraid we’re loosing the streamline approach and give BEV an outstanding role while not considering plugin or hydrogen.

I think I’m not getting the point to max value. Is the charge level relative to the theoretical capacity the battery is designed for? And that batteries could be charged beyond that if the electrical condition of the cells allow more charge?

**Comment by atiwari9** [comment]
@kshala-ford  and i discussed and we came to an agreement that we should consolidate Fuel information related vehicle data to make the API cleaner. So I'd like to propose following changes:

1. Enhance `FuelRange` Struct as per [Kujtim's Comment](https://github.com/smartdevicelink/sdl_evolution/issues/842#issuecomment-542259399)
2. Deprecate `FuelLevel`
3. Deprecate `FuelLevel_State`

I'll update the proposal as per this so that everyone can review it,

**Comment by atiwari9** [comment]
Since the changes need an update in Title of proposal, i have submitted a new proposal PR: https://github.com/smartdevicelink/sdl_evolution/pull/851

**Comment by JackLivio** [comment]
@atiwari9  If we agree to deprecate FuelLevel and FuelLevel_State in the Mobile API and move their equivalent parameters into the FuelRange struct, I want to discuss what the means for the HMI_API.xml. 

If we move FuelLevel and FuelLevel_state into the FuelRange struct, then I think we can remove the old FuelLevel and FuelLevel_state parameters from the HMI API. If the HMI and Core communicate only using the new FuelRange structure, logic can be added to Core to make sure the appropriate vehicle data response is communicated to the phone based on the negotiated RPC spec version.

**Comment by atiwari9** [comment]
@JackLivio 

Yes, `FuelLevel` and `FuelLevel_State` should be removed for a major version change. Is you suggestion to remove from HMI API and negotiate version for Mobile Proxies to avoid a breaking change? Wouldn't that anyways be breaking for HMI? 

I was hoping we could use deprecation here like we did for [`DisplayType` in Mobile API](https://github.com/smartdevicelink/sdl_core/blob/master/src/components/interfaces/MOBILE_API.xml#L689) and it is [kept in HMI API](https://github.com/smartdevicelink/sdl_core/blob/master/src/components/interfaces/HMI_API.xml#L438)

**Comment by JackLivio** [comment]
@atiwari9 Ok nevermind, yes lets keep the old parameters in the HMI API for now and mark them deprecated to avoid a Core major version change. I guess my point was that there is an easy path forward for ensuring backwards compatibility on the mobile side after these parameters are eventually removed.

**Comment by theresalech** [comment]
As the 2019-10-22 Steering Committee meeting did not reach a quorum, a vote could not take place on this proposal.  The proposal will remain in review until the next meeting on 2019-10-29.

**Comment by theresalech** [comment]
At the author's request, the Steering Committee voted to reject this proposal in favor of #851.
