### ISSUE TITLE
[Accepted with Revisions] SDL 0256 - Refactor Fuel Information Related Vehicle Data

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_evolution#854]
Hello SDL community,

The review of "SDL 0256 - Refactor Fuel Information Related Vehicle Data" begins now and runs through November 5, 2019.  The proposal is available here:

https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0256-Refactor-Fuel-Information-Related-Vehicle-Data.md

Reviews are an important part of the SDL evolution process. All reviews should be sent to the associated Github issue at:

https://github.com/smartdevicelink/sdl_evolution/issues/854

What goes into a review?

The goal of the review process is to improve the proposal under review through constructive criticism and, eventually, determine the direction of SDL. When writing your review, here are some questions you might want to answer in your review:

* Is the problem being addressed significant enough to warrant a change to SDL?
* Does this proposal fit well with the feel and direction of SDL?
* If you have used competitors with a similar feature, how do you feel that this proposal compares to those?
* How much effort did you put into your review? A glance, a quick reading, or an in-depth study?
Please state explicitly whether you believe that the proposal should be accepted into SDL.

More information about the SDL evolution process is available at

https://github.com/smartdevicelink/sdl_evolution/blob/master/process.md

Thank you,
Theresa Lech

Program Manager - Livio
theresa@livio.io

**Comment by joeljfischer** [comment]
This seems to be a good update. I have a few comments:

1. It seems to me that the [proposed CapacityUnit](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0256-Refactor-Fuel-Information-Related-Vehicle-Data.md#add-new-enum-capacityunit) is not adequate for all the `FuelType`s.  Is `LITERS` adequate for compressed natural gas or hydrogen? I'm not especially familiar with these fuel types, but wouldn't a pressure metric be better? Or does `LITERS` still work?

2. In the `FuelRange` struct can we change the maxValue of `level` 170 to 10000 or something like that? 170 seems arbitrary and limiting. I know it's a percentage but if we're already going over 100, then we should just have a huge upper limit just in case.

3. Same as above but for `capacity`. Why not just have a limit of 1000000 or something?

**Comment by atiwari9** [comment]
@joeljfischer 

1. For Gas fuels, i believe those are represented either by weight(kg) or volume(liters) for an average consumer at the Fuel dispensing source(pump). e.g. `CNG` is sold as gallons in US and as kg in UK/India etc. Same for `LPG`. I think we should add `KILOGRAMS` to the enum as well.

2. I have no objection to this.

3. Same, no objection to this. Though the value i came up with was after considering realistic max for different fuel types, but increasing the range does no harm.

**Comment by atiwari9** [comment]
@joeygrover 

4. Yes. That is a typo #ToUpdate 

5. OK, #ToUpdate 

6. OK #ToUpdate

**Comment by atiwari9** [comment]
1. Will add `KILOGRAM` then. #ToUpdate

**Comment by theresalech** [comment]
The Steering Committee voted to accept this proposal with revisions.  The author will make the following changes to the proposal: add `KILOGRAM` to `CapacityUnit`; change maxValue of `level` and `capacity` in `FuelRange` to larger upper limit (1000000); fix `fuelLevel` and `fuelLevel_State` typos; update descriptions of `fuelLevel` and `fuelLevel_State` to state the param is deprecated as of x.x.x of the rpc spec, please see `fuelRange`; modify description of `fuelRange` param to be more descriptive of its extended capabilities.  The author can work with the Project Maintainer to finalize this description.

**Comment by theresalech** [comment]
@atiwari9 Please advise when a new PR has been entered to update the proposal to reflect the agreed upon revisions. I'll then merge the PR so the proposal is up to date, and enter issues in the respective repositories for implementation. Thanks!

**Comment by theresalech** [comment]
Proposal has been updated to reflect revisions.  Implementation issues have been entered:

[RPC](https://github.com/smartdevicelink/rpc_spec/issues/204)
[Core](https://github.com/smartdevicelink/sdl_core/issues/3124)
[SDL HMI](https://github.com/smartdevicelink/sdl_hmi/issues/261)
[Java Suite](https://github.com/smartdevicelink/sdl_java_suite/issues/1223)
[iOS](https://github.com/smartdevicelink/sdl_ios/issues/1472)

**Comment by theresalech** [comment]
JavaScript Suite Issue: https://github.com/smartdevicelink/sdl_javascript_suite/issues/250
