### ISSUE TITLE
[Accepted] SDL 0025 - Stream File Manager Uploads from Disk

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_evolution#87]
Hello SDL community,

The review of "Stream File Manager Uploads from Disk" begins now and runs through February 14, 2017. The proposal is available here:

https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0025-ios-filemanager-stream-from-disk.md

Reviews are an important part of the SDL evolution process. All reviews should be sent to the associated Github issue at:

https://github.com/smartdevicelink/sdl_evolution/issues/87

What goes into a review?

The goal of the review process is to improve the proposal under review through constructive criticism and, eventually, determine the direction of SDL. When writing your review, here are some questions you might want to answer in your review:

* Is the problem being addressed significant enough to warrant a change to SDL?
* Does this proposal fit well with the feel and direction of SDL?
* If you have used competitors with a similar feature, how do you feel that this proposal compares to those?
* How much effort did you put into your review? A glance, a quick reading, or an in-depth study?
Please state explicitly whether you believe that the proposal should be accepted into SDL.

More information about the SDL evolution process is available at

https://github.com/smartdevicelink/sdl_evolution/blob/master/process.md

Thank you,
Theresa Lech

Program Manager - Livio
theresa@livio.io

**Comment by grimlockrocks** [comment]
Will this also reduce the latency of files/images (e.g. app icon, images to show on the screen) upload to HMI?

**Comment by joeljfischer** [comment]
@grimlockrocks No, I don't think so, not unless the file is quite large. Images of a normal size will most likely not be affected by this at all.

**Comment by theresalech** [comment]
There was little discussion about this proposal, as the Steering Committee quickly agreed this is a good idea and accepted the proposal.

**Comment by theresalech** [comment]
Issue entered: [[SDL 0025] Stream File Manager Uploads from Disk](https://github.com/smartdevicelink/sdl_ios/issues/536)
