### ISSUE TITLE
[Accepted with Revisions] SDL 0262 - New vehicle data SeatOccupancy

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_evolution#870]
Hello SDL community,

The review of "SDL 0262 - New vehicle data SeatOccupancy" begins now and runs through December 3, 2019.  The proposal is available here:

https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0262-New-vehicle-data-SeatOccupancy.md

Reviews are an important part of the SDL evolution process. All reviews should be sent to the associated Github issue at:

https://github.com/smartdevicelink/sdl_evolution/issues/870

What goes into a review?

The goal of the review process is to improve the proposal under review through constructive criticism and, eventually, determine the direction of SDL. When writing your review, here are some questions you might want to answer in your review:

* Is the problem being addressed significant enough to warrant a change to SDL?
* Does this proposal fit well with the feel and direction of SDL?
* If you have used competitors with a similar feature, how do you feel that this proposal compares to those?
* How much effort did you put into your review? A glance, a quick reading, or an in-depth study?
Please state explicitly whether you believe that the proposal should be accepted into SDL.

More information about the SDL evolution process is available at

https://github.com/smartdevicelink/sdl_evolution/blob/master/process.md

Thank you,
Theresa Lech

Program Manager - Livio
theresa@livio.io

**Comment by joeljfischer** [comment]
This proposal seems generally good for me. I have a few small note: the `SeatOccupancy` parameter descriptions don't seem correct. Also optional arrays should have `minSize=1` not `0`.

**Comment by kshala-ford** [comment]
I don't think this array should be `minSize=1` because an empty array clearly specifies that no seat is occupied or belted. you couldn't differentiate from seats not known.

**Comment by atiwari9** [comment]
Actually an empty array would mean that there are no seats. (hypothetical or in some universe where self driving cars don't offer seating :) ) , in that case how it a result code `VEHICLE_DATA_NOT_AVAILABLE` different than and empty array? If there are other params in same vehicle data item, then i'd say to keep array min size as 0 to not affect overall result code. So i guess we can keep min size as 0 for scalability.

**Comment by kshala-ford** [comment]
Thanks @atiwari9 I think I misunderstood the array in the first reading. Thought that only occupied or belted seats are included in the array.

To answer your question: My understanding is that `VEHICLE_DATA_NOT_AVAILABLE` for seats would mean that the seat status is not known or not implemented while an empty array is a clear statement of no seats available (at least with the given status information).

**Comment by atiwari9** [comment]
Sure, So both reasons warrant to keep the `minSize=0`

**Comment by joeljfischer** [comment]
👍

**Comment by joeljfischer** [comment]
Regarding the parameter description that still needs updating for `seatsOccupied` and `seatsBelted`, what about something like "Array of seats containing their location and whether or not they are currently occupied (/ belted)."

**Comment by atiwari9** [comment]
@joeljfischer  - are you pointing to [Struct for `SeatOccupancy`](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0262-New-vehicle-data-SeatOccupancy.md#add-new-struct-seatoccupancy-in-common-interface), is does have some description, did you mean to add the fact that the param is an array?

**Comment by joeljfischer** [comment]
@atiwari9 The `SeatOccupancy.seatsOccupied` and `belted` parameter descriptions just say "true" or "false", but the actual parameters aren't Boolean, they're `SeatStatus` structs. I just think that the description is confusing.

**Comment by atiwari9** [comment]
@joeljfischer - Got it, how about something like this then:

```xml
<struct name="SeatOccupancy">
	<param name="seatsOccupied" type="Common.SeatStatus" array="true" minsize="0" maxsize="100" mandatory="false">
		<description>Seat(s) status array containing location and whether the seat(s) is(are) occupied.</description>
	</param>
	<param name="seatsBelted" type="Common.SeatStatus" array="true" minsize="0" maxsize="100" mandatory="false">
		<description>Seat(s) status array containing location and whether the seat(s) is(are) belted.</description>
</struct>
```

**Comment by joeljfischer** [comment]
@atiwari9 I think it's fine if you just use plural and remove the `(s)` and `(are)`. Singular is implied if there happens to only be one.

**Comment by theresalech** [comment]
The Steering Committee voted to accept this proposal with the following revision: update `SeatOccupancy` parameter description to "Seat status array containing the location and whether the seats are belted."

**Comment by theresalech** [comment]
Proposal has been updated to reflect accepted revisions and implementation issues have been entered:

- [RPC](https://github.com/smartdevicelink/rpc_spec/issues/209)
- [Core](https://github.com/smartdevicelink/sdl_core/issues/3152)
- [HMI](https://github.com/smartdevicelink/sdl_hmi/issues/266)
- [iOS](https://github.com/smartdevicelink/sdl_ios/issues/1487)
- [Java Suite](https://github.com/smartdevicelink/sdl_java_suite/issues/1240)
- [Server](https://github.com/smartdevicelink/sdl_server/issues/176)

**Comment by theresalech** [comment]
JavaScript Suite issue: https://github.com/smartdevicelink/sdl_javascript_suite/issues/336
