### ISSUE TITLE
[Accepted] SDL 0265 - Remove duplicate parameter FileName from HMI RPC BasicCommunication.OnPutFile

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_evolution#873]
Hello SDL community,

The review of "SDL 0265 - Remove duplicate parameter FileName from HMI RPC BasicCommunication.OnPutFile"  begins now and runs through December 3, 2019.  The proposal is available here:

https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0265-Remove-Duplicate-Parameter-HMI-RPC-OnPutFile.md

Reviews are an important part of the SDL evolution process. All reviews should be sent to the associated Github issue at:

https://github.com/smartdevicelink/sdl_evolution/issues/873

What goes into a review?

The goal of the review process is to improve the proposal under review through constructive criticism and, eventually, determine the direction of SDL. When writing your review, here are some questions you might want to answer in your review:

* Is the problem being addressed significant enough to warrant a change to SDL?
* Does this proposal fit well with the feel and direction of SDL?
* If you have used competitors with a similar feature, how do you feel that this proposal compares to those?
* How much effort did you put into your review? A glance, a quick reading, or an in-depth study?
Please state explicitly whether you believe that the proposal should be accepted into SDL.

More information about the SDL evolution process is available at

https://github.com/smartdevicelink/sdl_evolution/blob/master/process.md

Thank you,
Theresa Lech

Program Manager - Livio
theresa@livio.io

**Comment by joeljfischer** [comment]
This seems like the right idea, but is a major version change and should be noted as such. Any existing HMI that uses this parameter would no longer function.

**Comment by joeygrover** [comment]
Per our previous votes in Steering Committee Meetings we agreed that since each Core release has a corresponding HMI release, any changes to the HMI API are considered internal API changes and not breaking. While I do disagree with this point and agree to Joel's, the SC has already voted on what these changes mean and therefore this is not a breaking change but simply must be released alongside a Core release.

**Comment by theresalech** [comment]
The Steering Committee fully agreed to accept this proposal.

**Comment by theresalech** [comment]
Implementation issue entered: [Core](https://github.com/smartdevicelink/sdl_core/issues/3153)
