### ISSUE TITLE
[Accepted] SDL 0026 - Move to Android Studio

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_evolution#88]
Hello SDL community,

The review of "Move to Android Studio" begins now and runs through February 14, 2017. The proposal is available here:

https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0026-android_move_to_android_studio.md

Reviews are an important part of the SDL evolution process. All reviews should be sent to the associated Github issue at:

https://github.com/smartdevicelink/sdl_evolution/issues/88

What goes into a review?

The goal of the review process is to improve the proposal under review through constructive criticism and, eventually, determine the direction of SDL. When writing your review, here are some questions you might want to answer in your review:

* Is the problem being addressed significant enough to warrant a change to SDL?
* Does this proposal fit well with the feel and direction of SDL?
* If you have used competitors with a similar feature, how do you feel that this proposal compares to those?
* How much effort did you put into your review? A glance, a quick reading, or an in-depth study?
Please state explicitly whether you believe that the proposal should be accepted into SDL.

More information about the SDL evolution process is available at

https://github.com/smartdevicelink/sdl_evolution/blob/master/process.md

Thank you,
Theresa Lech

Program Manager - Livio
theresa@livio.io

**Comment by grimlockrocks** [comment]
(Sheng from Amazon): Eclipse ADT was no longer supported by the end of 2015: https://android-developers.googleblog.com/2015/06/an-update-on-eclipse-android-developer.html, and I think it is important for SDL to move to Android Studio. There should be no code changes besides some configuration files. I set it up myself a few months ago without any issues. 

I think there are three places may require updates:
a) The documentation on GitHub and Ford Developer Website
b) The example code on GitHub and Ford Developer Website
c) A note on the Emulator will not work along with Virtual Box on the same machine, see below:

Issues with running Android Emulator along with Virtual Box (this issue has not been fixed): 

emulator: ERROR: Unfortunately, there's an incompatibility between HAXM hypervisor and VirtualBox 4.3.30+ which doesn't allow multiple hypervisors to co-exist. It is being actively worked on; you can find out more about the issue at http://b.android.com/197915 (Android) and https://www.virtualbox.org/ticket/14294 (VirtualBox)

Unfortunately, neither companies fixed the issue as of writing. One of the workarounds is to set up the SYNC3 Emulator on a virtual machine, e.g. AWS EC2.

**Comment by mrapitis** [comment]
Refactoring to the Android Studio expected file structure is a positive move overall. Like mentioned in the proposal, in the short term the projects git history will be a little confusing (the git move operation may be able to limit some of this).  In the long term conforming to the studio based file structure will keep the project up to date and in line with development efforts.

**Comment by theresalech** [comment]
The Steering Committee has accepted this proposal.  Eclipse ADT has not been supported by Android since 2015, so it makes sense to move the SDL Android library to Android Studio.  We should make sure to notify users of this change before it’s in place.  The Steering Committee has also agreed that this change can be implemented in the next minor version.

**Comment by theresalech** [comment]
Issue Entered: [[SDL 0026] Move to Android Studio](https://github.com/smartdevicelink/sdl_android/issues/428)
