### ISSUE TITLE
[Accepted] SDL 0028 - Add Potential Downsides to Template

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_evolution#90]
Hello SDL community,

The review of "Add Potential Downsides to Template" begins now and runs through February 14, 2017. The proposal is available here:

https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0028-meta-template-potential-downsides.md

Reviews are an important part of the SDL evolution process. All reviews should be sent to the associated Github issue at:

https://github.com/smartdevicelink/sdl_evolution/issues/90

What goes into a review?

The goal of the review process is to improve the proposal under review through constructive criticism and, eventually, determine the direction of SDL. When writing your review, here are some questions you might want to answer in your review:

* Is the problem being addressed significant enough to warrant a change to SDL?
* Does this proposal fit well with the feel and direction of SDL?
* If you have used competitors with a similar feature, how do you feel that this proposal compares to those?
* How much effort did you put into your review? A glance, a quick reading, or an in-depth study?
Please state explicitly whether you believe that the proposal should be accepted into SDL.

More information about the SDL evolution process is available at

https://github.com/smartdevicelink/sdl_evolution/blob/master/process.md

Thank you,
Theresa Lech

Program Manager - Livio
theresa@livio.io

**Comment by joeygrover** [comment]
I see no potential downsides with this proposal.

**Comment by joeljfischer** [comment]
@joeygrover 🙄

**Comment by mrapitis** [comment]
Adding the potential downsides section will be a beneficial addition to the review process. :thumbsup:

**Comment by theresalech** [comment]
This proposal has been accepted by the Steering Committee.  As potential downsides are already included in most SDL Evolution Proposals, it was agreed that it should be explicitly stated in the SDL Evolution Proposal template moving forward.
