### ISSUE TITLE
[In Review] SDL 0276 - POI Service Supported

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_evolution#933]
Hello SDL community,

The review of "SDL 0276 - POI Service Supported"  begins now and runs through February 18, 2020.  The proposal is available here:

https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0276-POI-Service-Supported.md

Reviews are an important part of the SDL evolution process. All reviews should be sent to the associated Github issue at:

https://github.com/smartdevicelink/sdl_evolution/issues/933

What goes into a review?

The goal of the review process is to improve the proposal under review through constructive criticism and, eventually, determine the direction of SDL. When writing your review, here are some questions you might want to answer in your review:

* Is the problem being addressed significant enough to warrant a change to SDL?
* Does this proposal fit well with the feel and direction of SDL?
* If you have used competitors with a similar feature, how do you feel that this proposal compares to those?
* How much effort did you put into your review? A glance, a quick reading, or an in-depth study?
Please state explicitly whether you believe that the proposal should be accepted into SDL.

More information about the SDL evolution process is available at

https://github.com/smartdevicelink/sdl_evolution/blob/master/process.md

Thank you,
Theresa Lech

Program Manager - Livio
theresa@livio.io

**Comment by joeljfischer** [comment]
1\. I think the motivation section that's giving the use-case shows a fundamental misunderstanding of the app services feature. The motivation seems to be a way to hold a single POI for other use within the mobile app itself, or to pass a single POI to a 3rd party navigation app, but that's already a supported use-case in SDL using `SendLocation` and the navigation service. Therefore, this proposal as written provides no new functionality at all!

2\. Can you clarify this statement?

> Recently, IVI has moved from AVN (Audio & Visual Navigation) to DA (Display Audio).

3\. You say:

> Therefore, when there is no Native Navigation, it is necessary to share POIs between SDL apps.

Why is it only when there's no native navigation?

4\. The "assumed use case" is extremely unclear, which comes back to (1) above.

a. Why is the user selecting a POI from a list and _then_ it goes into the app service? 
b. Who is showing the popup message? 
c. For 6.a, we can already do this with `SendLocation`. This proposal doesn't seem to be necessary for this use case.
d. For point (7) who's `appHMIType` are we talking about.
e. For (i) who is doing this? The HMI? The app? The mobile library? Who's presenting the popup? How? This is extremely confusing to follow and doesn't seem to make much sense based on current SDL capabilities.
f. For (ii) this isn't how app services work. If the user's preferred navigation app is in NONE, why can they not use that? Who is doing points 10-13? The mobile library? The app?
g. For (b) who is doing all of this? The app? The mobile library? Why not just send the `DialNumber`, why all the indirection through the `POIServiceData`.

5\. Including `poiInfoDataSupported` in `POIServiceManifest` is unneeded. The manifest won't exist if the service isn't supported.

6\. Including only one POI in the `POIServiceData` seems to make this feature not very useful.

I believe that this proposal needs to be totally reworked to make it useful. It has huge downsides despite no acknowledgment of them in this proposal. The comments on the original proposal [here](https://github.com/smartdevicelink/sdl_evolution/issues/776) need to be addressed. Specifically, from [my comment](https://github.com/smartdevicelink/sdl_evolution/issues/776#issuecomment-510522602), I think points 3, 4, 5 (though I think using `LocationDetails` can mitigate some of this, but not all, like how to open an individual POI in the originating app), 9 (or another way that POI searching would work). Additionally, in [Joey's comment](https://github.com/smartdevicelink/sdl_evolution/issues/776#issuecomment-511934096), I think point 11 needs responding to as well.

**Comment by Kazuki-Sugimoto** [comment]
@joeljfischer -san
Thank you for your opinion.
I will reply on behalf of @Shohei-Kawano.

Regarding the SendLocation and the navigation service already supporting the use-case in SDL, if what you are saying is correct, then I will drop this proposal.
However, I cannot find the evidence regarding that matter in any document on GitHub or SmartDeviceLink.com.
So, I would appreciate it if you could provide me the evidence for it.

Thank you.
Best Regards.

**Comment by joeljfischer** [comment]
@Kazuki-Sugimoto Hi, I understand that it can be difficult to find this information.

Please see the [navigation service in the app services proposal](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0167-app-services.md#navigation), this shows `SendLocation` as a handled RPC by the active navigation service. The active navigation service will receive any `SendLocation` requests sent by another app and can then show a popup and / or begin navigation.

**Comment by joeygrover** [comment]
Even more specifically [this flowchart](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0167-app-services.md#rpc-passing) shows how a `SendLocation` RPC is passed from one app, through the IVI, to the navigation app service.

I want to clarify when you say drop this proposal do you mean this POI proposal entirely? I do believe that a POI app service is needed for the platform and could be used to create some impressive systems. A POI app service could supply any navigation with better curated POI's like specific restaurant chains, gas stations, etc. There are just a lot of challenges in making this work well.

**Comment by Kazuki-Sugimoto** [comment]
@joeljfischer -san, @joeygrover -san
Thank you for providing the information on SendLocation. From the information you have provided, I was able to confirmed that this POI proposal can be satisfied with SendLocation + App Service.
Therefore, I insist for this proposal to be dropped.

**Comment by theresalech** [comment]
This proposal has been withdrawn per the author's request.
