### ISSUE TITLE
[Accepted with Revisions] SDL 0279 - Screen Manager Subscribe Buttons

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_evolution#936]
Hello SDL community,

The review of "SDL 0279 - Screen Manager Subscribe Buttons"  begins now and runs through February 18, 2020.  The proposal is available here:

https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0279-screen-manager-subscribe-buttons.md

Reviews are an important part of the SDL evolution process. All reviews should be sent to the associated Github issue at:

https://github.com/smartdevicelink/sdl_evolution/issues/936

What goes into a review?

The goal of the review process is to improve the proposal under review through constructive criticism and, eventually, determine the direction of SDL. When writing your review, here are some questions you might want to answer in your review:

* Is the problem being addressed significant enough to warrant a change to SDL?
* Does this proposal fit well with the feel and direction of SDL?
* If you have used competitors with a similar feature, how do you feel that this proposal compares to those?
* How much effort did you put into your review? A glance, a quick reading, or an in-depth study?
Please state explicitly whether you believe that the proposal should be accepted into SDL.

More information about the SDL evolution process is available at

https://github.com/smartdevicelink/sdl_evolution/blob/master/process.md

Thank you,
Theresa Lech

Program Manager - Livio
theresa@livio.io

**Comment by joeljfischer** [comment]
One alternative that we should also consider that may be better is:

### Alternatives
1. The current solution only allows one observer per `ButtonName`. We could allow multiple observers instead. Then the `unsubscribeButton:` method would need to check the observer and be able to recognize it and remove it. On iOS, this would be similar to the `subscribe` methods on `SystemCapabilityManager`.

**Comment by joeygrover** [comment]
Should we add `CompletionListener`s to subscribe and unsubscribe methods? Not sure if developers will really be able to do much based on the successful or unsuccessful completion or not.

**Comment by joeljfischer** [comment]
There is an error in the Obj/C `SDLSubscribeButtonHandler`, but I missed adding it to the Java one. The interface should be:

```java
public interface OnButtonListener {
    void onPress(ButtonName buttonName, OnButtonPress buttonPress);
    void onEvent(ButtonName buttonName, OnButtonEvent buttonEvent);
    void onError(String info);
}
```

**Comment by theresalech** [comment]
The Steering Committee voted to accept this proposal with revisions.  The revisions will include implementing the alternative approach described in [this comment](https://github.com/smartdevicelink/sdl_evolution/issues/936#issuecomment-586443859) from the author, as well as fixing the `SDLSubscribeButtonHandler` error as detailed in [this comment](https://github.com/smartdevicelink/sdl_evolution/issues/936#issuecomment-587154249) from the author.

**Comment by theresalech** [comment]
@joeljfischer Please advise when a new PR has been entered to update the proposal to reflect the agreed upon revisions. I'll then merge the PR so the proposal is up to date, and enter issues in respective repositories for implementation. Thanks!

**Comment by theresalech** [comment]
Author has updated PR to reflect revisions, and implementation issues have been entered:
- [iOS](https://github.com/smartdevicelink/sdl_ios/issues/1563)
- [JavaSuite](https://github.com/smartdevicelink/sdl_java_suite/issues/1280)
- [JavaScript Suite](https://github.com/smartdevicelink/sdl_javascript_suite/issues/118)
