### ISSUE TITLE
[Accepted with Revisions] SDL 0282 - Screen Manager Alert Manager

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_evolution#948]
Hello SDL community,

The review of "SDL 0282 - Screen Manager Alert Manager"  begins now and runs through March 3, 2020.  The proposal is available here:

https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0282-screen-manager-alerts.md

Reviews are an important part of the SDL evolution process. All reviews should be sent to the associated Github issue at:

https://github.com/smartdevicelink/sdl_evolution/issues/948

What goes into a review?

The goal of the review process is to improve the proposal under review through constructive criticism and, eventually, determine the direction of SDL. When writing your review, here are some questions you might want to answer in your review:

* Is the problem being addressed significant enough to warrant a change to SDL?
* Does this proposal fit well with the feel and direction of SDL?
* If you have used competitors with a similar feature, how do you feel that this proposal compares to those?
* How much effort did you put into your review? A glance, a quick reading, or an in-depth study?
Please state explicitly whether you believe that the proposal should be accepted into SDL.

More information about the SDL evolution process is available at

https://github.com/smartdevicelink/sdl_evolution/blob/master/process.md

Thank you,
Theresa Lech

Program Manager - Livio
theresa@livio.io

**Comment by joeygrover** [comment]
```java
public AlertView(@Nullable String text, @Nullable String secondaryText, @Nullable String tertiaryText, @Nullable Integer timeout, @NonNull Bool showWaitIndicator, @Nullable AlertAudioData audio, @Nullable List<SoftButtonObject> softButtons, @Nullable SdlArtwork icon)
```

I think a builder pattern might be more useful here and follows Android native alerts. this way we also don't need to create multiple more constructors if we add more params; they can simply be added to the builder.

```java
public class AlertView {

    private static final int DEFAULT_TIMEOUT = 5;

    private String text, secondaryText, tertiaryText;
    private int timeout;
    private AlertAudioData audio;
    private boolean showWaitIndicator;
    private List<SoftButtonObject> softButtons;
    private SdlArtwork icon;


    private AlertView(){

    }

    public static class Builder{

        AlertView alertView;
        void Builder(){
            alertView = new AlertView();
        }

        Builder setText(String text){
            alertView.text = text;
            return this;
        }

        Builder setSecondaryText(String secondaryText){
            alertView.secondaryText = secondaryText;
            return this;
        }

        Builder setTertiaryText(String tertiaryText){
            alertView.tertiaryText = tertiaryText;
            return this;
        }

        Builder setTimeout(int timeout){
            alertView.timeout = timeout;
            return this;
        }

        Builder setShowWaitIndicatort(boolean showWaitIndicator){
            alertView.showWaitIndicator = showWaitIndicator;
            return this;
        }

        Builder setSoftButtons(List<SoftButtonObject> softButtons){
            alertView.softButtons = softButtons;
            return this;
        }

        Builder setAudio(AlertAudioData audio){
            alertView.audio = audio;
            return this;
        }
        
        Builder setIcon(SdlArtwork icon){
            alertView.icon = icon;
            return this;
        }
    }
}

```

**Comment by kshala-ford** [comment]
I'm in favor of this proposal and do support the feature. I have a few questions to how the class `SDLAlertAudioData` works. 

1. Except `playTone` it could be used for `Speak` as well therefore I think a different name like `SDLAudioData` could work out better here. It's no big deal though but would allow to SDL-manage speak RPCs pretty easily.

2. The class accepts only a single audio file though playing audio files is per TTS chunk. My suggestion is to create a new class `SDLAudioChunk` that wraps `TTSChunk` and includes `SDLFile`. Convenient constructors of `SDLAlertAudioData` should accept single audio file but there are use cases where a full speech with multiple chunks is being played.

Questions to `presentAlert`: When working with alerts there are different reasons for it to fail. REJECTED or DISALLOWED is returned when it's not shown but ABORTED means the Alert was visible but disappeared due to another higher priority HMI action. Not sure if the inline documentation is clear to this as it states `If the error value in the handler is present, then the alert failed to appear`. `SDLResult` is an important item. Will it be part of the userInfo? I believe it's not that convenient to read the data out of a generic dictionary. May be the result should be included as a parameter in a newly added handler type.

**Comment by joeljfischer** [comment]
1\. See [my proposal](https://github.com/smartdevicelink/sdl_evolution/pull/928) that covers `Speak`. I decided to separate them out when I was writing this first proposal. However, when writing the `PlayAudio` proposal later, I didn't notice how similar the `SDLPlayAudioData` class had become. I think that we could change the `SDLPlayAudioData` class of that proposal to `SDLAudioData`, and then this proposal's `SDLAlertAudioData` could become a subclass of that class.

2\. You're right, there should probably be a way to have multiple pieces of audio data. I would agree to changing the audio data property and initializer to take an array.

3\.

> Not sure if the inline documentation is clear to this as it states If the error value in the handler is present, then the alert failed to appear.

This is already a set-up system. The `error` is sent if `RPCResponse.success == false`. The error does contain the `info` and `resultCode` information. 

```objc
NSLocalizedDescriptionKey: NSLocalizedString(description, nil),
NSLocalizedFailureReasonErrorKey: NSLocalizedString(reason, nil),
```

The `description` is the `resultCode`, and the `reason` is the `info` string. Personally, I think that is probably adequate, but you are right that the documentation isn't entirely clear there. It should be changed to something like "If the error value in the handler is present, then the alert failed to appear or the user aborted it, if not, then the alert dismissed without error."

**Comment by theresalech** [comment]
The Steering Committee voted to accept this proposal with the following revisions:

- Use a builder pattern as described in [this comment].(https://github.com/smartdevicelink/sdl_evolution/issues/948#issuecomment-592122717)
- Change `SDLAlertAudioData` to be a subclass of `SDLAudioData`.
- Change the audio data property and initializer to take an array to allow for multiple pieces of audio data.
- Clarify "if the error value is present, then the alert failed to appear or the user aborted it, if not, then the alert dismissed without error." within the inline documentation for `presentAlert`.

**Comment by theresalech** [comment]
@joeljfischer please advise when a new PR has been entered to update the proposal to reflect the agreed upon revisions. I'll then merge the PR so the proposal is up to date, and enter issues in respective repositories for implementation. Thanks!

**Comment by theresalech** [comment]
The author has updated the proposal to reflect accepted revisions, and implementation issues have been entered:
- [iOS](https://github.com/smartdevicelink/sdl_ios/issues/1579)
- [Java Suite](https://github.com/smartdevicelink/sdl_java_suite/issues/1304)
- [JavaScript Suite](https://github.com/smartdevicelink/sdl_javascript_suite/issues/127)
