### ISSUE TITLE
[Accepted with Revisions] SDL 0284 - DialNumber Text

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_evolution#950]
Hello SDL community,

The review of "SDL 0284 - DialNumber Text"  begins now and runs through March 3, 2020.  The proposal is available here:

https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0284-DialNumber_Text.md

Reviews are an important part of the SDL evolution process. All reviews should be sent to the associated Github issue at:

https://github.com/smartdevicelink/sdl_evolution/issues/950

What goes into a review?

The goal of the review process is to improve the proposal under review through constructive criticism and, eventually, determine the direction of SDL. When writing your review, here are some questions you might want to answer in your review:

* Is the problem being addressed significant enough to warrant a change to SDL?
* Does this proposal fit well with the feel and direction of SDL?
* If you have used competitors with a similar feature, how do you feel that this proposal compares to those?
* How much effort did you put into your review? A glance, a quick reading, or an in-depth study?
Please state explicitly whether you believe that the proposal should be accepted into SDL.

More information about the SDL evolution process is available at

https://github.com/smartdevicelink/sdl_evolution/blob/master/process.md

Thank you,
Theresa Lech

Program Manager - Livio
theresa@livio.io

**Comment by joeygrover** [comment]
1\. Minor item, JavaScript Suite needs to be added to affected platforms since there is an RPC change.
2\. The proposal only includes the HMI_API changes so the RPC Spec ones need to be added:

```xml
    <function name="DialNumber" functionID="DialNumberID" messagetype="request" since="3.0">
    .
    .
    .
        <param name="messageText" type="String" mandatory="false" since="X.X">
            <description>
              Body of text to display to the user.
            </description>
        </param>
    </function>
```

3\. I'd also prefer naming the param to `messagePrompt` or similar. Open to suggestions and not a huge deal either way.

4\. Should we define potential lengths to this text? I imagine it would be useful for developers and OEMs to know exactly what max length should be displayed in these prompts.

**Comment by joeljfischer** [comment]
3\. I think `promptText` might work? Something descriptive so that developers know how it will be used.

4\. I think that adding a `maxLength` of `500` should probably work.

**Comment by JackLivio** [comment]
4. Proxy can use the TextField capability struct to know the width / rows of the message prompt.

**Comment by joeljfischer** [comment]
4. You would have to add a new `TextFieldName` to the RPC enum here: https://github.com/smartdevicelink/rpc_spec/blob/master/MOBILE_API.xml#L753

I would recommend the `TextFieldName` value of `dialNumberPromptText`.

**Comment by theresalech** [comment]
The Steering Committee voted to accept this proposal with the following revisions:
- Add JavaScript Suite as an impacted platform
- Add RPC Spec changes
```xml
    <function name="DialNumber" functionID="DialNumberID" messagetype="request" since="3.0">
    .
    .
    .
        <param name="messageText" type="String" mandatory="false" since="X.X">
            <description>
              Body of text to display to the user.
            </description>
        </param>
    </function>
```
- Use `promptText` as a parameter name in `DialNumber`, instead of `messageText`
- Add `dialNumberPromptText` as a new `TextFieldName`

**Comment by theresalech** [comment]
@MichaelCrimando please advise when a new PR has been entered to update the proposal to reflect the agreed upon revisions. I'll then merge the PR so the proposal is up to date, and enter issues in respective repositories for implementation. Thanks!

**Comment by theresalech** [comment]
The author has updated the proposal to reflect the agreed upon revisions and implementation issues have been entered:
- [RPC Spec](https://github.com/smartdevicelink/rpc_spec/issues/242)
- [SDL Core](https://github.com/smartdevicelink/sdl_core/issues/3320)
- [SDL HMI](https://github.com/smartdevicelink/sdl_hmi/issues/299)
- [Generic HMI](https://github.com/smartdevicelink/generic_hmi/issues/255)
- [iOS](https://github.com/smartdevicelink/sdl_ios/issues/1616)
- [Java Suite](https://github.com/smartdevicelink/sdl_java_suite/issues/1329)
- [JavaScript Suite](https://github.com/smartdevicelink/sdl_javascript_suite/issues/176)
