### ISSUE TITLE
[Accepted] SDL 0288 - Screen Manager Play Audio

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_evolution#962]
Hello SDL community,

The review of "SDL 0288 - Screen Manager Play Audio"  begins now and runs through March 17, 2020.  The proposal is available here:

https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0288-screen-manager-play-audio.md

Reviews are an important part of the SDL evolution process. All reviews should be sent to the associated Github issue at:

https://github.com/smartdevicelink/sdl_evolution/issues/962

What goes into a review?

The goal of the review process is to improve the proposal under review through constructive criticism and, eventually, determine the direction of SDL. When writing your review, here are some questions you might want to answer in your review:

* Is the problem being addressed significant enough to warrant a change to SDL?
* Does this proposal fit well with the feel and direction of SDL?
* If you have used competitors with a similar feature, how do you feel that this proposal compares to those?
* How much effort did you put into your review? A glance, a quick reading, or an in-depth study?
Please state explicitly whether you believe that the proposal should be accepted into SDL.

More information about the SDL evolution process is available at

https://github.com/smartdevicelink/sdl_evolution/blob/master/process.md

Thank you,
Theresa Lech

Program Manager - Livio
theresa@livio.io

**Comment by Sohei-Suzuki** [comment]
In this proposal, only TTS is targeted, how do you handle other audio features such as AudioStreaming?
In addition, some other proposals also target ScreenManager features, but how much functions will be targeted to whole ScreenManager?　
I care about how much functions will be targeted.

**Comment by joeljfischer** [comment]
Hello @Sohei-Suzuki, this proposal is targeted at only one API, the Speak RPC, and making it available to developers through the screen manager API. Audio streaming and other features are outside of the scope of this proposal, and have already been proposed and implemented elsewhere.

I'm not sure what you're saying here:
> In addition, some other proposals also target ScreenManager features, but how much functions will be targeted to whole ScreenManager?　
> I care about how much functions will be targeted.

Could you please clarify?

**Comment by Shohei-Kawano** [comment]
Hi @joeljfischer -san

Thank you for replying to my team member.
He is already out of office today. So I will reply to you.

>and have already been proposed and implemented elsewhere.

Could you tell us which Proposal?

>Could you please clarify?

We feel that ScreenManager is a very useful module. And I feel that ScreenManager supports many features. However, since Proposal is divided, the whole picture of the function that ScreenManager supports is hard to understand for us. So the intent of the question is that we want to know the whole picture.

**Comment by joeljfischer** [comment]
@Sohei-Suzuki @Shohei-Kawano 

> Could you tell us which Proposal?

This one https://github.com/smartdevicelink/sdl_evolution/blob/4061d5225528ee092652698ccc53479f54d097ce/proposals/0113-audiostreammanager.md

> However, since Proposal is divided, the whole picture of the function that ScreenManager supports is hard to understand for us.

The general idea of the screen manager is to provide developers high-level APIs to perform UI operations and other basic functionality for their apps without the need to manually send / receive RPCs. The screen manager and its sub-managers can handle capabilities other other edge cases automatically for developers. The initial proposal [is here](https://github.com/smartdevicelink/sdl_evolution/blob/4061d5225528ee092652698ccc53479f54d097ce/proposals/0134-ios-show-manager.md). Many others have been made over the years to expand its functionality.

However, I believe that both of these questions are out of scope for this review.

**Comment by Shohei-Kawano** [comment]
Hi @joeljfischer -san

Thanks your comment.

We understand that AudioStreming has been proposed elsewhere. Thanks.

**Comment by theresalech** [comment]
The Steering Committee fully agreed to accept this proposal.

**Comment by theresalech** [comment]
Implementation issues entered:
- [iOS](https://github.com/smartdevicelink/sdl_ios/issues/1591)
- [Java Suite](https://github.com/smartdevicelink/sdl_java_suite/issues/1312)
- [JavaScript Suite](https://github.com/smartdevicelink/sdl_javascript_suite/issues/130)
