### ISSUE TITLE
[Accepted with Revisions] SDL 0289 - Support for Set Language Separately

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_evolution#963]
Hello SDL community,

The review of "SDL 0289 - Support for Set Language Separately"  begins now and runs through March 17, 2020.  The proposal is available here:

https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0289-set-language-separately.md

Reviews are an important part of the SDL evolution process. All reviews should be sent to the associated Github issue at:

https://github.com/smartdevicelink/sdl_evolution/issues/963

What goes into a review?

The goal of the review process is to improve the proposal under review through constructive criticism and, eventually, determine the direction of SDL. When writing your review, here are some questions you might want to answer in your review:

* Is the problem being addressed significant enough to warrant a change to SDL?
* Does this proposal fit well with the feel and direction of SDL?
* If you have used competitors with a similar feature, how do you feel that this proposal compares to those?
* How much effort did you put into your review? A glance, a quick reading, or an in-depth study?
Please state explicitly whether you believe that the proposal should be accepted into SDL.

More information about the SDL evolution process is available at

https://github.com/smartdevicelink/sdl_evolution/blob/master/process.md

Thank you,
Theresa Lech

Program Manager - Livio
theresa@livio.io

**Comment by joeljfischer** [comment]
1. Even though the JavaScript_Suite has not yet implemented this feature, I believe that is an affected platform.

**Comment by zhouxin627** [comment]
Hi @joeljfischer ,
Thank you for your opinion. I will add JavaScript_Suite to the `Impacted Platforms`

**Comment by theresalech** [comment]
The Steering Committee voted to accept this proposal with the following revision: add "JavaScript Suite" to the `Impacted Platforms` section.

**Comment by theresalech** [comment]
@zhouxin627 please advise when a new PR has been entered to update the proposal to reflect the agreed upon revisions. I'll then merge the PR so the proposal is up to date, and enter issues in respective repositories for implementation. Thanks!

**Comment by theresalech** [comment]
Author has revised proposal to reflect agreed upon revisions and implementation issues have been entered:
- [iOS](https://github.com/smartdevicelink/sdl_ios/issues/1593)
- [Java Suite](https://github.com/smartdevicelink/sdl_java_suite/issues/1313)
- [JavaScript Suite](https://github.com/smartdevicelink/sdl_javascript_suite/issues/131)
