### ISSUE TITLE
[Accepted with Revisions] SDL 0290 - Modify the range of APT's maxDuration

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_evolution#964]
Hello SDL community,

The review of "SDL 0290 - Modify the range of APT's maxDuration"  begins now and runs through March 17, 2020.  The proposal is available here:

https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0290-modify-the-range-of-APT's-maxDuration.md

Reviews are an important part of the SDL evolution process. All reviews should be sent to the associated Github issue at:

https://github.com/smartdevicelink/sdl_evolution/issues/964

What goes into a review?

The goal of the review process is to improve the proposal under review through constructive criticism and, eventually, determine the direction of SDL. When writing your review, here are some questions you might want to answer in your review:

* Is the problem being addressed significant enough to warrant a change to SDL?
* Does this proposal fit well with the feel and direction of SDL?
* If you have used competitors with a similar feature, how do you feel that this proposal compares to those?
* How much effort did you put into your review? A glance, a quick reading, or an in-depth study?
Please state explicitly whether you believe that the proposal should be accepted into SDL.

More information about the SDL evolution process is available at

https://github.com/smartdevicelink/sdl_evolution/blob/master/process.md

Thank you,
Theresa Lech

Program Manager - Livio
theresa@livio.io

**Comment by joeljfischer** [comment]
1. Unfortunately, this is a major version change to the RPC spec and Core due to the change of a parameter. If a developer sets 1000 ms, it currently succeeds, but it will fail when this change is made. That's okay, and I agree that the `minValue` is too low, but it needs to be noted that this is a major version change that could only occur in RPC Spec / Core 7.0 and would require app library mitigation strategies.

**Comment by zhouxin627** [comment]
Hi @joeljfischer ,
Thank you for your opinion. I will add the description about version change as you pointed out.

**Comment by theresalech** [comment]
The Steering Committee voted to accept this proposal with the revision to clarify that the RPC Spec and Core are both impacted platforms which will require major version changes upon implementation of this proposal.

**Comment by theresalech** [comment]
@zhouxin627 please advise when a new PR has been entered to update the proposal to reflect the agreed upon revisions. I'll then merge the PR so the proposal is up to date, and enter issues in respective repositories for implementation. Thanks!

**Comment by theresalech** [comment]
The author has updated the proposal to reflect agreed upon revisions, and implementation issues have been entered:
- [RPC](https://github.com/smartdevicelink/rpc_spec/issues/230)
- [Core](https://github.com/smartdevicelink/sdl_core/issues/3296)
