### ISSUE TITLE
[Rejected] SDL 0167 Revisions - App Services - Voice Assistant

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_evolution#970]
Hello SDL community,

The review of "SDL 0167 revisions - Voice Assistant" begins now and runs through March 24, 2020.

This will be a review of proposed revisions to the "Voice Assistant" service type, within the larger previously accepted proposal [SDL 0167](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0167-app-services.md#voice-assistant).  It should be noted that while Navigation, Weather, and Media service types have been implemented, Voice Assistant has not and therefore can be revised.

The pull request outlining the revisions under review is available here:

https://github.com/smartdevicelink/sdl_evolution/pull/937

Reviews are an important part of the SDL evolution process. All reviews should be sent to the associated Github issue at:

https://github.com/smartdevicelink/sdl_evolution/issues/970

What goes into a review?

The goal of the review process is to improve the proposal under review through constructive criticism and, eventually, determine the direction of SDL. When writing your review, here are some questions you might want to answer in your review:

* Is the problem being addressed significant enough to warrant a change to SDL?
* Does this proposal fit well with the feel and direction of SDL?
* If you have used competitors with a similar feature, how do you feel that this proposal compares to those?
* How much effort did you put into your review? A glance, a quick reading, or an in-depth study?
Please state explicitly whether you believe that the proposal should be accepted into SDL.

More information about the SDL evolution process is available at

https://github.com/smartdevicelink/sdl_evolution/blob/master/process.md

Thank you,
Theresa Lech

Program Manager - Livio
theresa@livio.io

**Comment by JackLivio** [comment]
1.

> This provider needs to be flushed out with a lot of extra details as its functionality is far reaching.

DId you mean for this to be in the proposal? This was copy and pasted from the original proposal. What other details need to be flushed out still?

2.  Should there be parameters added to the `VoiceAssistantServiceData` struct?

3. `VoiceAssistantTrigger` is not defined in the revision but is the type for `triggerSource`. Should this be type `VoiceAssistantOperatingMode` instead?

4. The xml changes do not specify which are for the mobile_api.xml or hmi_api.xml

5. VR.GetCapabilities are the capabilities provided by the HMI. Are these voice assistant capabilities decided by the app, the vehicle, or both?

**Comment by joeljfischer** [comment]
This proposal solves none of the issues that have been brought up time and time again when the previous voice assistant proposals have come forward. It's a repackaging of the same proposals that have been rejected and withdrawn. The authors state that it should be iterated upon step-by-step, but the problem with that is that we are locking ourselves into an approach that must be deprecated if a "full formed" approach is proposed. I'm strongly against this proposal.

The maintainers have been working on a proposal for this functionality and I would recommend that we wait for that proposal instead and reject or withdraw this proposal.

**Comment by Kazuki-Sugimoto** [comment]
@joeljfischer -san
>The maintainers have been working on a proposal for this functionality and I would recommend that we wait for that proposal instead and reject or withdraw this proposal.

When is the proposal created?
We would like to confirm that and decide whether to withdraw this proposal.

**Comment by joeygrover** [comment]
The proposal modifications are to an already accepted and implemented proposal. This is not how this should be done. A completely new proposal should be entered, not a modification to the overall App Services proposal.

**Comment by theresalech** [comment]
The Steering Committee voted to reject this proposal.  It was acknowledged that this proposal should have been entered as a new proposal, as SDL 0167 has already been accepted and implemented.  Additionally, the author agreed to move forward with reviewing the Project Maintainer's proposed solution, which should be ready for Steering Committee review soon, in place of the solution proposed here.
