### ISSUE TITLE
[Accepted with Revisions] SDL 0256 Revisions - Refactor Fuel Information Related Vehicle Data

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_evolution#972]
Hello SDL community,

The review of "Revise SDL-0256 Refactor Fuel Information Related Vehicle Data" begins now and runs through March 24, 2020.

This will be a review of proposed revisions to a previously accepted but not yet implemented proposal, [SDL 0256](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0256-Refactor-Fuel-Information-Related-Vehicle-Data.md).  

The pull request outlining the revisions under review is available here:

https://github.com/smartdevicelink/sdl_evolution/pull/939

Reviews are an important part of the SDL evolution process. All reviews should be sent to the associated Github issue at:

https://github.com/smartdevicelink/sdl_evolution/issues/972

What goes into a review?

The goal of the review process is to improve the proposal under review through constructive criticism and, eventually, determine the direction of SDL. When writing your review, here are some questions you might want to answer in your review:

* Is the problem being addressed significant enough to warrant a change to SDL?
* Does this proposal fit well with the feel and direction of SDL?
* If you have used competitors with a similar feature, how do you feel that this proposal compares to those?
* How much effort did you put into your review? A glance, a quick reading, or an in-depth study?
Please state explicitly whether you believe that the proposal should be accepted into SDL.

More information about the SDL evolution process is available at

https://github.com/smartdevicelink/sdl_evolution/blob/master/process.md

Thank you,
Theresa Lech

Program Manager - Livio
theresa@livio.io

**Comment by JackLivio** [comment]
@ydementieiev I believe the history tags you added need to say since="2.0" instead of "1.0". 

The vehicle data rpc messages were introduced in version "2.0"

```
<function name="SubscribeVehicleData" functionID="SubscribeVehicleDataID" messagetype="response" since="2.0">
```

**Comment by IGapchuk** [comment]
@JackLivio Thank you for the feedback! Please take a look at the commit https://github.com/smartdevicelink/sdl_evolution/commit/03748333da96b1c673663496e82450e44ce8eca9. The requested changes were made. Please let me know if you have any questions or comments.

**Comment by theresalech** [comment]
The Steering Committee voted to accept this proposal with revisions.  The author will revise to use "2.0" in the history tag for `SubscribeVehicleData`.

**Comment by theresalech** [comment]
The author has revised the PR to reflect the agreed upon revisions, and comments have been left on implementation issues to note the accepted changes to the original proposal:
- [RPC](https://github.com/smartdevicelink/rpc_spec/issues/204)
- [Core](https://github.com/smartdevicelink/sdl_core/issues/3124)
- [SDL HMI](https://github.com/smartdevicelink/sdl_hmi/issues/261)
- [Java Suite](https://github.com/smartdevicelink/sdl_java_suite/issues/1223)
- [iOS](https://github.com/smartdevicelink/sdl_ios/issues/1472)
