### ISSUE TITLE
[Accepted with Revisions] SDL 0295 - Screen Manager Microphone Input Manager

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_evolution#974]
Hello SDL community,

The review of "SDL 0295 - Screen Manager Microphone Input Manager" begins now and runs through March 24, 2020.  The proposal is available here:

https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0295-screen-manager-audio-pass-thru.md

Reviews are an important part of the SDL evolution process. All reviews should be sent to the associated Github issue at:

https://github.com/smartdevicelink/sdl_evolution/issues/974

What goes into a review?

The goal of the review process is to improve the proposal under review through constructive criticism and, eventually, determine the direction of SDL. When writing your review, here are some questions you might want to answer in your review:

* Is the problem being addressed significant enough to warrant a change to SDL?
* Does this proposal fit well with the feel and direction of SDL?
* If you have used competitors with a similar feature, how do you feel that this proposal compares to those?
* How much effort did you put into your review? A glance, a quick reading, or an in-depth study?
Please state explicitly whether you believe that the proposal should be accepted into SDL.

More information about the SDL evolution process is available at

https://github.com/smartdevicelink/sdl_evolution/blob/master/process.md

Thank you,
Theresa Lech

Program Manager - Livio
theresa@livio.io

**Comment by joeygrover** [comment]
1. The java suite should use a builder pattern instead of the single long constructor for `MicrophoneInputView`. See the [Screen Manager Alert Manager
 proposal](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0282-screen-manager-alerts.md).
2. The `MicrophoneInputView` should also have the dismiss method call like the scrollable message and alert views that have recently been accepted. See the [Screen Manager Alert Manager
 proposal](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0282-screen-manager-alerts.md)

**Comment by theresalech** [comment]
The Steering Committee voted to accept this proposal with the following revisions:

1. The Java Suite should use a builder pattern instead of the single long constructor for `MicrophoneInputView`. See the [Screen Manager Alert Manager
 proposal](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0282-screen-manager-alerts.md).
2. The `MicrophoneInputView` should also have the dismiss method call like the scrollable message and alert views that have recently been accepted. See the [Screen Manager Alert Manager proposal](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0282-screen-manager-alerts.md).

**Comment by theresalech** [comment]
The author has updated this proposal to reflect the agreed upon revisions, and implementation issues have been entered:
- [iOS](https://github.com/smartdevicelink/sdl_ios/issues/1605)
- [Java Suite](https://github.com/smartdevicelink/sdl_java_suite/issues/1322)
- [JavaScript Suite](https://github.com/smartdevicelink/sdl_javascript_suite/issues/167)
